// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module GPCDCacheWrapper(
  input         clock,
                reset,
                auto_dcacheClient_out_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_b_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [2:0]  auto_dcacheClient_out_b_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_dcacheClient_out_b_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [3:0]  auto_dcacheClient_out_b_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [4:0]  auto_dcacheClient_out_b_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [31:0] auto_dcacheClient_out_b_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [7:0]  auto_dcacheClient_out_b_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [63:0] auto_dcacheClient_out_b_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_dcacheClient_out_b_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_c_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [2:0]  auto_dcacheClient_out_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_dcacheClient_out_d_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [3:0]  auto_dcacheClient_out_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [4:0]  auto_dcacheClient_out_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_dcacheClient_out_d_bits_sink,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_dcacheClient_out_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [63:0] auto_dcacheClient_out_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_dcacheClient_out_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_e_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                io_cpu_req_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [39:0] io_cpu_req_bits_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [6:0]  io_cpu_req_bits_tag,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [4:0]  io_cpu_req_bits_cmd,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_cpu_req_bits_size,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_cpu_req_bits_signed,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_cpu_req_bits_dprv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_cpu_req_bits_dv,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_req_bits_phys,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_req_bits_no_alloc,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_req_bits_no_xcpt,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [63:0] io_cpu_req_bits_data,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [7:0]  io_cpu_req_bits_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_cpu_s1_kill,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_asid,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [63:0] io_cpu_s1_data_data,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [7:0]  io_cpu_s1_data_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_cpu_s2_kill,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_keep_clock_enabled,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_req_ready,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_ae_ptw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_ae_final,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pf,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_gf,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_hr,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_hw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_hx,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [9:0]  io_ptw_resp_bits_pte_reserved_for_future,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [43:0] io_ptw_resp_bits_pte_ppn,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_resp_bits_pte_reserved_for_software,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_resp_bits_pte_d,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_a,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_g,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_u,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_r,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_pte_v,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_resp_bits_level,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_resp_bits_fragmented_superpage,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_homogeneous,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_resp_bits_gpa_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [38:0] io_ptw_resp_bits_gpa_bits,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_resp_bits_gpa_is_pte,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [3:0]  io_ptw_ptbr_mode,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [15:0] io_ptw_ptbr_asid,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [43:0] io_ptw_ptbr_ppn,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [3:0]  io_ptw_hgatp_mode,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [15:0] io_ptw_hgatp_asid,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [43:0] io_ptw_hgatp_ppn,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [3:0]  io_ptw_vsatp_mode,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [15:0] io_ptw_vsatp_asid,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [43:0] io_ptw_vsatp_ppn,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_debug,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_cease,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_wfi,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_status_isa,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_status_dprv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_dv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_status_prv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_v,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_sd,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [22:0] io_ptw_status_zero2,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_mpv,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_gva,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_mbe,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_sbe,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_status_sxl,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_uxl,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_sd_rv32,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [7:0]  io_ptw_status_zero1,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_tsr,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_tw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_tvm,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_mxr,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_sum,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_mprv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_status_xs,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_fs,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_mpp,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_vs,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_status_spp,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_mpie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_ube,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_spie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_upie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_mie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_hie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_sie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_status_uie,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_hstatus_zero6,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_hstatus_vsxl,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [8:0]  io_ptw_hstatus_zero5,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_hstatus_vtsr,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_hstatus_vtw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_hstatus_vtvm,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_hstatus_zero3,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [5:0]  io_ptw_hstatus_vgein,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_hstatus_zero2,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_hstatus_hu,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_hstatus_spvp,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_hstatus_spv,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_hstatus_gva,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_hstatus_vsbe,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [4:0]  io_ptw_hstatus_zero1,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_debug,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_cease,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_wfi,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_gstatus_isa,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_gstatus_dprv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_dv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_gstatus_prv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_v,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_sd,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [22:0] io_ptw_gstatus_zero2,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_mpv,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_gva,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_mbe,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_sbe,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_gstatus_sxl,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_uxl,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_sd_rv32,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [7:0]  io_ptw_gstatus_zero1,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_tsr,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_tw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_tvm,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_mxr,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_sum,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_mprv,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_gstatus_xs,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_fs,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_mpp,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_vs,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_gstatus_spp,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_mpie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_ube,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_spie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_upie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_mie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_hie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_sie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_gstatus_uie,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_0_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_0_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_0_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_0_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_0_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_0_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_0_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_0_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_1_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_1_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_1_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_1_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_1_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_1_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_1_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_1_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_2_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_2_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_2_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_2_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_2_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_2_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_2_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_2_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_3_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_3_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_3_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_3_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_3_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_3_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_3_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_3_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_4_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_4_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_4_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_4_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_4_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_4_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_4_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_4_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_5_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_5_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_5_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_5_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_5_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_5_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_5_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_5_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_6_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_6_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_6_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_6_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_6_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_6_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_6_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_6_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_7_cfg_l,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [1:0]  io_ptw_pmp_7_cfg_res,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_7_cfg_a,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_pmp_7_cfg_x,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_7_cfg_w,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_pmp_7_cfg_r,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [29:0] io_ptw_pmp_7_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [31:0] io_ptw_pmp_7_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_customCSRs_csrs_0_ren,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_0_wen,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [63:0] io_ptw_customCSRs_csrs_0_wdata,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_0_value,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_customCSRs_csrs_1_ren,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_1_wen,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [63:0] io_ptw_customCSRs_csrs_1_wdata,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_1_value,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_customCSRs_csrs_2_ren,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_2_wen,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [63:0] io_ptw_customCSRs_csrs_2_wdata,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_2_value,	// src/main/scala/rocket/HellaCache.scala:235:14
  input         io_ptw_customCSRs_csrs_3_ren,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_3_wen,	// src/main/scala/rocket/HellaCache.scala:235:14
  input  [63:0] io_ptw_customCSRs_csrs_3_wdata,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_3_value,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        auto_dcacheClient_out_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_dcacheClient_out_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [3:0]  auto_dcacheClient_out_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [4:0]  auto_dcacheClient_out_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [31:0] auto_dcacheClient_out_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [7:0]  auto_dcacheClient_out_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_dcacheClient_out_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_dcacheClient_out_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_b_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_c_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_dcacheClient_out_c_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_c_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [3:0]  auto_dcacheClient_out_c_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [4:0]  auto_dcacheClient_out_c_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [31:0] auto_dcacheClient_out_c_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_dcacheClient_out_c_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_dcacheClient_out_c_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_dcacheClient_out_e_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [1:0]  auto_dcacheClient_out_e_bits_sink,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        io_cpu_req_ready,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_nack,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_nack_cause_raw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_uncached,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [31:0] io_cpu_s2_paddr,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_cpu_resp_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [39:0] io_cpu_resp_bits_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [6:0]  io_cpu_resp_bits_tag,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [4:0]  io_cpu_resp_bits_cmd,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [1:0]  io_cpu_resp_bits_size,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_cpu_resp_bits_signed,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [1:0]  io_cpu_resp_bits_dprv,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_cpu_resp_bits_dv,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [63:0] io_cpu_resp_bits_data,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [7:0]  io_cpu_resp_bits_mask,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_cpu_resp_bits_replay,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_resp_bits_has_data,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [63:0] io_cpu_resp_bits_data_word_bypass,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_resp_bits_data_raw,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_resp_bits_store_data,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_cpu_replay_next,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_ma_ld,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_ma_st,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_pf_ld,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_pf_st,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_gf_ld,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_gf_st,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_ae_ld,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_s2_xcpt_ae_st,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [39:0] io_cpu_s2_gpa,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_cpu_s2_gpa_is_pte,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_ordered,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_acquire,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_release,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_grant,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_tlbMiss,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_blocked,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_canAcceptStoreThenLoad,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_canAcceptStoreThenRMW,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_canAcceptLoadThenLoad,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_storeBufferEmptyAfterLoad,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_perf_storeBufferEmptyAfterStore,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_cpu_clock_enabled,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_req_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_req_bits_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [26:0] io_ptw_req_bits_bits_addr,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_ptw_req_bits_bits_need_gpa,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_req_bits_bits_vstage1,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_req_bits_bits_stage2,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_0_stall,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_0_set,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [63:0] io_ptw_customCSRs_csrs_0_sdata,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_ptw_customCSRs_csrs_1_stall,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_1_set,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [63:0] io_ptw_customCSRs_csrs_1_sdata,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_ptw_customCSRs_csrs_2_stall,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_2_set,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [63:0] io_ptw_customCSRs_csrs_2_sdata,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_ptw_customCSRs_csrs_3_stall,	// src/main/scala/rocket/HellaCache.scala:235:14
                io_ptw_customCSRs_csrs_3_set,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [63:0] io_ptw_customCSRs_csrs_3_sdata,	// src/main/scala/rocket/HellaCache.scala:235:14
  output        io_errors_bus_valid,	// src/main/scala/rocket/HellaCache.scala:235:14
  output [31:0] io_errors_bus_bits	// src/main/scala/rocket/HellaCache.scala:235:14
);

  wire         _dtlb_io_req_ready;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_miss;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire [31:0]  _dtlb_io_resp_paddr;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire [39:0]  _dtlb_io_resp_gpa;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_pf_inst;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_ae_inst;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_cacheable;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dtlb_io_resp_must_alloc;	// src/main/scala/rocket/GPCDCache.scala:46:20
  wire         _dcacheClient_io_req_ready;	// src/main/scala/rocket/GPCDCache.scala:17:32
  wire         _dcacheClient_io_resp_valid;	// src/main/scala/rocket/GPCDCache.scala:17:32
  wire [1:0]   _dcacheClient_io_resp_bits_source;	// src/main/scala/rocket/GPCDCache.scala:17:32
  wire [4:0]   _dcacheClient_io_resp_bits_dest;	// src/main/scala/rocket/GPCDCache.scala:17:32
  wire [1:0]   _dcacheClient_io_resp_bits_status;	// src/main/scala/rocket/GPCDCache.scala:17:32
  wire [511:0] _dcacheClient_io_resp_bits_data;	// src/main/scala/rocket/GPCDCache.scala:17:32
  wire [39:0]  s0_tlbReq_vaddr = io_cpu_req_bits_addr;	// src/main/scala/rocket/GPCDCache.scala:36:27
  wire         s0_tlbReq_passthrough = io_cpu_req_bits_phys;	// src/main/scala/rocket/GPCDCache.scala:36:27
  wire [1:0]   s0_tlbReq_size = io_cpu_req_bits_size;	// src/main/scala/rocket/GPCDCache.scala:36:27
  wire [4:0]   s0_tlbReq_cmd = io_cpu_req_bits_cmd;	// src/main/scala/rocket/GPCDCache.scala:36:27
  wire [1:0]   s0_tlbReq_prv = io_cpu_req_bits_dprv;	// src/main/scala/rocket/GPCDCache.scala:36:27
  wire         s0_tlbReq_v = io_cpu_req_bits_dv;	// src/main/scala/rocket/GPCDCache.scala:36:27
  wire [1:0]   cacheReq_refillCoh = 2'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :79:26
  wire         s1_tlbXcpt_gf_ld = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :71:28, :79:26
  wire         s1_tlbXcpt_gf_st = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :71:28, :79:26
  wire         cacheReq_noAlloc = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  wire         cacheReq_isRefill = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  wire         _io_cpu_req_ready_output;
  wire         s0_valid = _io_cpu_req_ready_output & io_cpu_req_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35
  wire         _s0_write_T_3 = io_cpu_req_bits_cmd == 5'h7;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_5 = io_cpu_req_bits_cmd == 5'h4;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_6 = io_cpu_req_bits_cmd == 5'h9;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_7 = io_cpu_req_bits_cmd == 5'hA;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_8 = io_cpu_req_bits_cmd == 5'hB;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_12 = io_cpu_req_bits_cmd == 5'h8;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_13 = io_cpu_req_bits_cmd == 5'hC;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_14 = io_cpu_req_bits_cmd == 5'hD;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_15 = io_cpu_req_bits_cmd == 5'hE;	// src/main/scala/util/package.scala:16:47
  wire         _s0_write_T_16 = io_cpu_req_bits_cmd == 5'hF;	// src/main/scala/util/package.scala:16:47
  wire         s0_read =
    io_cpu_req_bits_cmd == 5'h0 | io_cpu_req_bits_cmd == 5'h10
    | io_cpu_req_bits_cmd == 5'h6 | _s0_write_T_3 | _s0_write_T_5 | _s0_write_T_6
    | _s0_write_T_7 | _s0_write_T_8 | _s0_write_T_12 | _s0_write_T_13 | _s0_write_T_14
    | _s0_write_T_15 | _s0_write_T_16;	// src/main/scala/rocket/Consts.scala:85:68, src/main/scala/rocket/GPCDCache.scala:36:40, src/main/scala/util/package.scala:16:47
  wire         s0_write =
    io_cpu_req_bits_cmd == 5'h1 | io_cpu_req_bits_cmd == 5'h11 | _s0_write_T_3
    | _s0_write_T_5 | _s0_write_T_6 | _s0_write_T_7 | _s0_write_T_8 | _s0_write_T_12
    | _s0_write_T_13 | _s0_write_T_14 | _s0_write_T_15 | _s0_write_T_16;	// src/main/scala/rocket/Consts.scala:86:{32,49,76}, src/main/scala/util/package.scala:16:47
  wire         s0_readwrite =
    s0_read | s0_write | io_cpu_req_bits_cmd == 5'h2 | io_cpu_req_bits_cmd == 5'h3;	// src/main/scala/rocket/Consts.scala:84:{35,52}, :85:68, :86:76, src/main/scala/rocket/GPCDCache.scala:34:42
  reg  [39:0]  s1_req_addr;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg  [6:0]   s1_req_tag;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg  [4:0]   s1_req_cmd;	// src/main/scala/rocket/GPCDCache.scala:64:25
  wire [4:0]   cacheReq_cmd = s1_req_cmd;	// src/main/scala/rocket/GPCDCache.scala:64:25, :79:26
  reg  [1:0]   s1_req_size;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg          s1_req_signed;	// src/main/scala/rocket/GPCDCache.scala:64:25
  wire         cacheReq_signed = s1_req_signed;	// src/main/scala/rocket/GPCDCache.scala:64:25, :79:26
  reg  [1:0]   s1_req_dprv;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg          s1_req_dv;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg          s1_req_phys;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg          s1_req_no_alloc;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg          s1_req_no_xcpt;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg  [63:0]  s1_req_data;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg  [7:0]   s1_req_mask;	// src/main/scala/rocket/GPCDCache.scala:64:25
  reg          s1_valid_REG;	// src/main/scala/rocket/GPCDCache.scala:65:25
  wire         s1_valid =
    s1_valid_REG & ~io_cpu_s1_kill
    & ~(s1_req_cmd == 5'h14 | s1_req_cmd == 5'h15 | s1_req_cmd == 5'h16);	// src/main/scala/rocket/GPCDCache.scala:53:51, :58:40, :59:40, :64:25, :65:{25,39,55}, :66:{5,18,45,59,73}
  reg          s1_tlbResp_miss;	// src/main/scala/rocket/GPCDCache.scala:69:29
  reg  [31:0]  s1_tlbResp_paddr;	// src/main/scala/rocket/GPCDCache.scala:69:29
  reg  [39:0]  s1_tlbResp_gpa;	// src/main/scala/rocket/GPCDCache.scala:69:29
  reg          s1_tlbResp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire         s1_tlbXcpt_pf_ld = s1_tlbResp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29, :71:28
  reg          s1_tlbResp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire         s1_tlbXcpt_pf_st = s1_tlbResp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:69:29, :71:28
  reg          s1_tlbResp_pf_inst;	// src/main/scala/rocket/GPCDCache.scala:69:29
  reg          s1_tlbResp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire         s1_tlbXcpt_ae_ld = s1_tlbResp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29, :71:28
  reg          s1_tlbResp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire         s1_tlbXcpt_ae_st = s1_tlbResp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:69:29, :71:28
  reg          s1_tlbResp_ae_inst;	// src/main/scala/rocket/GPCDCache.scala:69:29
  reg          s1_tlbResp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire         s1_tlbXcpt_ma_ld = s1_tlbResp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29, :71:28
  reg          s1_tlbResp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire         s1_tlbXcpt_ma_st = s1_tlbResp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:69:29, :71:28
  reg          s1_tlbResp_cacheable;	// src/main/scala/rocket/GPCDCache.scala:69:29
  reg          s1_tlbResp_must_alloc;	// src/main/scala/rocket/GPCDCache.scala:69:29
  wire [1:0]   s1_tlbHasXcpt_lo_lo = {s1_tlbXcpt_ae_ld, s1_tlbXcpt_ae_st};	// src/main/scala/rocket/GPCDCache.scala:71:28, :72:34
  wire [1:0]   s1_tlbHasXcpt_lo_hi = {s1_tlbXcpt_gf_ld, s1_tlbXcpt_gf_st};	// src/main/scala/rocket/GPCDCache.scala:71:28, :72:34
  wire [3:0]   s1_tlbHasXcpt_lo = {s1_tlbHasXcpt_lo_hi, s1_tlbHasXcpt_lo_lo};	// src/main/scala/rocket/GPCDCache.scala:72:34
  wire [1:0]   s1_tlbHasXcpt_hi_lo = {s1_tlbXcpt_pf_ld, s1_tlbXcpt_pf_st};	// src/main/scala/rocket/GPCDCache.scala:71:28, :72:34
  wire [1:0]   s1_tlbHasXcpt_hi_hi = {s1_tlbXcpt_ma_ld, s1_tlbXcpt_ma_st};	// src/main/scala/rocket/GPCDCache.scala:71:28, :72:34
  wire [3:0]   s1_tlbHasXcpt_hi = {s1_tlbHasXcpt_hi_hi, s1_tlbHasXcpt_hi_lo};	// src/main/scala/rocket/GPCDCache.scala:72:34
  wire         s1_tlbHasXcpt = |{s1_tlbHasXcpt_hi, s1_tlbHasXcpt_lo};	// src/main/scala/rocket/GPCDCache.scala:72:{34,41}
  wire         cacheReqValid = s1_valid & ~s1_tlbHasXcpt & ~s1_tlbResp_miss;	// src/main/scala/rocket/GPCDCache.scala:65:55, :69:29, :72:41, :76:{35,50,53}
  wire         s1_replayReq = cacheReqValid & ~_dcacheClient_io_req_ready;	// src/main/scala/rocket/GPCDCache.scala:17:32, :76:50, :77:{36,39}
  wire [38:0]  cacheReq_paddr = {7'h0, s1_tlbResp_paddr};	// src/main/scala/rocket/GPCDCache.scala:69:29, :79:26, :80:18
  wire [2:0]   cacheReq_size = {1'h0, s1_req_size};	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :64:25, :79:26, :82:17
  wire [511:0] cacheReq_wdata = {448'h0, io_cpu_s1_data_data};	// src/main/scala/rocket/GPCDCache.scala:79:26, :84:18
  wire [63:0]  cacheReq_wmask = {56'h0, io_cpu_s1_data_mask};	// src/main/scala/rocket/GPCDCache.scala:79:26, :85:18
  wire [1:0]   cacheReq_source = s1_req_tag[1:0];	// src/main/scala/rocket/GPCDCache.scala:64:25, :79:26, :88:32
  wire [4:0]   cacheReq_dest = s1_req_tag[6:2];	// src/main/scala/rocket/GPCDCache.scala:64:25, :79:26, :89:30
  reg          s2_valid_REG;	// src/main/scala/rocket/GPCDCache.scala:98:25
  wire         s2_valid = s2_valid_REG & ~io_cpu_s2_kill;	// src/main/scala/rocket/GPCDCache.scala:98:{25,36,39}
  reg          s2_tlbResp_miss;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg  [31:0]  s2_tlbResp_paddr;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg  [39:0]  s2_tlbResp_gpa;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_gpa_is_pte;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_pf_inst;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_gf_ld;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_gf_st;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_gf_inst;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_ae_inst;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_ma_inst;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_cacheable;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_must_alloc;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_tlbResp_prefetchable;	// src/main/scala/rocket/GPCDCache.scala:99:29
  reg          s2_replayReq;	// src/main/scala/rocket/GPCDCache.scala:102:29
  assign _io_cpu_req_ready_output =
    ~(~_dtlb_io_req_ready & ~io_cpu_req_bits_phys | s1_replayReq);	// src/main/scala/rocket/Consts.scala:86:32, src/main/scala/rocket/GPCDCache.scala:46:20, :77:36, :139:20, :140:{8,27,30,43,60}, :141:22, src/main/scala/util/package.scala:16:47
  always @(posedge clock) begin
    if (s0_valid) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35
      s1_req_addr <= io_cpu_req_bits_addr;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_tag <= io_cpu_req_bits_tag;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_cmd <= io_cpu_req_bits_cmd;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_size <= io_cpu_req_bits_size;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_signed <= io_cpu_req_bits_signed;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_dprv <= io_cpu_req_bits_dprv;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_dv <= io_cpu_req_bits_dv;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_phys <= io_cpu_req_bits_phys;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_no_alloc <= io_cpu_req_bits_no_alloc;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_no_xcpt <= io_cpu_req_bits_no_xcpt;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_data <= io_cpu_req_bits_data;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_req_mask <= io_cpu_req_bits_mask;	// src/main/scala/rocket/GPCDCache.scala:64:25
      s1_tlbResp_miss <= _dtlb_io_resp_miss;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_paddr <= _dtlb_io_resp_paddr;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_gpa <= _dtlb_io_resp_gpa;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_pf_ld <= _dtlb_io_resp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_pf_st <= _dtlb_io_resp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_pf_inst <= _dtlb_io_resp_pf_inst;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_ae_ld <= _dtlb_io_resp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_ae_st <= _dtlb_io_resp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_ae_inst <= _dtlb_io_resp_ae_inst;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_ma_ld <= _dtlb_io_resp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_ma_st <= _dtlb_io_resp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_cacheable <= _dtlb_io_resp_cacheable;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
      s1_tlbResp_must_alloc <= _dtlb_io_resp_must_alloc;	// src/main/scala/rocket/GPCDCache.scala:46:20, :69:29
    end
    s1_valid_REG <= s0_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/GPCDCache.scala:65:25
    s2_valid_REG <= s1_valid;	// src/main/scala/rocket/GPCDCache.scala:65:55, :98:25
    if (s1_valid) begin	// src/main/scala/rocket/GPCDCache.scala:65:55
      s2_tlbResp_miss <= s1_tlbResp_miss;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_paddr <= s1_tlbResp_paddr;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_gpa <= s1_tlbResp_gpa;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_pf_ld <= s1_tlbResp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_pf_st <= s1_tlbResp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_pf_inst <= s1_tlbResp_pf_inst;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_ae_ld <= s1_tlbResp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_ae_st <= s1_tlbResp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_ae_inst <= s1_tlbResp_ae_inst;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_ma_ld <= s1_tlbResp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_ma_st <= s1_tlbResp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_cacheable <= s1_tlbResp_cacheable;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
      s2_tlbResp_must_alloc <= s1_tlbResp_must_alloc;	// src/main/scala/rocket/GPCDCache.scala:69:29, :99:29
    end
    s2_tlbResp_gpa_is_pte <= ~s1_valid & s2_tlbResp_gpa_is_pte;	// src/main/scala/rocket/GPCDCache.scala:65:55, :99:29
    s2_tlbResp_gf_ld <= ~s1_valid & s2_tlbResp_gf_ld;	// src/main/scala/rocket/GPCDCache.scala:65:55, :99:29
    s2_tlbResp_gf_st <= ~s1_valid & s2_tlbResp_gf_st;	// src/main/scala/rocket/GPCDCache.scala:65:55, :99:29
    s2_tlbResp_gf_inst <= ~s1_valid & s2_tlbResp_gf_inst;	// src/main/scala/rocket/GPCDCache.scala:65:55, :99:29
    s2_tlbResp_ma_inst <= ~s1_valid & s2_tlbResp_ma_inst;	// src/main/scala/rocket/GPCDCache.scala:65:55, :99:29
    s2_tlbResp_prefetchable <= ~s1_valid & s2_tlbResp_prefetchable;	// src/main/scala/rocket/GPCDCache.scala:65:55, :99:29
    s2_replayReq <= s1_replayReq;	// src/main/scala/rocket/GPCDCache.scala:77:36, :102:29
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:9];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        s1_req_addr = {_RANDOM[4'h0], _RANDOM[4'h1][7:0]};	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_tag = _RANDOM[4'h1][14:8];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_cmd = _RANDOM[4'h1][19:15];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_size = _RANDOM[4'h1][21:20];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_signed = _RANDOM[4'h1][22];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_dprv = _RANDOM[4'h1][24:23];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_dv = _RANDOM[4'h1][25];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_phys = _RANDOM[4'h1][26];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_no_alloc = _RANDOM[4'h1][27];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_no_xcpt = _RANDOM[4'h1][28];	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_data = {_RANDOM[4'h1][31:29], _RANDOM[4'h2], _RANDOM[4'h3][28:0]};	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_req_mask = {_RANDOM[4'h3][31:29], _RANDOM[4'h4][4:0]};	// src/main/scala/rocket/GPCDCache.scala:64:25
        s1_valid_REG = _RANDOM[4'h4][5];	// src/main/scala/rocket/GPCDCache.scala:64:25, :65:25
        s1_tlbResp_miss = _RANDOM[4'h4][6];	// src/main/scala/rocket/GPCDCache.scala:64:25, :69:29
        s1_tlbResp_paddr = {_RANDOM[4'h4][31:7], _RANDOM[4'h5][6:0]};	// src/main/scala/rocket/GPCDCache.scala:64:25, :69:29
        s1_tlbResp_gpa = {_RANDOM[4'h5][31:7], _RANDOM[4'h6][14:0]};	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_pf_ld = _RANDOM[4'h6][16];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_pf_st = _RANDOM[4'h6][17];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_pf_inst = _RANDOM[4'h6][18];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_ae_ld = _RANDOM[4'h6][22];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_ae_st = _RANDOM[4'h6][23];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_ae_inst = _RANDOM[4'h6][24];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_ma_ld = _RANDOM[4'h6][25];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_ma_st = _RANDOM[4'h6][26];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_cacheable = _RANDOM[4'h6][28];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s1_tlbResp_must_alloc = _RANDOM[4'h6][29];	// src/main/scala/rocket/GPCDCache.scala:69:29
        s2_valid_REG = _RANDOM[4'h6][31];	// src/main/scala/rocket/GPCDCache.scala:69:29, :98:25
        s2_tlbResp_miss = _RANDOM[4'h7][0];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_paddr = {_RANDOM[4'h7][31:1], _RANDOM[4'h8][0]};	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_gpa = {_RANDOM[4'h8][31:1], _RANDOM[4'h9][8:0]};	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_gpa_is_pte = _RANDOM[4'h9][9];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_pf_ld = _RANDOM[4'h9][10];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_pf_st = _RANDOM[4'h9][11];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_pf_inst = _RANDOM[4'h9][12];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_gf_ld = _RANDOM[4'h9][13];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_gf_st = _RANDOM[4'h9][14];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_gf_inst = _RANDOM[4'h9][15];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_ae_ld = _RANDOM[4'h9][16];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_ae_st = _RANDOM[4'h9][17];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_ae_inst = _RANDOM[4'h9][18];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_ma_ld = _RANDOM[4'h9][19];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_ma_st = _RANDOM[4'h9][20];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_ma_inst = _RANDOM[4'h9][21];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_cacheable = _RANDOM[4'h9][22];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_must_alloc = _RANDOM[4'h9][23];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_tlbResp_prefetchable = _RANDOM[4'h9][24];	// src/main/scala/rocket/GPCDCache.scala:99:29
        s2_replayReq = _RANDOM[4'h9][25];	// src/main/scala/rocket/GPCDCache.scala:99:29, :102:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  GPCDCache dcacheClient (	// src/main/scala/rocket/GPCDCache.scala:17:32
    .clock                   (clock),
    .reset                   (reset),
    .auto_out_a_ready        (auto_dcacheClient_out_a_ready),
    .auto_out_b_valid        (auto_dcacheClient_out_b_valid),
    .auto_out_b_bits_opcode  (auto_dcacheClient_out_b_bits_opcode),
    .auto_out_b_bits_param   (auto_dcacheClient_out_b_bits_param),
    .auto_out_b_bits_size    (auto_dcacheClient_out_b_bits_size),
    .auto_out_b_bits_source  (auto_dcacheClient_out_b_bits_source),
    .auto_out_b_bits_address (auto_dcacheClient_out_b_bits_address),
    .auto_out_b_bits_mask    (auto_dcacheClient_out_b_bits_mask),
    .auto_out_b_bits_data    (auto_dcacheClient_out_b_bits_data),
    .auto_out_b_bits_corrupt (auto_dcacheClient_out_b_bits_corrupt),
    .auto_out_c_ready        (auto_dcacheClient_out_c_ready),
    .auto_out_d_valid        (auto_dcacheClient_out_d_valid),
    .auto_out_d_bits_opcode  (auto_dcacheClient_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_dcacheClient_out_d_bits_param),
    .auto_out_d_bits_size    (auto_dcacheClient_out_d_bits_size),
    .auto_out_d_bits_source  (auto_dcacheClient_out_d_bits_source),
    .auto_out_d_bits_sink    (auto_dcacheClient_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_dcacheClient_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_dcacheClient_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_dcacheClient_out_d_bits_corrupt),
    .auto_out_e_ready        (auto_dcacheClient_out_e_ready),
    .io_req_valid            (cacheReqValid),	// src/main/scala/rocket/GPCDCache.scala:76:50
    .io_req_bits_source      (cacheReq_source),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_paddr       (cacheReq_paddr),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_cmd         (cacheReq_cmd),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_size        (cacheReq_size),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_signed      (cacheReq_signed),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_wdata       (cacheReq_wdata),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_wmask       (cacheReq_wmask),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_noAlloc     (1'h0),	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
    .io_req_bits_dest        (cacheReq_dest),	// src/main/scala/rocket/GPCDCache.scala:79:26
    .io_req_bits_isRefill    (1'h0),	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
    .io_req_bits_refillCoh   (2'h0),	// src/main/scala/rocket/GPCDCache.scala:17:32, :79:26
    .io_s1_kill              (io_cpu_s2_kill),
    .auto_out_a_valid        (auto_dcacheClient_out_a_valid),
    .auto_out_a_bits_opcode  (auto_dcacheClient_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_dcacheClient_out_a_bits_param),
    .auto_out_a_bits_size    (auto_dcacheClient_out_a_bits_size),
    .auto_out_a_bits_source  (auto_dcacheClient_out_a_bits_source),
    .auto_out_a_bits_address (auto_dcacheClient_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_dcacheClient_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_dcacheClient_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_dcacheClient_out_a_bits_corrupt),
    .auto_out_b_ready        (auto_dcacheClient_out_b_ready),
    .auto_out_c_valid        (auto_dcacheClient_out_c_valid),
    .auto_out_c_bits_opcode  (auto_dcacheClient_out_c_bits_opcode),
    .auto_out_c_bits_param   (auto_dcacheClient_out_c_bits_param),
    .auto_out_c_bits_size    (auto_dcacheClient_out_c_bits_size),
    .auto_out_c_bits_source  (auto_dcacheClient_out_c_bits_source),
    .auto_out_c_bits_address (auto_dcacheClient_out_c_bits_address),
    .auto_out_c_bits_data    (auto_dcacheClient_out_c_bits_data),
    .auto_out_c_bits_corrupt (auto_dcacheClient_out_c_bits_corrupt),
    .auto_out_d_ready        (auto_dcacheClient_out_d_ready),
    .auto_out_e_valid        (auto_dcacheClient_out_e_valid),
    .auto_out_e_bits_sink    (auto_dcacheClient_out_e_bits_sink),
    .io_req_ready            (_dcacheClient_io_req_ready),
    .io_resp_valid           (_dcacheClient_io_resp_valid),
    .io_resp_bits_source     (_dcacheClient_io_resp_bits_source),
    .io_resp_bits_dest       (_dcacheClient_io_resp_bits_dest),
    .io_resp_bits_status     (_dcacheClient_io_resp_bits_status),
    .io_resp_bits_hasData    (io_cpu_resp_bits_has_data),
    .io_resp_bits_data       (_dcacheClient_io_resp_bits_data),
    .io_nextCycleWb          (io_cpu_replay_next),
    .io_fenceRdy             (io_cpu_ordered)
  );
  TLB dtlb (	// src/main/scala/rocket/GPCDCache.scala:46:20
    .clock                                 (clock),
    .reset                                 (reset),
    .io_req_valid                          (s0_valid & s0_readwrite),	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/GPCDCache.scala:34:42, :50:33
    .io_req_bits_vaddr                     (s0_tlbReq_vaddr),	// src/main/scala/rocket/GPCDCache.scala:36:27
    .io_req_bits_passthrough               (s0_tlbReq_passthrough),	// src/main/scala/rocket/GPCDCache.scala:36:27
    .io_req_bits_size                      (s0_tlbReq_size),	// src/main/scala/rocket/GPCDCache.scala:36:27
    .io_req_bits_cmd                       (s0_tlbReq_cmd),	// src/main/scala/rocket/GPCDCache.scala:36:27
    .io_req_bits_prv                       (s0_tlbReq_prv),	// src/main/scala/rocket/GPCDCache.scala:36:27
    .io_sfence_valid                       (s0_valid & io_cpu_req_bits_cmd == 5'h14),	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/rocket/GPCDCache.scala:53:{36,51}
    .io_sfence_bits_rs1                    (io_cpu_req_bits_size[0]),	// src/main/scala/rocket/GPCDCache.scala:54:41
    .io_sfence_bits_rs2                    (io_cpu_req_bits_size[1]),	// src/main/scala/rocket/GPCDCache.scala:55:41
    .io_sfence_bits_addr                   (io_cpu_req_bits_addr[38:0]),	// src/main/scala/rocket/GPCDCache.scala:56:28
    .io_ptw_req_ready                      (io_ptw_req_ready),
    .io_ptw_resp_valid                     (io_ptw_resp_valid),
    .io_ptw_resp_bits_ae_ptw               (io_ptw_resp_bits_ae_ptw),
    .io_ptw_resp_bits_ae_final             (io_ptw_resp_bits_ae_final),
    .io_ptw_resp_bits_pf                   (io_ptw_resp_bits_pf),
    .io_ptw_resp_bits_gf                   (io_ptw_resp_bits_gf),
    .io_ptw_resp_bits_hr                   (io_ptw_resp_bits_hr),
    .io_ptw_resp_bits_hw                   (io_ptw_resp_bits_hw),
    .io_ptw_resp_bits_hx                   (io_ptw_resp_bits_hx),
    .io_ptw_resp_bits_pte_ppn              (io_ptw_resp_bits_pte_ppn),
    .io_ptw_resp_bits_pte_d                (io_ptw_resp_bits_pte_d),
    .io_ptw_resp_bits_pte_a                (io_ptw_resp_bits_pte_a),
    .io_ptw_resp_bits_pte_g                (io_ptw_resp_bits_pte_g),
    .io_ptw_resp_bits_pte_u                (io_ptw_resp_bits_pte_u),
    .io_ptw_resp_bits_pte_x                (io_ptw_resp_bits_pte_x),
    .io_ptw_resp_bits_pte_w                (io_ptw_resp_bits_pte_w),
    .io_ptw_resp_bits_pte_r                (io_ptw_resp_bits_pte_r),
    .io_ptw_resp_bits_pte_v                (io_ptw_resp_bits_pte_v),
    .io_ptw_resp_bits_level                (io_ptw_resp_bits_level),
    .io_ptw_resp_bits_fragmented_superpage (io_ptw_resp_bits_fragmented_superpage),
    .io_ptw_resp_bits_homogeneous          (io_ptw_resp_bits_homogeneous),
    .io_ptw_resp_bits_gpa_valid            (io_ptw_resp_bits_gpa_valid),
    .io_ptw_resp_bits_gpa_bits             (io_ptw_resp_bits_gpa_bits),
    .io_ptw_resp_bits_gpa_is_pte           (io_ptw_resp_bits_gpa_is_pte),
    .io_ptw_ptbr_mode                      (io_ptw_ptbr_mode),
    .io_ptw_ptbr_asid                      (io_ptw_ptbr_asid),
    .io_ptw_ptbr_ppn                       (io_ptw_ptbr_ppn),
    .io_ptw_status_debug                   (io_ptw_status_debug),
    .io_ptw_status_mxr                     (io_ptw_status_mxr),
    .io_ptw_status_sum                     (io_ptw_status_sum),
    .io_ptw_pmp_0_cfg_l                    (io_ptw_pmp_0_cfg_l),
    .io_ptw_pmp_0_cfg_res                  (io_ptw_pmp_0_cfg_res),
    .io_ptw_pmp_0_cfg_a                    (io_ptw_pmp_0_cfg_a),
    .io_ptw_pmp_0_cfg_x                    (io_ptw_pmp_0_cfg_x),
    .io_ptw_pmp_0_cfg_w                    (io_ptw_pmp_0_cfg_w),
    .io_ptw_pmp_0_cfg_r                    (io_ptw_pmp_0_cfg_r),
    .io_ptw_pmp_0_addr                     (io_ptw_pmp_0_addr),
    .io_ptw_pmp_0_mask                     (io_ptw_pmp_0_mask),
    .io_ptw_pmp_1_cfg_l                    (io_ptw_pmp_1_cfg_l),
    .io_ptw_pmp_1_cfg_res                  (io_ptw_pmp_1_cfg_res),
    .io_ptw_pmp_1_cfg_a                    (io_ptw_pmp_1_cfg_a),
    .io_ptw_pmp_1_cfg_x                    (io_ptw_pmp_1_cfg_x),
    .io_ptw_pmp_1_cfg_w                    (io_ptw_pmp_1_cfg_w),
    .io_ptw_pmp_1_cfg_r                    (io_ptw_pmp_1_cfg_r),
    .io_ptw_pmp_1_addr                     (io_ptw_pmp_1_addr),
    .io_ptw_pmp_1_mask                     (io_ptw_pmp_1_mask),
    .io_ptw_pmp_2_cfg_l                    (io_ptw_pmp_2_cfg_l),
    .io_ptw_pmp_2_cfg_res                  (io_ptw_pmp_2_cfg_res),
    .io_ptw_pmp_2_cfg_a                    (io_ptw_pmp_2_cfg_a),
    .io_ptw_pmp_2_cfg_x                    (io_ptw_pmp_2_cfg_x),
    .io_ptw_pmp_2_cfg_w                    (io_ptw_pmp_2_cfg_w),
    .io_ptw_pmp_2_cfg_r                    (io_ptw_pmp_2_cfg_r),
    .io_ptw_pmp_2_addr                     (io_ptw_pmp_2_addr),
    .io_ptw_pmp_2_mask                     (io_ptw_pmp_2_mask),
    .io_ptw_pmp_3_cfg_l                    (io_ptw_pmp_3_cfg_l),
    .io_ptw_pmp_3_cfg_res                  (io_ptw_pmp_3_cfg_res),
    .io_ptw_pmp_3_cfg_a                    (io_ptw_pmp_3_cfg_a),
    .io_ptw_pmp_3_cfg_x                    (io_ptw_pmp_3_cfg_x),
    .io_ptw_pmp_3_cfg_w                    (io_ptw_pmp_3_cfg_w),
    .io_ptw_pmp_3_cfg_r                    (io_ptw_pmp_3_cfg_r),
    .io_ptw_pmp_3_addr                     (io_ptw_pmp_3_addr),
    .io_ptw_pmp_3_mask                     (io_ptw_pmp_3_mask),
    .io_ptw_pmp_4_cfg_l                    (io_ptw_pmp_4_cfg_l),
    .io_ptw_pmp_4_cfg_res                  (io_ptw_pmp_4_cfg_res),
    .io_ptw_pmp_4_cfg_a                    (io_ptw_pmp_4_cfg_a),
    .io_ptw_pmp_4_cfg_x                    (io_ptw_pmp_4_cfg_x),
    .io_ptw_pmp_4_cfg_w                    (io_ptw_pmp_4_cfg_w),
    .io_ptw_pmp_4_cfg_r                    (io_ptw_pmp_4_cfg_r),
    .io_ptw_pmp_4_addr                     (io_ptw_pmp_4_addr),
    .io_ptw_pmp_4_mask                     (io_ptw_pmp_4_mask),
    .io_ptw_pmp_5_cfg_l                    (io_ptw_pmp_5_cfg_l),
    .io_ptw_pmp_5_cfg_res                  (io_ptw_pmp_5_cfg_res),
    .io_ptw_pmp_5_cfg_a                    (io_ptw_pmp_5_cfg_a),
    .io_ptw_pmp_5_cfg_x                    (io_ptw_pmp_5_cfg_x),
    .io_ptw_pmp_5_cfg_w                    (io_ptw_pmp_5_cfg_w),
    .io_ptw_pmp_5_cfg_r                    (io_ptw_pmp_5_cfg_r),
    .io_ptw_pmp_5_addr                     (io_ptw_pmp_5_addr),
    .io_ptw_pmp_5_mask                     (io_ptw_pmp_5_mask),
    .io_ptw_pmp_6_cfg_l                    (io_ptw_pmp_6_cfg_l),
    .io_ptw_pmp_6_cfg_res                  (io_ptw_pmp_6_cfg_res),
    .io_ptw_pmp_6_cfg_a                    (io_ptw_pmp_6_cfg_a),
    .io_ptw_pmp_6_cfg_x                    (io_ptw_pmp_6_cfg_x),
    .io_ptw_pmp_6_cfg_w                    (io_ptw_pmp_6_cfg_w),
    .io_ptw_pmp_6_cfg_r                    (io_ptw_pmp_6_cfg_r),
    .io_ptw_pmp_6_addr                     (io_ptw_pmp_6_addr),
    .io_ptw_pmp_6_mask                     (io_ptw_pmp_6_mask),
    .io_ptw_pmp_7_cfg_l                    (io_ptw_pmp_7_cfg_l),
    .io_ptw_pmp_7_cfg_res                  (io_ptw_pmp_7_cfg_res),
    .io_ptw_pmp_7_cfg_a                    (io_ptw_pmp_7_cfg_a),
    .io_ptw_pmp_7_cfg_x                    (io_ptw_pmp_7_cfg_x),
    .io_ptw_pmp_7_cfg_w                    (io_ptw_pmp_7_cfg_w),
    .io_ptw_pmp_7_cfg_r                    (io_ptw_pmp_7_cfg_r),
    .io_ptw_pmp_7_addr                     (io_ptw_pmp_7_addr),
    .io_ptw_pmp_7_mask                     (io_ptw_pmp_7_mask),
    .io_req_ready                          (_dtlb_io_req_ready),
    .io_resp_miss                          (_dtlb_io_resp_miss),
    .io_resp_paddr                         (_dtlb_io_resp_paddr),
    .io_resp_gpa                           (_dtlb_io_resp_gpa),
    .io_resp_pf_ld                         (_dtlb_io_resp_pf_ld),
    .io_resp_pf_st                         (_dtlb_io_resp_pf_st),
    .io_resp_pf_inst                       (_dtlb_io_resp_pf_inst),
    .io_resp_ae_ld                         (_dtlb_io_resp_ae_ld),
    .io_resp_ae_st                         (_dtlb_io_resp_ae_st),
    .io_resp_ae_inst                       (_dtlb_io_resp_ae_inst),
    .io_resp_ma_ld                         (_dtlb_io_resp_ma_ld),
    .io_resp_ma_st                         (_dtlb_io_resp_ma_st),
    .io_resp_cacheable                     (_dtlb_io_resp_cacheable),
    .io_resp_must_alloc                    (_dtlb_io_resp_must_alloc),
    .io_ptw_req_valid                      (io_ptw_req_valid),
    .io_ptw_req_bits_bits_addr             (io_ptw_req_bits_bits_addr),
    .io_ptw_req_bits_bits_need_gpa         (io_ptw_req_bits_bits_need_gpa)
  );
  assign io_cpu_req_ready = _io_cpu_req_ready_output;
  assign io_cpu_s2_nack =
    s2_valid & s2_tlbResp_miss | _dcacheClient_io_resp_valid
    & _dcacheClient_io_resp_bits_status == 2'h2 | s2_replayReq;	// src/main/scala/rocket/Consts.scala:84:35, src/main/scala/rocket/GPCDCache.scala:17:32, :98:36, :99:29, :102:29, :107:31, :108:{25,48,77}
  assign io_cpu_s2_nack_cause_raw = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_s2_uncached = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_s2_paddr = 32'h0;	// src/main/scala/rocket/GPCDCache.scala:106:13
  assign io_cpu_resp_valid =
    _dcacheClient_io_resp_valid & _dcacheClient_io_resp_bits_status != 2'h1
    & _dcacheClient_io_resp_bits_status != 2'h2;	// src/main/scala/rocket/Consts.scala:84:35, src/main/scala/rocket/GPCDCache.scala:17:32, :117:{42,66,114}
  assign io_cpu_resp_bits_addr = 40'h0;	// src/main/scala/rocket/GPCDCache.scala:36:40
  assign io_cpu_resp_bits_tag =
    {_dcacheClient_io_resp_bits_dest, _dcacheClient_io_resp_bits_source};	// src/main/scala/rocket/GPCDCache.scala:17:32, :123:30
  assign io_cpu_resp_bits_cmd = 5'h0;	// src/main/scala/rocket/GPCDCache.scala:36:40
  assign io_cpu_resp_bits_size = 2'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :79:26
  assign io_cpu_resp_bits_signed = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_resp_bits_dprv = 2'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :79:26
  assign io_cpu_resp_bits_dv = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_resp_bits_data = _dcacheClient_io_resp_bits_data[63:0];	// src/main/scala/rocket/GPCDCache.scala:17:32, :119:25
  assign io_cpu_resp_bits_mask = 8'h0;	// src/main/scala/rocket/GPCDCache.scala:116:20
  assign io_cpu_resp_bits_replay = &_dcacheClient_io_resp_bits_status;	// src/main/scala/rocket/GPCDCache.scala:17:32, :121:51
  assign io_cpu_resp_bits_data_word_bypass = _dcacheClient_io_resp_bits_data[63:0];	// src/main/scala/rocket/GPCDCache.scala:17:32, :119:25
  assign io_cpu_resp_bits_data_raw = 64'h0;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_cpu_resp_bits_store_data = 64'h0;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_cpu_s2_xcpt_ma_ld = s2_valid & s2_tlbResp_ma_ld;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_ma_st = s2_valid & s2_tlbResp_ma_st;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_pf_ld = s2_valid & s2_tlbResp_pf_ld;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_pf_st = s2_valid & s2_tlbResp_pf_st;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_gf_ld = s2_valid & s2_tlbResp_gf_ld;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_gf_st = s2_valid & s2_tlbResp_gf_st;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_ae_ld = s2_valid & s2_tlbResp_ae_ld;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_xcpt_ae_st = s2_valid & s2_tlbResp_ae_st;	// src/main/scala/rocket/GPCDCache.scala:98:36, :99:29, :130:18, :131:20, :133:20
  assign io_cpu_s2_gpa = s2_tlbResp_gpa;	// src/main/scala/rocket/GPCDCache.scala:99:29
  assign io_cpu_s2_gpa_is_pte = s2_tlbResp_gpa_is_pte;	// src/main/scala/rocket/GPCDCache.scala:99:29
  assign io_cpu_perf_acquire = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_release = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_grant = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_tlbMiss = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_blocked = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_canAcceptStoreThenLoad = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_canAcceptStoreThenRMW = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_canAcceptLoadThenLoad = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_storeBufferEmptyAfterLoad = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_perf_storeBufferEmptyAfterStore = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_cpu_clock_enabled = 1'h1;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_ptw_req_bits_valid = 1'h1;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_ptw_req_bits_bits_vstage1 = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_req_bits_bits_stage2 = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_0_stall = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_0_set = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_0_sdata = 64'h0;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_ptw_customCSRs_csrs_1_stall = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_1_set = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_1_sdata = 64'h0;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_ptw_customCSRs_csrs_2_stall = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_2_set = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_2_sdata = 64'h0;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_ptw_customCSRs_csrs_3_stall = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_3_set = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_ptw_customCSRs_csrs_3_sdata = 64'h0;	// src/main/scala/rocket/GPCDCache.scala:46:20
  assign io_errors_bus_valid = 1'h0;	// src/main/scala/rocket/GPCDCache.scala:17:32, :46:20, :79:26
  assign io_errors_bus_bits = 32'h0;	// src/main/scala/rocket/GPCDCache.scala:106:13
endmodule

