// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module MSHRWrapper(
  input          clock,
                 reset,
                 io_req_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [4:0]   io_req_bits_source,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [38:0]  io_req_bits_paddr,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [4:0]   io_req_bits_cmd,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [2:0]   io_req_bits_size,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input          io_req_bits_signed,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [511:0] io_req_bits_wdata,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [63:0]  io_req_bits_wmask,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input          io_req_bits_isMMIO,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_req_bits_noAlloc,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [4:0]   io_req_bits_dest,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input          io_req_bits_isFromCore,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_req_bits_isProbe,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_req_bits_isRefill,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [1:0]   io_req_bits_probePerm,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_req_bits_refillCoh,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input          io_cacheable,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_isUpgrade,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_l2Req_ready,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_fromRefill_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [4:0]   io_fromRefill_bits_entryId,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [1:0]   io_fromRefill_bits_perm,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [511:0] io_fromRefill_bits_data,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input          io_fromRefill_bits_hasData,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_fromRefill_bits_probeMatch,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_probeCheck_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [1:0]   io_probeCheck_probePermission,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [32:0]  io_probeCheck_lineAddr,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input          io_toReplace_ready,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  input  [1:0]   io_replaceStatus,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_req_ready,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_l2Req_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [2:0]   io_l2Req_bits_opcode,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_l2Req_bits_param,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [3:0]   io_l2Req_bits_size,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [4:0]   io_l2Req_bits_source,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [31:0]  io_l2Req_bits_address,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [7:0]   io_l2Req_bits_mask,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [63:0]  io_l2Req_bits_data,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_l2Req_bits_corrupt,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_fromRefill_ready,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_nextCycleWb,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_resp_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [1:0]   io_resp_bits_source,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [4:0]   io_resp_bits_dest,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [1:0]   io_resp_bits_status,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_resp_bits_hasData,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [511:0] io_resp_bits_data,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_probeCheck_pass,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_probeCheck_hit,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [1:0]   io_probeCheck_probeCoh,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_probeCheck_replaceFinish,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
                 io_probeRefill_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [2:0]   io_probeRefill_bits_entryId,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_toReplace_valid,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [1:0]   io_toReplace_bits_state,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [32:0]  io_toReplace_bits_lineAddr,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output [511:0] io_toReplace_bits_data,	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
  output         io_fenceRdy	// src/main/scala/gpcdcache/MSHRWrapper.scala:12:14
);

  wire         _iomshrs_io_req_ready;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _iomshrs_io_addrMatch;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _iomshrs_io_fenceRdy;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _iomshrs_io_nextCycleWb;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _iomshrs_io_resp_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [1:0]   _iomshrs_io_resp_bits_source;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [4:0]   _iomshrs_io_resp_bits_dest;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [511:0] _iomshrs_io_resp_bits_data;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _iomshrs_io_l2Req_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [2:0]   _iomshrs_io_l2Req_bits_opcode;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [2:0]   _iomshrs_io_l2Req_bits_param;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [3:0]   _iomshrs_io_l2Req_bits_size;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [4:0]   _iomshrs_io_l2Req_bits_source;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [31:0]  _iomshrs_io_l2Req_bits_address;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [7:0]   _iomshrs_io_l2Req_bits_mask;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire [63:0]  _iomshrs_io_l2Req_bits_data;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _iomshrs_io_fromRefill_ready;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
  wire         _mshrs_io_pipelineReq_ready;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         _mshrs_io_addrMatch;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         _mshrs_io_fenceRdy;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         _mshrs_io_toL2Req_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire [1:0]   _mshrs_io_toL2Req_bits_perm;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire [32:0]  _mshrs_io_toL2Req_bits_lineAddr;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         _mshrs_io_fromRefill_ready;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         _mshrs_io_toPipeline_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         _mshrs_io_toPipeline_bits_nextCycleWb;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
  wire         acquire_a_mask_size = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_1 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_2 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_3 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_4 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_5 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_size_2 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_6 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_7 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_8 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_9 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_10 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_11 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_12 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire         acquire_a_mask_acc_13 = 1'h1;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, src/main/scala/util/Misc.scala:209:26, :215:29
  wire [1:0]   acquire_a_mask_lo_lo = 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  wire [1:0]   acquire_a_mask_lo_hi = 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  wire [1:0]   acquire_a_mask_hi_lo = 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  wire [1:0]   acquire_a_mask_hi_hi = 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  wire [1:0]   mshrsResp_status = 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  wire         acquire_corrupt = 1'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:209:26
  wire         acquire_a_mask_bit = 1'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:209:26, :210:26
  wire         acquire_a_mask_size_1 = 1'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:209:26
  wire         acquire_a_mask_bit_1 = 1'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:209:26, :210:26
  wire         acquire_a_mask_bit_2 = 1'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:209:26, :210:26
  wire [1:0]   acquire_a_mask_sizeOH_shiftAmount = 2'h2;	// src/main/scala/chisel3/util/OneHot.scala:64:49
  wire [2:0]   acquire_opcode = 3'h6;	// src/main/scala/tilelink/Edges.scala:347:17
  wire [3:0]   acquire_size = 4'h6;	// src/main/scala/tilelink/Edges.scala:347:17
  wire [63:0]  acquire_data = 64'h0;	// src/main/scala/tilelink/Edges.scala:347:17
  wire [2:0]   acquire_a_mask_sizeOH = 3'h5;	// src/main/scala/util/Misc.scala:202:81
  wire [3:0]   acquire_a_mask_lo = 4'hF;	// src/main/scala/util/Misc.scala:222:10
  wire [3:0]   acquire_a_mask_hi = 4'hF;	// src/main/scala/util/Misc.scala:222:10
  wire [7:0]   acquire_mask = 8'hFF;	// src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:222:10
  wire         amoReq =
    io_req_bits_cmd == 5'h4 | io_req_bits_cmd == 5'h9 | io_req_bits_cmd == 5'hA
    | io_req_bits_cmd == 5'hB | io_req_bits_cmd == 5'h8 | io_req_bits_cmd == 5'hC
    | io_req_bits_cmd == 5'hD | io_req_bits_cmd == 5'hE | io_req_bits_cmd == 5'hF;	// src/main/scala/gpcdcache/MemConstants.scala:42:52, src/main/scala/util/package.scala:16:47
  wire         validIOMSHRReq =
    (~io_cacheable | amoReq | io_req_bits_noAlloc) & ~_mshrs_io_addrMatch;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :36:{25,49,73,76}, src/main/scala/gpcdcache/MemConstants.scala:42:52
  wire         validMSHRReq =
    ~(amoReq | ~io_cacheable | _iomshrs_io_addrMatch)
    & (~io_req_bits_noAlloc | _mshrs_io_addrMatch);	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :36:25, :37:25, :38:29, :40:8, src/main/scala/gpcdcache/MemConstants.scala:42:52
  wire [31:0]  acquire_address = {_mshrs_io_toL2Req_bits_lineAddr[25:0], 6'h0};	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :48:43, src/main/scala/tilelink/Edges.scala:347:17
  wire         acquire_legal = _mshrs_io_toL2Req_bits_lineAddr[25];	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, src/main/scala/tilelink/Parameters.scala:673:26
  wire [2:0]   acquire_param = {1'h0, _mshrs_io_toL2Req_bits_perm};	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, :349:15, src/main/scala/util/Misc.scala:209:26
  wire         acquire_a_mask_eq_1 = acquire_a_mask_bit;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire         acquire_a_mask_nbit = ~acquire_a_mask_bit;	// src/main/scala/util/Misc.scala:210:26, :211:20
  wire         acquire_a_mask_eq = acquire_a_mask_nbit;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_nbit_1 = ~acquire_a_mask_bit_1;	// src/main/scala/util/Misc.scala:210:26, :211:20
  wire         acquire_a_mask_eq_2 = acquire_a_mask_eq & acquire_a_mask_nbit_1;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_eq_3 = acquire_a_mask_eq & acquire_a_mask_bit_1;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire         acquire_a_mask_eq_4 = acquire_a_mask_eq_1 & acquire_a_mask_nbit_1;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_eq_5 = acquire_a_mask_eq_1 & acquire_a_mask_bit_1;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire         acquire_a_mask_nbit_2 = ~acquire_a_mask_bit_2;	// src/main/scala/util/Misc.scala:210:26, :211:20
  wire         acquire_a_mask_eq_6 = acquire_a_mask_eq_2 & acquire_a_mask_nbit_2;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_eq_7 = acquire_a_mask_eq_2 & acquire_a_mask_bit_2;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire         acquire_a_mask_eq_8 = acquire_a_mask_eq_3 & acquire_a_mask_nbit_2;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_eq_9 = acquire_a_mask_eq_3 & acquire_a_mask_bit_2;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire         acquire_a_mask_eq_10 = acquire_a_mask_eq_4 & acquire_a_mask_nbit_2;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_eq_11 = acquire_a_mask_eq_4 & acquire_a_mask_bit_2;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire         acquire_a_mask_eq_12 = acquire_a_mask_eq_5 & acquire_a_mask_nbit_2;	// src/main/scala/util/Misc.scala:211:20, :214:27
  wire         acquire_a_mask_eq_13 = acquire_a_mask_eq_5 & acquire_a_mask_bit_2;	// src/main/scala/util/Misc.scala:210:26, :214:27
  wire [4:0]   acquire_source;	// src/main/scala/tilelink/Edges.scala:347:17
  wire         refillMSHR = io_fromRefill_bits_entryId < 5'h8;	// src/main/scala/gpcdcache/MSHRWrapper.scala:79:47, src/main/scala/util/package.scala:16:47
  wire         refillIOMSHR =
    io_fromRefill_bits_entryId[4] & io_fromRefill_bits_entryId[4:3] != 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :80:{49,82}, :81:32, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  wire [1:0]   mshrsResp_source;	// src/main/scala/gpcdcache/MSHRWrapper.scala:98:23
  wire [4:0]   mshrsResp_dest;	// src/main/scala/gpcdcache/MSHRWrapper.scala:98:23
  wire         mshrsResp_hasData;	// src/main/scala/gpcdcache/MSHRWrapper.scala:98:23
  wire [511:0] mshrsResp_data;	// src/main/scala/gpcdcache/MSHRWrapper.scala:98:23
  MSHRFile mshrs (	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23
    .clock                             (clock),
    .reset                             (reset),
    .io_pipelineReq_valid              (io_req_valid & validMSHRReq),	// src/main/scala/gpcdcache/MSHRWrapper.scala:37:25, :44:59
    .io_pipelineReq_bits_isUpgrade     (io_isUpgrade),
    .io_pipelineReq_bits_lineAddr      ({6'h0, io_req_bits_paddr[32:6]}),	// src/main/scala/gpcdcache/MSHRWrapper.scala:48:43, src/main/scala/gpcdcache/Utils.scala:19:9
    .io_pipelineReq_bits_meta_sourceId (io_req_bits_source[1:0]),	// src/main/scala/gpcdcache/MSHRWrapper.scala:49:43
    .io_pipelineReq_bits_meta_regIdx   (io_req_bits_dest),
    .io_pipelineReq_bits_meta_size     (io_req_bits_size),
    .io_pipelineReq_bits_meta_signed   (io_req_bits_signed),
    .io_pipelineReq_bits_meta_offset   (io_req_bits_paddr[5:0]),	// src/main/scala/gpcdcache/Utils.scala:22:9
    .io_pipelineReq_bits_meta_cmd      (io_req_bits_cmd),
    .io_pipelineReq_bits_mask          (io_req_bits_wmask),
    .io_pipelineReq_bits_data          (io_req_bits_wdata),
    .io_toL2Req_ready                  (io_l2Req_ready & ~_iomshrs_io_l2Req_valid),	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :74:{44,47}
    .io_fromRefill_valid               (io_fromRefill_valid & refillMSHR),	// src/main/scala/gpcdcache/MSHRWrapper.scala:79:47, :85:52
    .io_fromRefill_bits_entryId        (io_fromRefill_bits_entryId),
    .io_fromRefill_bits_perm           (io_fromRefill_bits_perm),
    .io_fromRefill_bits_data           (io_fromRefill_bits_data),
    .io_fromRefill_bits_hasData        (io_fromRefill_bits_hasData),
    .io_fromRefill_bits_probeMatch     (io_fromRefill_bits_probeMatch),
    .io_probeCheck_valid               (io_probeCheck_valid),
    .io_probeCheck_probePermission     (io_probeCheck_probePermission),
    .io_probeCheck_lineAddr            (io_probeCheck_lineAddr),
    .io_toReplace_ready                (io_toReplace_ready),
    .io_replaceStatus                  (io_replaceStatus),
    .io_pipelineReq_ready              (_mshrs_io_pipelineReq_ready),
    .io_addrMatch                      (_mshrs_io_addrMatch),
    .io_fenceRdy                       (_mshrs_io_fenceRdy),
    .io_toL2Req_valid                  (_mshrs_io_toL2Req_valid),
    .io_toL2Req_bits_perm              (_mshrs_io_toL2Req_bits_perm),
    .io_toL2Req_bits_entryId           (acquire_source),
    .io_toL2Req_bits_lineAddr          (_mshrs_io_toL2Req_bits_lineAddr),
    .io_fromRefill_ready               (_mshrs_io_fromRefill_ready),
    .io_probeCheck_pass                (io_probeCheck_pass),
    .io_probeCheck_hit                 (io_probeCheck_hit),
    .io_probeCheck_probeCoh            (io_probeCheck_probeCoh),
    .io_probeCheck_replaceFinish       (io_probeCheck_replaceFinish),
    .io_probeRefill_valid              (io_probeRefill_valid),
    .io_probeRefill_bits_entryId       (io_probeRefill_bits_entryId),
    .io_toPipeline_valid               (_mshrs_io_toPipeline_valid),
    .io_toPipeline_bits_sourceId       (mshrsResp_source),
    .io_toPipeline_bits_regIdx         (mshrsResp_dest),
    .io_toPipeline_bits_regData        (mshrsResp_data),
    .io_toPipeline_bits_nextCycleWb    (_mshrs_io_toPipeline_bits_nextCycleWb),
    .io_toReplace_valid                (io_toReplace_valid),
    .io_toReplace_bits_state           (io_toReplace_bits_state),
    .io_toReplace_bits_lineAddr        (io_toReplace_bits_lineAddr),
    .io_toReplace_bits_data            (io_toReplace_bits_data)
  );
  assign mshrsResp_hasData = _mshrs_io_toPipeline_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :98:23
  IOMSHRFile iomshrs (	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23
    .clock                      (clock),
    .reset                      (reset),
    .io_req_valid               (io_req_valid & validIOMSHRReq),	// src/main/scala/gpcdcache/MSHRWrapper.scala:36:73, :56:40
    .io_req_bits_source         (io_req_bits_source),
    .io_req_bits_paddr          (io_req_bits_paddr),
    .io_req_bits_cmd            (io_req_bits_cmd),
    .io_req_bits_size           (io_req_bits_size),
    .io_req_bits_signed         (io_req_bits_signed),
    .io_req_bits_wdata          (io_req_bits_wdata),
    .io_req_bits_wmask          (io_req_bits_wmask),
    .io_req_bits_isMMIO         (io_req_bits_isMMIO),
    .io_req_bits_noAlloc        (io_req_bits_noAlloc),
    .io_req_bits_dest           (io_req_bits_dest),
    .io_req_bits_isFromCore     (io_req_bits_isFromCore),
    .io_req_bits_isProbe        (io_req_bits_isProbe),
    .io_req_bits_isRefill       (io_req_bits_isRefill),
    .io_req_bits_probePerm      (io_req_bits_probePerm),
    .io_req_bits_refillCoh      (io_req_bits_refillCoh),
    .io_resp_ready              (~_mshrs_io_toPipeline_valid),	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :108:28
    .io_l2Req_ready             (io_l2Req_ready),
    .io_fromRefill_valid        (io_fromRefill_valid & refillIOMSHR),	// src/main/scala/gpcdcache/MSHRWrapper.scala:80:82, :88:54
    .io_fromRefill_bits_entryId (io_fromRefill_bits_entryId),
    .io_fromRefill_bits_data    (io_fromRefill_bits_data),
    .io_fromRefill_bits_hasData (io_fromRefill_bits_hasData),
    .io_req_ready               (_iomshrs_io_req_ready),
    .io_addrMatch               (_iomshrs_io_addrMatch),
    .io_fenceRdy                (_iomshrs_io_fenceRdy),
    .io_nextCycleWb             (_iomshrs_io_nextCycleWb),
    .io_resp_valid              (_iomshrs_io_resp_valid),
    .io_resp_bits_source        (_iomshrs_io_resp_bits_source),
    .io_resp_bits_dest          (_iomshrs_io_resp_bits_dest),
    .io_resp_bits_data          (_iomshrs_io_resp_bits_data),
    .io_l2Req_valid             (_iomshrs_io_l2Req_valid),
    .io_l2Req_bits_opcode       (_iomshrs_io_l2Req_bits_opcode),
    .io_l2Req_bits_param        (_iomshrs_io_l2Req_bits_param),
    .io_l2Req_bits_size         (_iomshrs_io_l2Req_bits_size),
    .io_l2Req_bits_source       (_iomshrs_io_l2Req_bits_source),
    .io_l2Req_bits_address      (_iomshrs_io_l2Req_bits_address),
    .io_l2Req_bits_mask         (_iomshrs_io_l2Req_bits_mask),
    .io_l2Req_bits_data         (_iomshrs_io_l2Req_bits_data),
    .io_fromRefill_ready        (_iomshrs_io_fromRefill_ready)
  );
  assign io_req_ready =
    validIOMSHRReq ? _iomshrs_io_req_ready : validMSHRReq & _mshrs_io_pipelineReq_ready;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :36:73, :37:25, :59:22, :62:8
  assign io_l2Req_valid = _mshrs_io_toL2Req_valid | _iomshrs_io_l2Req_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :73:52
  assign io_l2Req_bits_opcode =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_opcode : 3'h6;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17
  assign io_l2Req_bits_param =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_param : acquire_param;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17
  assign io_l2Req_bits_size =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_size : 4'h6;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17
  assign io_l2Req_bits_source =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_source : acquire_source;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17
  assign io_l2Req_bits_address =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_address : acquire_address;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17
  assign io_l2Req_bits_mask =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_mask : 8'hFF;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:222:10
  assign io_l2Req_bits_data =
    _iomshrs_io_l2Req_valid ? _iomshrs_io_l2Req_bits_data : 64'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17
  assign io_l2Req_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :76:32, src/main/scala/tilelink/Edges.scala:347:17, src/main/scala/util/Misc.scala:209:26
  assign io_fromRefill_ready =
    refillMSHR ? _mshrs_io_fromRefill_ready : refillIOMSHR & _iomshrs_io_fromRefill_ready;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :79:47, :80:82, :91:29, :94:8
  assign io_nextCycleWb = _mshrs_io_toPipeline_bits_nextCycleWb | _iomshrs_io_nextCycleWb;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :105:65
  assign io_resp_valid = _mshrs_io_toPipeline_valid | _iomshrs_io_resp_valid;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :106:54
  assign io_resp_bits_source =
    _mshrs_io_toPipeline_valid ? mshrsResp_source : _iomshrs_io_resp_bits_source;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :98:23, :107:31
  assign io_resp_bits_dest =
    _mshrs_io_toPipeline_valid ? mshrsResp_dest : _iomshrs_io_resp_bits_dest;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :98:23, :107:31
  assign io_resp_bits_status = 2'h3;	// src/main/scala/gpcdcache/MSHRWrapper.scala:32:23, :98:23, :107:31, src/main/scala/util/Misc.scala:222:10
  assign io_resp_bits_hasData = ~_mshrs_io_toPipeline_valid | mshrsResp_hasData;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :98:23, :107:31
  assign io_resp_bits_data =
    _mshrs_io_toPipeline_valid ? mshrsResp_data : _iomshrs_io_resp_bits_data;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :98:23, :107:31
  assign io_fenceRdy = _mshrs_io_fenceRdy & _iomshrs_io_fenceRdy;	// src/main/scala/gpcdcache/MSHRWrapper.scala:31:23, :32:23, :116:36
endmodule

