// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module MSHR(
  input         clock,
                reset,
                io_reqValid,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  input  [1:0]  io_req,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  input  [4:0]  io_reqCmd,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  input  [32:0] io_allocLineAddr,	// src/main/scala/gpcdcache/MSHR.scala:10:14
                io_probeLineAddr,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  input         io_isUpgrade,	// src/main/scala/gpcdcache/MSHR.scala:10:14
                io_replayFinish,	// src/main/scala/gpcdcache/MSHR.scala:10:14
                io_senderResp,	// src/main/scala/gpcdcache/MSHR.scala:10:14
                io_probeValid,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  input  [1:0]  io_probePermission,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output        io_allocLineAddrMatch,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output [2:0]  io_writeCounter,	// src/main/scala/gpcdcache/MSHR.scala:10:14
                io_replayCounter,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output        io_isEmpty,	// src/main/scala/gpcdcache/MSHR.scala:10:14
                io_stallReq,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output [1:0]  io_senderPermission,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output [32:0] io_senderLineAddr,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output        io_probeLineAddrMatch,	// src/main/scala/gpcdcache/MSHR.scala:10:14
  output [1:0]  io_probeState	// src/main/scala/gpcdcache/MSHR.scala:10:14
);

  wire        _io_probeLineAddrMatch_output;	// src/main/scala/gpcdcache/MSHR.scala:56:14
  reg  [2:0]  state;	// src/main/scala/gpcdcache/MSHR.scala:13:100
  wire        replayReq = io_req == 2'h2 & io_reqValid;	// src/main/scala/gpcdcache/MSHR.scala:18:{28,51}
  wire        allocateReq = io_req == 2'h1 & io_reqValid;	// src/main/scala/gpcdcache/MSHR.scala:19:{28,50}
  reg  [1:0]  sentPermission;	// src/main/scala/gpcdcache/MSHR.scala:22:31
  reg  [32:0] lineAddrReg;	// src/main/scala/gpcdcache/MSHR.scala:23:33
  reg  [2:0]  metaCounter;	// src/main/scala/gpcdcache/MSHR.scala:25:28
  wire        allocLineAddrMatch = lineAddrReg == io_allocLineAddr & (|state);	// src/main/scala/gpcdcache/MSHR.scala:13:100, :23:33, :28:{40,61,70}
  wire        _sentPermission_T_29 = sentPermission == 2'h0;	// src/main/scala/gpcdcache/MSHR.scala:22:31, :33:62
  wire        _sentPermission_T_30 = io_reqCmd == 5'h1;	// src/main/scala/gpcdcache/MemConstants.scala:45:38
  wire        _sentPermission_T_31 = io_reqCmd == 5'h11;	// src/main/scala/gpcdcache/MemConstants.scala:45:55
  wire        _sentPermission_T_33 = io_reqCmd == 5'h7;	// src/main/scala/gpcdcache/MemConstants.scala:45:72
  wire        _sentPermission_T_35 = io_reqCmd == 5'h4;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_36 = io_reqCmd == 5'h9;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_37 = io_reqCmd == 5'hA;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_38 = io_reqCmd == 5'hB;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_42 = io_reqCmd == 5'h8;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_43 = io_reqCmd == 5'hC;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_44 = io_reqCmd == 5'hD;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_45 = io_reqCmd == 5'hE;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_46 = io_reqCmd == 5'hF;	// src/main/scala/util/package.scala:16:47
  wire        _sentPermission_T_53 = io_reqCmd == 5'h3;	// src/main/scala/gpcdcache/MemConstants.scala:46:54
  wire        _sentPermission_T_55 = io_reqCmd == 5'h6;	// src/main/scala/gpcdcache/MemConstants.scala:46:71
  wire        privErr =
    (|(state[2:1])) & _sentPermission_T_29
    & (_sentPermission_T_30 | _sentPermission_T_31 | _sentPermission_T_33
       | _sentPermission_T_35 | _sentPermission_T_36 | _sentPermission_T_37
       | _sentPermission_T_38 | _sentPermission_T_42 | _sentPermission_T_43
       | _sentPermission_T_44 | _sentPermission_T_45 | _sentPermission_T_46
       | _sentPermission_T_53 | _sentPermission_T_55);	// src/main/scala/gpcdcache/MSHR.scala:13:100, :33:{24,62,86}, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72}, :46:{54,64,71}, src/main/scala/util/package.scala:16:47
  reg         readAfterWriteFlag;	// src/main/scala/gpcdcache/MSHR.scala:35:35
  reg         trueWriteFlag;	// src/main/scala/gpcdcache/MSHR.scala:36:35
  wire        wrwErr =
    readAfterWriteFlag
    & (_sentPermission_T_30 | _sentPermission_T_31 | _sentPermission_T_33
       | _sentPermission_T_35 | _sentPermission_T_36 | _sentPermission_T_37
       | _sentPermission_T_38 | _sentPermission_T_42 | _sentPermission_T_43
       | _sentPermission_T_44 | _sentPermission_T_45 | _sentPermission_T_46);	// src/main/scala/gpcdcache/MSHR.scala:35:35, :37:47, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72,82}, src/main/scala/util/package.scala:16:47
  wire [1:0]  probeState =
    state > 3'h2
      ? 2'h3
      : io_probePermission == 2'h1
          ? (_sentPermission_T_29 ? 2'h1 : 2'h2)
          : io_probePermission == 2'h2 ? 2'h2 : 2'h1;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :33:{24,62}, :39:23, :40:11, :42:56, :45:33, src/main/scala/gpcdcache/MemConstants.scala:46:54
  wire        _io_probeState_T = io_probeValid & _io_probeLineAddrMatch_output;	// src/main/scala/gpcdcache/MSHR.scala:54:33, :56:14
  assign _io_probeLineAddrMatch_output =
    lineAddrReg == io_probeLineAddr & io_probeValid & (|state);	// src/main/scala/gpcdcache/MSHR.scala:13:100, :23:33, :28:70, :55:41, :56:14
  wire        _stallReq_T_6 = io_reqCmd == 5'h2;	// src/main/scala/util/package.scala:16:47
  wire        isFull = &metaCounter;	// src/main/scala/gpcdcache/MSHR.scala:25:28, :68:28
  wire        stallReq =
    allocLineAddrMatch & (state > 3'h2 | isFull | privErr | wrwErr)
    & ~(_stallReq_T_6 | _sentPermission_T_53);	// src/main/scala/gpcdcache/MSHR.scala:13:100, :28:61, :33:{24,86}, :37:47, :68:28, :72:{36,76,87,90}, src/main/scala/gpcdcache/MemConstants.scala:43:48, :46:54, src/main/scala/util/package.scala:16:47
  always @(posedge clock) begin
    if (reset) begin
      state <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:13:100
      sentPermission <= 2'h0;	// src/main/scala/gpcdcache/MSHR.scala:22:31
      lineAddrReg <= 33'h0;	// src/main/scala/gpcdcache/MSHR.scala:23:33
      metaCounter <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :25:28
      readAfterWriteFlag <= 1'h0;	// src/main/scala/gpcdcache/MSHR.scala:35:35
      trueWriteFlag <= 1'h0;	// src/main/scala/gpcdcache/MSHR.scala:36:35
    end
    else begin
      automatic logic _readAfterWriteFlag_T;	// src/main/scala/gpcdcache/MSHR.scala:62:14
      automatic logic _readAfterWriteFlag_T_2;	// src/main/scala/util/package.scala:16:47
      automatic logic _readAfterWriteFlag_T_3;	// src/main/scala/util/package.scala:16:47
      automatic logic _GEN;	// src/main/scala/gpcdcache/MSHR.scala:89:26
      automatic logic _GEN_0;	// src/main/scala/gpcdcache/MSHR.scala:93:35
      automatic logic _GEN_1;	// src/main/scala/gpcdcache/MemConstants.scala:42:52
      automatic logic _GEN_2;	// src/main/scala/gpcdcache/MSHR.scala:94:27
      _readAfterWriteFlag_T = state == 3'h4;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :62:14, src/main/scala/util/package.scala:16:47
      _readAfterWriteFlag_T_2 = io_reqCmd == 5'h0;	// src/main/scala/util/package.scala:16:47
      _readAfterWriteFlag_T_3 = io_reqCmd == 5'h10;	// src/main/scala/util/package.scala:16:47
      _GEN = allocateReq & ~stallReq;	// src/main/scala/gpcdcache/MSHR.scala:19:50, :72:87, :89:{26,29}
      _GEN_0 = allocLineAddrMatch & ~(_stallReq_T_6 | _sentPermission_T_53);	// src/main/scala/gpcdcache/MSHR.scala:28:61, :93:{35,38}, src/main/scala/gpcdcache/MemConstants.scala:43:48, :46:54, src/main/scala/util/package.scala:16:47
      _GEN_1 =
        _sentPermission_T_35 | _sentPermission_T_36 | _sentPermission_T_37
        | _sentPermission_T_38 | _sentPermission_T_42 | _sentPermission_T_43
        | _sentPermission_T_44 | _sentPermission_T_45 | _sentPermission_T_46;	// src/main/scala/gpcdcache/MemConstants.scala:42:52, src/main/scala/util/package.scala:16:47
      _GEN_2 =
        ~trueWriteFlag
        & (_sentPermission_T_30 | _sentPermission_T_31 | _sentPermission_T_33 | _GEN_1);	// src/main/scala/gpcdcache/MSHR.scala:36:35, :94:{12,27}, src/main/scala/gpcdcache/MemConstants.scala:42:52, :45:{38,55,72,82}
      if (state == 3'h4)	// src/main/scala/gpcdcache/MSHR.scala:13:100, :134:35, src/main/scala/util/package.scala:16:47
        state <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:13:100
      else if (state == 3'h3) begin	// src/main/scala/gpcdcache/MSHR.scala:13:100, :134:35, :138:30
        if (io_replayFinish)	// src/main/scala/gpcdcache/MSHR.scala:10:14
          state <= 3'h4;	// src/main/scala/gpcdcache/MSHR.scala:13:100, src/main/scala/util/package.scala:16:47
      end
      else if (state == 3'h2) begin	// src/main/scala/gpcdcache/MSHR.scala:13:100, :33:24, :134:35
        if (replayReq)	// src/main/scala/gpcdcache/MSHR.scala:18:51
          state <= 3'h3;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :138:30
      end
      else if (state == 3'h1) begin	// src/main/scala/gpcdcache/MSHR.scala:13:100, :134:35, :136:30
        if (io_senderResp)	// src/main/scala/gpcdcache/MSHR.scala:10:14
          state <= 3'h2;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :33:24
      end
      else if (~(|state) & allocateReq)	// src/main/scala/gpcdcache/MSHR.scala:13:100, :19:50, :23:78, :134:35, :136:30
        state <= 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :136:30
      if (_readAfterWriteFlag_T) begin	// src/main/scala/gpcdcache/MSHR.scala:62:14
        sentPermission <= 2'h0;	// src/main/scala/gpcdcache/MSHR.scala:22:31
        metaCounter <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:13:100, :25:28
      end
      else if (_GEN) begin	// src/main/scala/gpcdcache/MSHR.scala:89:26
        if (|state) begin	// src/main/scala/gpcdcache/MSHR.scala:13:100, :23:78
          if (_GEN_0 & _sentPermission_T_29
              & (_sentPermission_T_30 | _sentPermission_T_31 | _sentPermission_T_33
                 | _sentPermission_T_35 | _sentPermission_T_36 | _sentPermission_T_37
                 | _sentPermission_T_38 | _sentPermission_T_42 | _sentPermission_T_43
                 | _sentPermission_T_44 | _sentPermission_T_45 | _sentPermission_T_46
                 | _sentPermission_T_53 | _sentPermission_T_55))	// src/main/scala/gpcdcache/MSHR.scala:22:31, :33:62, :93:35, :113:62, :114:{22,28}, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72}, :46:{54,64,71}, src/main/scala/util/package.scala:16:47
            sentPermission <= 2'h1;	// src/main/scala/gpcdcache/MSHR.scala:22:31
          if (_GEN_0) begin	// src/main/scala/gpcdcache/MSHR.scala:93:35
            if (_GEN_2)	// src/main/scala/gpcdcache/MSHR.scala:94:27
              metaCounter <= metaCounter + 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:25:28, :96:38, :136:30
            else if (_readAfterWriteFlag_T_2 | _readAfterWriteFlag_T_3
                     | _sentPermission_T_55 | _sentPermission_T_33 | _stallReq_T_6
                     | _GEN_1)	// src/main/scala/gpcdcache/MemConstants.scala:42:52, :44:82, :45:72, :46:71, src/main/scala/util/package.scala:16:47
              metaCounter <= metaCounter + 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:25:28, :98:36, :136:30
          end
        end
        else begin	// src/main/scala/gpcdcache/MSHR.scala:23:78
          if (io_isUpgrade)	// src/main/scala/gpcdcache/MSHR.scala:10:14
            sentPermission <= 2'h2;	// src/main/scala/gpcdcache/MSHR.scala:22:31
          else	// src/main/scala/gpcdcache/MSHR.scala:10:14
            sentPermission <=
              {1'h0,
               _sentPermission_T_30 | _sentPermission_T_31 | _sentPermission_T_33
                 | _sentPermission_T_35 | _sentPermission_T_36 | _sentPermission_T_37
                 | _sentPermission_T_38 | _sentPermission_T_42 | _sentPermission_T_43
                 | _sentPermission_T_44 | _sentPermission_T_45 | _sentPermission_T_46
                 | _sentPermission_T_53 | _sentPermission_T_55};	// src/main/scala/gpcdcache/MSHR.scala:22:31, :111:12, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72}, :46:{54,64,71}, src/main/scala/util/package.scala:16:47
          metaCounter <= 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:25:28, :136:30
        end
      end
      else if (_io_probeState_T & io_probePermission == 2'h2 & sentPermission == 2'h2)	// src/main/scala/gpcdcache/MSHR.scala:22:31, :54:33, :120:49, :121:{20,26}, :122:{26,66}
        sentPermission <= 2'h1;	// src/main/scala/gpcdcache/MSHR.scala:22:31
      if (allocateReq & ~(|state))	// src/main/scala/gpcdcache/MSHR.scala:13:100, :19:50, :23:{69,78}
        lineAddrReg <= io_allocLineAddr;	// src/main/scala/gpcdcache/MSHR.scala:23:33
      readAfterWriteFlag <=
        ~_readAfterWriteFlag_T
        & (allocLineAddrMatch & trueWriteFlag
           & (_readAfterWriteFlag_T_2 | _readAfterWriteFlag_T_3 | _sentPermission_T_55
              | _sentPermission_T_33 | _stallReq_T_6 | _sentPermission_T_35
              | _sentPermission_T_36 | _sentPermission_T_37 | _sentPermission_T_38
              | _sentPermission_T_42 | _sentPermission_T_43 | _sentPermission_T_44
              | _sentPermission_T_45 | _sentPermission_T_46)
           & ~(_stallReq_T_6 | _sentPermission_T_53) | readAfterWriteFlag);	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/gpcdcache/MSHR.scala:28:61, :35:35, :36:35, :62:14, :63:{65,68}, src/main/scala/gpcdcache/MemConstants.scala:43:48, :44:82, :45:72, :46:{54,71}, src/main/scala/util/package.scala:16:47
      trueWriteFlag <=
        ~_readAfterWriteFlag_T
        & (_GEN
             ? ((|state)
                  ? _GEN_0 & _GEN_2 | trueWriteFlag
                  : io_isUpgrade | _sentPermission_T_30 | _sentPermission_T_31
                    | _sentPermission_T_33 | _sentPermission_T_35 | _sentPermission_T_36
                    | _sentPermission_T_37 | _sentPermission_T_38 | _sentPermission_T_42
                    | _sentPermission_T_43 | _sentPermission_T_44 | _sentPermission_T_45
                    | _sentPermission_T_46)
             : trueWriteFlag);	// src/main/scala/chisel3/util/Mux.scala:141:16, src/main/scala/gpcdcache/MSHR.scala:13:100, :23:78, :36:35, :62:14, :86:30, :88:19, :89:{26,40}, :90:31, :92:{21,37}, :93:{35,62}, :94:{27,50}, :95:23, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72}, src/main/scala/util/package.scala:16:47
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:1];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        state = _RANDOM[1'h0][2:0];	// src/main/scala/gpcdcache/MSHR.scala:13:100
        sentPermission = _RANDOM[1'h0][4:3];	// src/main/scala/gpcdcache/MSHR.scala:13:100, :22:31
        lineAddrReg = {_RANDOM[1'h0][31:5], _RANDOM[1'h1][5:0]};	// src/main/scala/gpcdcache/MSHR.scala:13:100, :23:33
        metaCounter = _RANDOM[1'h1][8:6];	// src/main/scala/gpcdcache/MSHR.scala:23:33, :25:28
        readAfterWriteFlag = _RANDOM[1'h1][9];	// src/main/scala/gpcdcache/MSHR.scala:23:33, :35:35
        trueWriteFlag = _RANDOM[1'h1][10];	// src/main/scala/gpcdcache/MSHR.scala:23:33, :36:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_allocLineAddrMatch = allocLineAddrMatch;	// src/main/scala/gpcdcache/MSHR.scala:28:61
  assign io_writeCounter =
    trueWriteFlag & allocateReq
    & (_sentPermission_T_30 | _sentPermission_T_31 | _sentPermission_T_33
       | _sentPermission_T_35 | _sentPermission_T_36 | _sentPermission_T_37
       | _sentPermission_T_38 | _sentPermission_T_42 | _sentPermission_T_43
       | _sentPermission_T_44 | _sentPermission_T_45 | _sentPermission_T_46)
      ? metaCounter - 3'h1
      : metaCounter;	// src/main/scala/gpcdcache/MSHR.scala:19:50, :25:28, :36:35, :77:25, :78:34, :79:17, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72,82}, src/main/scala/util/package.scala:16:47
  assign io_replayCounter = metaCounter;	// src/main/scala/gpcdcache/MSHR.scala:25:28
  assign io_isEmpty = ~(|state);	// src/main/scala/gpcdcache/MSHR.scala:13:100, :23:78
  assign io_stallReq = stallReq;	// src/main/scala/gpcdcache/MSHR.scala:72:87
  assign io_senderPermission = sentPermission;	// src/main/scala/gpcdcache/MSHR.scala:22:31
  assign io_senderLineAddr = lineAddrReg;	// src/main/scala/gpcdcache/MSHR.scala:23:33
  assign io_probeLineAddrMatch = _io_probeLineAddrMatch_output;	// src/main/scala/gpcdcache/MSHR.scala:56:14
  assign io_probeState = _io_probeState_T ? probeState : 2'h0;	// src/main/scala/gpcdcache/MSHR.scala:39:23, :54:{23,33}
endmodule

