// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module MyQueue_1(
  input        clock,
               reset,
               io_enq_valid,	// src/main/scala/gpcdcache/RefillQueue.scala:184:14
  input  [1:0] io_enq_bits,	// src/main/scala/gpcdcache/RefillQueue.scala:184:14
  input        io_deq_ready,	// src/main/scala/gpcdcache/RefillQueue.scala:184:14
  output [1:0] io_deq_bits	// src/main/scala/gpcdcache/RefillQueue.scala:184:14
);

  wire            _io_enq_ready_T;	// src/main/scala/gpcdcache/RefillQueue.scala:211:19
  wire            _io_deq_valid_T;	// src/main/scala/gpcdcache/RefillQueue.scala:210:19
  reg  [1:0]      queue_0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_1;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_2;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_3;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_4;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_5;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_6;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [1:0]      queue_7;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
  reg  [2:0]      enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [2:0]      deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg             maybe_full;	// src/main/scala/gpcdcache/RefillQueue.scala:192:27
  wire            ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:193:34
  wire            empty = ptr_match & ~maybe_full;	// src/main/scala/gpcdcache/RefillQueue.scala:192:27, :193:34, :194:{30,33}
  wire            full = ptr_match & maybe_full;	// src/main/scala/gpcdcache/RefillQueue.scala:192:27, :193:34, :195:30
  wire            do_enq = _io_enq_ready_T & io_enq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/RefillQueue.scala:196:31, :211:19
  wire            do_deq = io_deq_ready & _io_deq_valid_T;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/RefillQueue.scala:197:31, :210:19
  wire            wrap = &enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24, src/main/scala/gpcdcache/RefillQueue.scala:200:26
  wire            wrap_1 = &deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
  assign _io_deq_valid_T = ~empty;	// src/main/scala/gpcdcache/RefillQueue.scala:194:30, :210:19
  assign _io_enq_ready_T = ~full;	// src/main/scala/gpcdcache/RefillQueue.scala:195:30, :211:19
  wire [7:0][1:0] _GEN =
    {{queue_7},
     {queue_6},
     {queue_5},
     {queue_4},
     {queue_3},
     {queue_2},
     {queue_1},
     {queue_0}};	// src/main/scala/gpcdcache/RefillQueue.scala:189:27, :213:15
  always @(posedge clock) begin
    if (reset) begin
      queue_0 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_1 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_2 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_3 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_4 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_5 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_6 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      queue_7 <= 2'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:189:{27,66}
      enq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 3'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/gpcdcache/RefillQueue.scala:192:27
    end
    else begin
      if (do_enq & enq_ptr_value == 3'h0)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_0 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & enq_ptr_value == 3'h1)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_1 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & enq_ptr_value == 3'h2)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_2 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & enq_ptr_value == 3'h3)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_3 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & enq_ptr_value == 3'h4)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_4 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & enq_ptr_value == 3'h5)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_5 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & enq_ptr_value == 3'h6)	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_6 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq & (&enq_ptr_value))	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27, :196:31, :199:16, :200:26
        queue_7 <= io_enq_bits;	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
      if (do_enq)	// src/main/scala/gpcdcache/RefillQueue.scala:196:31
        enq_ptr_value <= enq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24, src/main/scala/gpcdcache/RefillQueue.scala:200:26
      if (do_deq)	// src/main/scala/gpcdcache/RefillQueue.scala:197:31
        deq_ptr_value <= deq_ptr_value + 3'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24, src/main/scala/gpcdcache/RefillQueue.scala:200:26
      if (do_enq != do_deq)	// src/main/scala/gpcdcache/RefillQueue.scala:196:31, :197:31, :206:15
        maybe_full <= do_enq;	// src/main/scala/gpcdcache/RefillQueue.scala:192:27, :196:31
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:0];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        queue_0 = _RANDOM[/*Zero width*/ 1'b0][1:0];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_1 = _RANDOM[/*Zero width*/ 1'b0][3:2];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_2 = _RANDOM[/*Zero width*/ 1'b0][5:4];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_3 = _RANDOM[/*Zero width*/ 1'b0][7:6];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_4 = _RANDOM[/*Zero width*/ 1'b0][9:8];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_5 = _RANDOM[/*Zero width*/ 1'b0][11:10];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_6 = _RANDOM[/*Zero width*/ 1'b0][13:12];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        queue_7 = _RANDOM[/*Zero width*/ 1'b0][15:14];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27
        enq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][18:16];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27
        deq_ptr_value = _RANDOM[/*Zero width*/ 1'b0][21:19];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:189:27
        maybe_full = _RANDOM[/*Zero width*/ 1'b0][22];	// src/main/scala/gpcdcache/RefillQueue.scala:189:27, :192:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_deq_bits = _GEN[deq_ptr_value];	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/gpcdcache/RefillQueue.scala:213:15
endmodule

