// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module ReplayModule(
  input          clock,
                 reset,
                 io_toReplace_ready,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [1:0]   io_replaceStatus,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input          io_innerIO_valid,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [1:0]   io_innerIO_bits_perm,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [32:0]  io_innerIO_bits_lineAddr,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [1:0]   io_innerIO_bits_meta_sourceId,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [4:0]   io_innerIO_bits_meta_regIdx,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [2:0]   io_innerIO_bits_meta_size,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input          io_innerIO_bits_meta_signed,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [5:0]   io_innerIO_bits_meta_offset,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [4:0]   io_innerIO_bits_meta_cmd,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [63:0]  io_innerIO_bits_mask,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [511:0] io_innerIO_bits_data,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  input  [2:0]   io_innerIO_bits_entryIdx,	// src/main/scala/gpcdcache/MSHR.scala:147:14
                 io_innerIO_bits_counter,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output         io_toPipe_valid,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [1:0]   io_toPipe_bits_sourceId,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [4:0]   io_toPipe_bits_regIdx,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [511:0] io_toPipe_bits_regData,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output         io_toPipe_bits_nextCycleWb,	// src/main/scala/gpcdcache/MSHR.scala:147:14
                 io_toReplace_valid,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [1:0]   io_toReplace_bits_state,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [32:0]  io_toReplace_bits_lineAddr,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [511:0] io_toReplace_bits_data,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output         io_innerIO_ready,	// src/main/scala/gpcdcache/MSHR.scala:147:14
  output [2:0]   io_idxMeta,	// src/main/scala/gpcdcache/MSHR.scala:147:14
                 io_replayIdx	// src/main/scala/gpcdcache/MSHR.scala:147:14
);

  wire         loadgen_doZero = 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32
  wire         loadgen_doZero_1 = 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32
  wire         loadgen_doZero_2 = 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32
  wire         loadgen_doZero_3 = 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32
  wire         loadgen_doZero_4 = 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32
  wire         loadgen_doZero_5 = 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32
  reg  [511:0] replayReg;	// src/main/scala/gpcdcache/MSHR.scala:149:34
  reg  [2:0]   state;	// src/main/scala/gpcdcache/MSHR.scala:152:104
  reg  [2:0]   metaCounter;	// src/main/scala/gpcdcache/MSHR.scala:154:28
  wire         initEnable = ~(|state) & io_innerIO_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/MSHR.scala:152:104, :215:35, :230:29
  reg  [2:0]   mshrEntryIdx;	// src/main/scala/gpcdcache/MSHR.scala:157:31
  reg  [2:0]   totalCounter;	// src/main/scala/gpcdcache/MSHR.scala:162:33
  reg  [32:0]  replayLineAddr;	// src/main/scala/gpcdcache/MSHR.scala:163:33
  reg  [1:0]   replayPerm;	// src/main/scala/gpcdcache/MSHR.scala:164:33
  wire         _replayReg_T = state == 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :166:41
  wire         underReplay = initEnable | _replayReg_T;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/MSHR.scala:166:{32,41}
  reg  [1:0]   replayMeta_sourceId;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  reg  [4:0]   replayMeta_regIdx;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  reg  [2:0]   replayMeta_size;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  wire [2:0]   loadgen_size = replayMeta_size;	// src/main/scala/gpcdcache/AMOALU.scala:9:22, src/main/scala/gpcdcache/MSHR.scala:168:29
  reg          replayMeta_signed;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  reg  [5:0]   replayMeta_offset;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  reg  [4:0]   replayMeta_cmd;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  reg          writeRecord;	// src/main/scala/gpcdcache/MSHR.scala:170:28
  wire [255:0] loadgen_shifted =
    replayMeta_offset[5] ? replayReg[511:256] : replayReg[255:0];	// src/main/scala/gpcdcache/AMOALU.scala:62:{24,29,37,60}, src/main/scala/gpcdcache/MSHR.scala:149:34, :168:29
  wire [255:0] loadgen_zeroed = loadgen_shifted;	// src/main/scala/gpcdcache/AMOALU.scala:62:24, :64:24
  wire [127:0] loadgen_shifted_1 =
    replayMeta_offset[4] ? loadgen_zeroed[255:128] : loadgen_zeroed[127:0];	// src/main/scala/gpcdcache/AMOALU.scala:62:{24,29,37,60}, :64:24, src/main/scala/gpcdcache/MSHR.scala:168:29
  wire [127:0] loadgen_zeroed_1 = loadgen_shifted_1;	// src/main/scala/gpcdcache/AMOALU.scala:62:24, :64:24
  wire [63:0]  loadgen_shifted_2 =
    replayMeta_offset[3] ? loadgen_zeroed_1[127:64] : loadgen_zeroed_1[63:0];	// src/main/scala/gpcdcache/AMOALU.scala:62:{24,29,37,60}, :64:24, src/main/scala/gpcdcache/MSHR.scala:168:29
  wire [63:0]  loadgen_zeroed_2 = loadgen_shifted_2;	// src/main/scala/gpcdcache/AMOALU.scala:62:24, :64:24
  wire [31:0]  loadgen_shifted_3 =
    replayMeta_offset[2] ? loadgen_zeroed_2[63:32] : loadgen_zeroed_2[31:0];	// src/main/scala/gpcdcache/AMOALU.scala:62:{24,29,37,60}, :64:24, src/main/scala/gpcdcache/MSHR.scala:168:29
  wire [31:0]  loadgen_zeroed_3 = loadgen_shifted_3;	// src/main/scala/gpcdcache/AMOALU.scala:62:24, :64:24
  wire [15:0]  loadgen_shifted_4 =
    replayMeta_offset[1] ? loadgen_zeroed_3[31:16] : loadgen_zeroed_3[15:0];	// src/main/scala/gpcdcache/AMOALU.scala:62:{24,29,37,60}, :64:24, src/main/scala/gpcdcache/MSHR.scala:168:29
  wire [15:0]  loadgen_zeroed_4 = loadgen_shifted_4;	// src/main/scala/gpcdcache/AMOALU.scala:62:24, :64:24
  wire [7:0]   loadgen_shifted_5 =
    replayMeta_offset[0] ? loadgen_zeroed_4[15:8] : loadgen_zeroed_4[7:0];	// src/main/scala/gpcdcache/AMOALU.scala:62:{24,29,37,60}, :64:24, src/main/scala/gpcdcache/MSHR.scala:168:29
  wire [7:0]   loadgen_zeroed_5 = loadgen_shifted_5;	// src/main/scala/gpcdcache/AMOALU.scala:62:24, :64:24
  wire [511:0] loadgen =
    {loadgen_size == 3'h0
       ? {504{replayMeta_signed & loadgen_zeroed_5[7]}}
       : {loadgen_size == 3'h1
            ? {496{replayMeta_signed & loadgen_zeroed_4[15]}}
            : {loadgen_size == 3'h2
                 ? {480{replayMeta_signed & loadgen_zeroed_3[31]}}
                 : {loadgen_size == 3'h3
                      ? {448{replayMeta_signed & loadgen_zeroed_2[63]}}
                      : {loadgen_size == 3'h4
                           ? {384{replayMeta_signed & loadgen_zeroed_1[127]}}
                           : {loadgen_size == 3'h5
                                ? {256{replayMeta_signed & loadgen_zeroed[255]}}
                                : replayReg[511:256],
                              loadgen_zeroed[255:128]},
                         loadgen_zeroed_1[127:64]},
                    loadgen_zeroed_2[63:32]},
               loadgen_zeroed_3[31:16]},
          loadgen_zeroed_4[15:8]},
     loadgen_zeroed_5};	// src/main/scala/gpcdcache/AMOALU.scala:9:22, :62:37, :64:24, :65:16, :66:12, :67:16, :68:{15,49,58}, :69:14, src/main/scala/gpcdcache/MSHR.scala:149:34, :152:104, :158:15, :166:41, :168:29, :218:31, :219:31
  wire [7:0]   replayReg_originDataByte_0 = replayReg[7:0];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_1 = replayReg[15:8];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_2 = replayReg[23:16];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_3 = replayReg[31:24];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_4 = replayReg[39:32];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_5 = replayReg[47:40];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_6 = replayReg[55:48];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_7 = replayReg[63:56];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_8 = replayReg[71:64];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_9 = replayReg[79:72];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_10 = replayReg[87:80];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_11 = replayReg[95:88];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_12 = replayReg[103:96];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_13 = replayReg[111:104];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_14 = replayReg[119:112];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_15 = replayReg[127:120];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_16 = replayReg[135:128];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_17 = replayReg[143:136];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_18 = replayReg[151:144];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_19 = replayReg[159:152];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_20 = replayReg[167:160];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_21 = replayReg[175:168];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_22 = replayReg[183:176];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_23 = replayReg[191:184];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_24 = replayReg[199:192];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_25 = replayReg[207:200];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_26 = replayReg[215:208];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_27 = replayReg[223:216];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_28 = replayReg[231:224];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_29 = replayReg[239:232];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_30 = replayReg[247:240];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_31 = replayReg[255:248];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_32 = replayReg[263:256];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_33 = replayReg[271:264];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_34 = replayReg[279:272];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_35 = replayReg[287:280];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_36 = replayReg[295:288];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_37 = replayReg[303:296];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_38 = replayReg[311:304];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_39 = replayReg[319:312];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_40 = replayReg[327:320];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_41 = replayReg[335:328];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_42 = replayReg[343:336];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_43 = replayReg[351:344];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_44 = replayReg[359:352];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_45 = replayReg[367:360];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_46 = replayReg[375:368];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_47 = replayReg[383:376];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_48 = replayReg[391:384];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_49 = replayReg[399:392];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_50 = replayReg[407:400];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_51 = replayReg[415:408];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_52 = replayReg[423:416];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_53 = replayReg[431:424];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_54 = replayReg[439:432];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_55 = replayReg[447:440];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_56 = replayReg[455:448];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_57 = replayReg[463:456];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_58 = replayReg[471:464];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_59 = replayReg[479:472];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_60 = replayReg[487:480];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_61 = replayReg[495:488];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_62 = replayReg[503:496];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_originDataByte_63 = replayReg[511:504];	// src/main/scala/gpcdcache/MSHR.scala:149:34, :190:45
  wire [7:0]   replayReg_newDataByte_0 = io_innerIO_bits_data[7:0];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_1 = io_innerIO_bits_data[15:8];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_2 = io_innerIO_bits_data[23:16];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_3 = io_innerIO_bits_data[31:24];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_4 = io_innerIO_bits_data[39:32];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_5 = io_innerIO_bits_data[47:40];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_6 = io_innerIO_bits_data[55:48];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_7 = io_innerIO_bits_data[63:56];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_8 = io_innerIO_bits_data[71:64];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_9 = io_innerIO_bits_data[79:72];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_10 = io_innerIO_bits_data[87:80];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_11 = io_innerIO_bits_data[95:88];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_12 = io_innerIO_bits_data[103:96];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_13 = io_innerIO_bits_data[111:104];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_14 = io_innerIO_bits_data[119:112];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_15 = io_innerIO_bits_data[127:120];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_16 = io_innerIO_bits_data[135:128];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_17 = io_innerIO_bits_data[143:136];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_18 = io_innerIO_bits_data[151:144];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_19 = io_innerIO_bits_data[159:152];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_20 = io_innerIO_bits_data[167:160];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_21 = io_innerIO_bits_data[175:168];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_22 = io_innerIO_bits_data[183:176];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_23 = io_innerIO_bits_data[191:184];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_24 = io_innerIO_bits_data[199:192];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_25 = io_innerIO_bits_data[207:200];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_26 = io_innerIO_bits_data[215:208];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_27 = io_innerIO_bits_data[223:216];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_28 = io_innerIO_bits_data[231:224];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_29 = io_innerIO_bits_data[239:232];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_30 = io_innerIO_bits_data[247:240];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_31 = io_innerIO_bits_data[255:248];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_32 = io_innerIO_bits_data[263:256];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_33 = io_innerIO_bits_data[271:264];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_34 = io_innerIO_bits_data[279:272];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_35 = io_innerIO_bits_data[287:280];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_36 = io_innerIO_bits_data[295:288];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_37 = io_innerIO_bits_data[303:296];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_38 = io_innerIO_bits_data[311:304];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_39 = io_innerIO_bits_data[319:312];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_40 = io_innerIO_bits_data[327:320];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_41 = io_innerIO_bits_data[335:328];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_42 = io_innerIO_bits_data[343:336];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_43 = io_innerIO_bits_data[351:344];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_44 = io_innerIO_bits_data[359:352];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_45 = io_innerIO_bits_data[367:360];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_46 = io_innerIO_bits_data[375:368];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_47 = io_innerIO_bits_data[383:376];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_48 = io_innerIO_bits_data[391:384];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_49 = io_innerIO_bits_data[399:392];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_50 = io_innerIO_bits_data[407:400];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_51 = io_innerIO_bits_data[415:408];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_52 = io_innerIO_bits_data[423:416];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_53 = io_innerIO_bits_data[431:424];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_54 = io_innerIO_bits_data[439:432];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_55 = io_innerIO_bits_data[447:440];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_56 = io_innerIO_bits_data[455:448];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_57 = io_innerIO_bits_data[463:456];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_58 = io_innerIO_bits_data[471:464];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_59 = io_innerIO_bits_data[479:472];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_60 = io_innerIO_bits_data[487:480];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_61 = io_innerIO_bits_data[495:488];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_62 = io_innerIO_bits_data[503:496];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_newDataByte_63 = io_innerIO_bits_data[511:504];	// src/main/scala/gpcdcache/MSHR.scala:191:42
  wire [7:0]   replayReg_res_0 =
    io_innerIO_bits_mask[0] ? replayReg_newDataByte_0 : replayReg_originDataByte_0;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_1 =
    io_innerIO_bits_mask[1] ? replayReg_newDataByte_1 : replayReg_originDataByte_1;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_2 =
    io_innerIO_bits_mask[2] ? replayReg_newDataByte_2 : replayReg_originDataByte_2;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_3 =
    io_innerIO_bits_mask[3] ? replayReg_newDataByte_3 : replayReg_originDataByte_3;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_4 =
    io_innerIO_bits_mask[4] ? replayReg_newDataByte_4 : replayReg_originDataByte_4;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_5 =
    io_innerIO_bits_mask[5] ? replayReg_newDataByte_5 : replayReg_originDataByte_5;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_6 =
    io_innerIO_bits_mask[6] ? replayReg_newDataByte_6 : replayReg_originDataByte_6;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_7 =
    io_innerIO_bits_mask[7] ? replayReg_newDataByte_7 : replayReg_originDataByte_7;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_8 =
    io_innerIO_bits_mask[8] ? replayReg_newDataByte_8 : replayReg_originDataByte_8;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_9 =
    io_innerIO_bits_mask[9] ? replayReg_newDataByte_9 : replayReg_originDataByte_9;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_10 =
    io_innerIO_bits_mask[10] ? replayReg_newDataByte_10 : replayReg_originDataByte_10;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_11 =
    io_innerIO_bits_mask[11] ? replayReg_newDataByte_11 : replayReg_originDataByte_11;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_12 =
    io_innerIO_bits_mask[12] ? replayReg_newDataByte_12 : replayReg_originDataByte_12;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_13 =
    io_innerIO_bits_mask[13] ? replayReg_newDataByte_13 : replayReg_originDataByte_13;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_14 =
    io_innerIO_bits_mask[14] ? replayReg_newDataByte_14 : replayReg_originDataByte_14;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_15 =
    io_innerIO_bits_mask[15] ? replayReg_newDataByte_15 : replayReg_originDataByte_15;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_16 =
    io_innerIO_bits_mask[16] ? replayReg_newDataByte_16 : replayReg_originDataByte_16;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_17 =
    io_innerIO_bits_mask[17] ? replayReg_newDataByte_17 : replayReg_originDataByte_17;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_18 =
    io_innerIO_bits_mask[18] ? replayReg_newDataByte_18 : replayReg_originDataByte_18;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_19 =
    io_innerIO_bits_mask[19] ? replayReg_newDataByte_19 : replayReg_originDataByte_19;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_20 =
    io_innerIO_bits_mask[20] ? replayReg_newDataByte_20 : replayReg_originDataByte_20;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_21 =
    io_innerIO_bits_mask[21] ? replayReg_newDataByte_21 : replayReg_originDataByte_21;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_22 =
    io_innerIO_bits_mask[22] ? replayReg_newDataByte_22 : replayReg_originDataByte_22;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_23 =
    io_innerIO_bits_mask[23] ? replayReg_newDataByte_23 : replayReg_originDataByte_23;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_24 =
    io_innerIO_bits_mask[24] ? replayReg_newDataByte_24 : replayReg_originDataByte_24;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_25 =
    io_innerIO_bits_mask[25] ? replayReg_newDataByte_25 : replayReg_originDataByte_25;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_26 =
    io_innerIO_bits_mask[26] ? replayReg_newDataByte_26 : replayReg_originDataByte_26;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_27 =
    io_innerIO_bits_mask[27] ? replayReg_newDataByte_27 : replayReg_originDataByte_27;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_28 =
    io_innerIO_bits_mask[28] ? replayReg_newDataByte_28 : replayReg_originDataByte_28;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_29 =
    io_innerIO_bits_mask[29] ? replayReg_newDataByte_29 : replayReg_originDataByte_29;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_30 =
    io_innerIO_bits_mask[30] ? replayReg_newDataByte_30 : replayReg_originDataByte_30;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_31 =
    io_innerIO_bits_mask[31] ? replayReg_newDataByte_31 : replayReg_originDataByte_31;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_32 =
    io_innerIO_bits_mask[32] ? replayReg_newDataByte_32 : replayReg_originDataByte_32;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_33 =
    io_innerIO_bits_mask[33] ? replayReg_newDataByte_33 : replayReg_originDataByte_33;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_34 =
    io_innerIO_bits_mask[34] ? replayReg_newDataByte_34 : replayReg_originDataByte_34;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_35 =
    io_innerIO_bits_mask[35] ? replayReg_newDataByte_35 : replayReg_originDataByte_35;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_36 =
    io_innerIO_bits_mask[36] ? replayReg_newDataByte_36 : replayReg_originDataByte_36;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_37 =
    io_innerIO_bits_mask[37] ? replayReg_newDataByte_37 : replayReg_originDataByte_37;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_38 =
    io_innerIO_bits_mask[38] ? replayReg_newDataByte_38 : replayReg_originDataByte_38;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_39 =
    io_innerIO_bits_mask[39] ? replayReg_newDataByte_39 : replayReg_originDataByte_39;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_40 =
    io_innerIO_bits_mask[40] ? replayReg_newDataByte_40 : replayReg_originDataByte_40;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_41 =
    io_innerIO_bits_mask[41] ? replayReg_newDataByte_41 : replayReg_originDataByte_41;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_42 =
    io_innerIO_bits_mask[42] ? replayReg_newDataByte_42 : replayReg_originDataByte_42;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_43 =
    io_innerIO_bits_mask[43] ? replayReg_newDataByte_43 : replayReg_originDataByte_43;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_44 =
    io_innerIO_bits_mask[44] ? replayReg_newDataByte_44 : replayReg_originDataByte_44;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_45 =
    io_innerIO_bits_mask[45] ? replayReg_newDataByte_45 : replayReg_originDataByte_45;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_46 =
    io_innerIO_bits_mask[46] ? replayReg_newDataByte_46 : replayReg_originDataByte_46;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_47 =
    io_innerIO_bits_mask[47] ? replayReg_newDataByte_47 : replayReg_originDataByte_47;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_48 =
    io_innerIO_bits_mask[48] ? replayReg_newDataByte_48 : replayReg_originDataByte_48;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_49 =
    io_innerIO_bits_mask[49] ? replayReg_newDataByte_49 : replayReg_originDataByte_49;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_50 =
    io_innerIO_bits_mask[50] ? replayReg_newDataByte_50 : replayReg_originDataByte_50;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_51 =
    io_innerIO_bits_mask[51] ? replayReg_newDataByte_51 : replayReg_originDataByte_51;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_52 =
    io_innerIO_bits_mask[52] ? replayReg_newDataByte_52 : replayReg_originDataByte_52;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_53 =
    io_innerIO_bits_mask[53] ? replayReg_newDataByte_53 : replayReg_originDataByte_53;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_54 =
    io_innerIO_bits_mask[54] ? replayReg_newDataByte_54 : replayReg_originDataByte_54;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_55 =
    io_innerIO_bits_mask[55] ? replayReg_newDataByte_55 : replayReg_originDataByte_55;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_56 =
    io_innerIO_bits_mask[56] ? replayReg_newDataByte_56 : replayReg_originDataByte_56;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_57 =
    io_innerIO_bits_mask[57] ? replayReg_newDataByte_57 : replayReg_originDataByte_57;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_58 =
    io_innerIO_bits_mask[58] ? replayReg_newDataByte_58 : replayReg_originDataByte_58;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_59 =
    io_innerIO_bits_mask[59] ? replayReg_newDataByte_59 : replayReg_originDataByte_59;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_60 =
    io_innerIO_bits_mask[60] ? replayReg_newDataByte_60 : replayReg_originDataByte_60;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_61 =
    io_innerIO_bits_mask[61] ? replayReg_newDataByte_61 : replayReg_originDataByte_61;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_62 =
    io_innerIO_bits_mask[62] ? replayReg_newDataByte_62 : replayReg_originDataByte_62;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [7:0]   replayReg_res_63 =
    io_innerIO_bits_mask[63] ? replayReg_newDataByte_63 : replayReg_originDataByte_63;	// src/main/scala/gpcdcache/MSHR.scala:190:45, :191:42, :192:30, :194:{20,25}
  wire [15:0]  replayReg_lo_lo_lo_lo_lo = {replayReg_res_1, replayReg_res_0};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_lo_lo_lo_hi = {replayReg_res_3, replayReg_res_2};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_lo_lo_lo =
    {replayReg_lo_lo_lo_lo_hi, replayReg_lo_lo_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_lo_lo_hi_lo = {replayReg_res_5, replayReg_res_4};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_lo_lo_hi_hi = {replayReg_res_7, replayReg_res_6};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_lo_lo_hi =
    {replayReg_lo_lo_lo_hi_hi, replayReg_lo_lo_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_lo_lo_lo = {replayReg_lo_lo_lo_hi, replayReg_lo_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_lo_hi_lo_lo = {replayReg_res_9, replayReg_res_8};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_lo_hi_lo_hi = {replayReg_res_11, replayReg_res_10};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_lo_hi_lo =
    {replayReg_lo_lo_hi_lo_hi, replayReg_lo_lo_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_lo_hi_hi_lo = {replayReg_res_13, replayReg_res_12};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_lo_hi_hi_hi = {replayReg_res_15, replayReg_res_14};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_lo_hi_hi =
    {replayReg_lo_lo_hi_hi_hi, replayReg_lo_lo_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_lo_lo_hi = {replayReg_lo_lo_hi_hi, replayReg_lo_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [127:0] replayReg_lo_lo = {replayReg_lo_lo_hi, replayReg_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_hi_lo_lo_lo = {replayReg_res_17, replayReg_res_16};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_hi_lo_lo_hi = {replayReg_res_19, replayReg_res_18};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_hi_lo_lo =
    {replayReg_lo_hi_lo_lo_hi, replayReg_lo_hi_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_hi_lo_hi_lo = {replayReg_res_21, replayReg_res_20};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_hi_lo_hi_hi = {replayReg_res_23, replayReg_res_22};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_hi_lo_hi =
    {replayReg_lo_hi_lo_hi_hi, replayReg_lo_hi_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_lo_hi_lo = {replayReg_lo_hi_lo_hi, replayReg_lo_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_hi_hi_lo_lo = {replayReg_res_25, replayReg_res_24};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_hi_hi_lo_hi = {replayReg_res_27, replayReg_res_26};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_hi_hi_lo =
    {replayReg_lo_hi_hi_lo_hi, replayReg_lo_hi_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_lo_hi_hi_hi_lo = {replayReg_res_29, replayReg_res_28};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_lo_hi_hi_hi_hi = {replayReg_res_31, replayReg_res_30};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_lo_hi_hi_hi =
    {replayReg_lo_hi_hi_hi_hi, replayReg_lo_hi_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_lo_hi_hi = {replayReg_lo_hi_hi_hi, replayReg_lo_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [127:0] replayReg_lo_hi = {replayReg_lo_hi_hi, replayReg_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [255:0] replayReg_lo = {replayReg_lo_hi, replayReg_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_lo_lo_lo_lo = {replayReg_res_33, replayReg_res_32};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_lo_lo_lo_hi = {replayReg_res_35, replayReg_res_34};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_lo_lo_lo =
    {replayReg_hi_lo_lo_lo_hi, replayReg_hi_lo_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_lo_lo_hi_lo = {replayReg_res_37, replayReg_res_36};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_lo_lo_hi_hi = {replayReg_res_39, replayReg_res_38};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_lo_lo_hi =
    {replayReg_hi_lo_lo_hi_hi, replayReg_hi_lo_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_hi_lo_lo = {replayReg_hi_lo_lo_hi, replayReg_hi_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_lo_hi_lo_lo = {replayReg_res_41, replayReg_res_40};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_lo_hi_lo_hi = {replayReg_res_43, replayReg_res_42};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_lo_hi_lo =
    {replayReg_hi_lo_hi_lo_hi, replayReg_hi_lo_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_lo_hi_hi_lo = {replayReg_res_45, replayReg_res_44};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_lo_hi_hi_hi = {replayReg_res_47, replayReg_res_46};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_lo_hi_hi =
    {replayReg_hi_lo_hi_hi_hi, replayReg_hi_lo_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_hi_lo_hi = {replayReg_hi_lo_hi_hi, replayReg_hi_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [127:0] replayReg_hi_lo = {replayReg_hi_lo_hi, replayReg_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_hi_lo_lo_lo = {replayReg_res_49, replayReg_res_48};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_hi_lo_lo_hi = {replayReg_res_51, replayReg_res_50};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_hi_lo_lo =
    {replayReg_hi_hi_lo_lo_hi, replayReg_hi_hi_lo_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_hi_lo_hi_lo = {replayReg_res_53, replayReg_res_52};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_hi_lo_hi_hi = {replayReg_res_55, replayReg_res_54};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_hi_lo_hi =
    {replayReg_hi_hi_lo_hi_hi, replayReg_hi_hi_lo_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_hi_hi_lo = {replayReg_hi_hi_lo_hi, replayReg_hi_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_hi_hi_lo_lo = {replayReg_res_57, replayReg_res_56};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_hi_hi_lo_hi = {replayReg_res_59, replayReg_res_58};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_hi_hi_lo =
    {replayReg_hi_hi_hi_lo_hi, replayReg_hi_hi_hi_lo_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [15:0]  replayReg_hi_hi_hi_hi_lo = {replayReg_res_61, replayReg_res_60};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [15:0]  replayReg_hi_hi_hi_hi_hi = {replayReg_res_63, replayReg_res_62};	// src/main/scala/gpcdcache/MSHR.scala:192:30, :195:9
  wire [31:0]  replayReg_hi_hi_hi_hi =
    {replayReg_hi_hi_hi_hi_hi, replayReg_hi_hi_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [63:0]  replayReg_hi_hi_hi = {replayReg_hi_hi_hi_hi, replayReg_hi_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [127:0] replayReg_hi_hi = {replayReg_hi_hi_hi, replayReg_hi_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire [255:0] replayReg_hi = {replayReg_hi_hi, replayReg_hi_lo};	// src/main/scala/gpcdcache/MSHR.scala:195:9
  wire         _io_toPipe_bits_nextCycleWb_output =
    underReplay & metaCounter < ((|state) ? totalCounter : io_innerIO_bits_counter)
    & ~(io_innerIO_bits_meta_cmd == 5'h2 | io_innerIO_bits_meta_cmd == 5'h3
        | io_innerIO_bits_meta_cmd == 5'h1 | io_innerIO_bits_meta_cmd == 5'h11
        | io_innerIO_bits_meta_cmd == 5'h7 | io_innerIO_bits_meta_cmd == 5'h4
        | io_innerIO_bits_meta_cmd == 5'h9 | io_innerIO_bits_meta_cmd == 5'hA
        | io_innerIO_bits_meta_cmd == 5'hB | io_innerIO_bits_meta_cmd == 5'h8
        | io_innerIO_bits_meta_cmd == 5'hC | io_innerIO_bits_meta_cmd == 5'hD
        | io_innerIO_bits_meta_cmd == 5'hE | io_innerIO_bits_meta_cmd == 5'hF
        | io_innerIO_bits_meta_cmd == 5'h6);	// src/main/scala/gpcdcache/MSHR.scala:152:104, :154:28, :162:33, :166:32, :215:35, :248:{61,66}, :252:{6,9,48}, src/main/scala/gpcdcache/MemConstants.scala:43:{38,55}, :45:{38,55,72}, :46:71, src/main/scala/util/package.scala:16:47
  reg          io_toPipe_valid_REG;	// src/main/scala/gpcdcache/MSHR.scala:254:37
  always @(posedge clock) begin
    if (reset) begin
      replayReg <= 512'h0;	// src/main/scala/gpcdcache/MSHR.scala:149:34
      state <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104
      metaCounter <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :154:28
      mshrEntryIdx <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :157:31
      totalCounter <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :162:33
      replayLineAddr <= 33'h0;	// src/main/scala/gpcdcache/MSHR.scala:163:33
      replayPerm <= 2'h1;	// src/main/scala/gpcdcache/MSHR.scala:164:33
      writeRecord <= 1'h0;	// src/main/scala/gpcdcache/AMOALU.scala:63:32, src/main/scala/gpcdcache/MSHR.scala:170:28
    end
    else begin
      automatic logic _metaCounter_T;	// src/main/scala/gpcdcache/MSHR.scala:158:15
      automatic logic _replayReg_T_1;	// src/main/scala/gpcdcache/MemConstants.scala:45:38
      automatic logic _replayReg_T_2;	// src/main/scala/gpcdcache/MemConstants.scala:45:55
      automatic logic _replayReg_T_4;	// src/main/scala/gpcdcache/MemConstants.scala:45:72
      automatic logic _replayReg_T_6;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_7;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_8;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_9;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_13;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_14;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_15;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_16;	// src/main/scala/util/package.scala:16:47
      automatic logic _replayReg_T_17;	// src/main/scala/util/package.scala:16:47
      automatic logic _state_T_17;	// src/main/scala/gpcdcache/MSHR.scala:172:47
      automatic logic _state_T_11;	// src/main/scala/gpcdcache/MSHR.scala:172:47
      _metaCounter_T = state == 3'h4;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :158:15
      _replayReg_T_1 = replayMeta_cmd == 5'h1;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/gpcdcache/MemConstants.scala:45:38
      _replayReg_T_2 = replayMeta_cmd == 5'h11;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/gpcdcache/MemConstants.scala:45:55
      _replayReg_T_4 = replayMeta_cmd == 5'h7;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/gpcdcache/MemConstants.scala:45:72
      _replayReg_T_6 = replayMeta_cmd == 5'h4;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_7 = replayMeta_cmd == 5'h9;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_8 = replayMeta_cmd == 5'hA;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_9 = replayMeta_cmd == 5'hB;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_13 = replayMeta_cmd == 5'h8;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_14 = replayMeta_cmd == 5'hC;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_15 = replayMeta_cmd == 5'hD;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_16 = replayMeta_cmd == 5'hE;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _replayReg_T_17 = replayMeta_cmd == 5'hF;	// src/main/scala/gpcdcache/MSHR.scala:168:29, src/main/scala/util/package.scala:16:47
      _state_T_17 = state == 3'h4;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :158:15, :172:47
      _state_T_11 = state == 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :166:41, :172:47
      if (initEnable) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35
        replayReg <= io_innerIO_bits_data;	// src/main/scala/gpcdcache/MSHR.scala:149:34
        totalCounter <= io_innerIO_bits_counter;	// src/main/scala/gpcdcache/MSHR.scala:162:33
        replayLineAddr <= io_innerIO_bits_lineAddr;	// src/main/scala/gpcdcache/MSHR.scala:163:33
        replayPerm <= io_innerIO_bits_perm;	// src/main/scala/gpcdcache/MSHR.scala:164:33
      end
      else if (_replayReg_T
               & (_replayReg_T_1 | _replayReg_T_2 | _replayReg_T_4 | _replayReg_T_6
                  | _replayReg_T_7 | _replayReg_T_8 | _replayReg_T_9 | _replayReg_T_13
                  | _replayReg_T_14 | _replayReg_T_15 | _replayReg_T_16
                  | _replayReg_T_17))	// src/main/scala/gpcdcache/MSHR.scala:166:41, :210:32, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72,82}, src/main/scala/util/package.scala:16:47
        replayReg <= {replayReg_hi, replayReg_lo};	// src/main/scala/gpcdcache/MSHR.scala:149:34, :195:9
      if (_state_T_17)	// src/main/scala/gpcdcache/MSHR.scala:172:47
        state <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104
      else if (state == 3'h3) begin	// src/main/scala/gpcdcache/MSHR.scala:152:104, :215:35, :219:31
        if (io_replaceStatus == 2'h1)	// src/main/scala/gpcdcache/MSHR.scala:164:33, :221:26
          state <= 3'h4;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :158:15
        else if (io_replaceStatus == 2'h2)	// src/main/scala/gpcdcache/AMOALU.scala:67:16, src/main/scala/gpcdcache/MSHR.scala:223:30
          state <= 3'h2;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :218:31
      end
      else if (state == 3'h2) begin	// src/main/scala/gpcdcache/MSHR.scala:152:104, :215:35, :218:31
        if (io_toReplace_ready)	// src/main/scala/gpcdcache/MSHR.scala:147:14
          state <= 3'h3;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :219:31
      end
      else if (_state_T_11) begin	// src/main/scala/gpcdcache/MSHR.scala:172:47
        if (metaCounter >= totalCounter)	// src/main/scala/gpcdcache/MSHR.scala:154:28, :162:33, :218:44
          state <= 3'h2;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :218:31
      end
      else if (~(|state) & initEnable)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/MSHR.scala:152:104, :215:35, :217:31
        state <= 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :166:41
      if (_metaCounter_T)	// src/main/scala/gpcdcache/MSHR.scala:158:15
        metaCounter <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :154:28
      else if (underReplay)	// src/main/scala/gpcdcache/MSHR.scala:166:32
        metaCounter <= metaCounter + 3'h1;	// src/main/scala/gpcdcache/MSHR.scala:154:28, :166:41, :202:46
      if (initEnable | _metaCounter_T) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/MSHR.scala:158:15, :160:16
        if (_metaCounter_T)	// src/main/scala/gpcdcache/MSHR.scala:158:15
          mshrEntryIdx <= 3'h0;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :157:31
        else	// src/main/scala/gpcdcache/MSHR.scala:158:15
          mshrEntryIdx <= io_innerIO_bits_entryIdx;	// src/main/scala/gpcdcache/MSHR.scala:157:31
      end
      if (_state_T_11)	// src/main/scala/gpcdcache/MSHR.scala:172:47
        writeRecord <=
          writeRecord | _replayReg_T_1 | _replayReg_T_2 | _replayReg_T_4 | _replayReg_T_6
          | _replayReg_T_7 | _replayReg_T_8 | _replayReg_T_9 | _replayReg_T_13
          | _replayReg_T_14 | _replayReg_T_15 | _replayReg_T_16 | _replayReg_T_17;	// src/main/scala/gpcdcache/MSHR.scala:170:28, :175:35, src/main/scala/gpcdcache/MemConstants.scala:45:{38,55,72}, src/main/scala/util/package.scala:16:47
      else	// src/main/scala/gpcdcache/MSHR.scala:172:47
        writeRecord <= ~_state_T_17 & writeRecord;	// src/main/scala/gpcdcache/MSHR.scala:170:28, :172:47
    end
    if (underReplay) begin	// src/main/scala/gpcdcache/MSHR.scala:166:32
      replayMeta_sourceId <= io_innerIO_bits_meta_sourceId;	// src/main/scala/gpcdcache/MSHR.scala:168:29
      replayMeta_regIdx <= io_innerIO_bits_meta_regIdx;	// src/main/scala/gpcdcache/MSHR.scala:168:29
      replayMeta_size <= io_innerIO_bits_meta_size;	// src/main/scala/gpcdcache/MSHR.scala:168:29
      replayMeta_signed <= io_innerIO_bits_meta_signed;	// src/main/scala/gpcdcache/MSHR.scala:168:29
      replayMeta_offset <= io_innerIO_bits_meta_offset;	// src/main/scala/gpcdcache/MSHR.scala:168:29
      replayMeta_cmd <= io_innerIO_bits_meta_cmd;	// src/main/scala/gpcdcache/MSHR.scala:168:29
    end
    io_toPipe_valid_REG <= _io_toPipe_bits_nextCycleWb_output;	// src/main/scala/gpcdcache/MSHR.scala:252:6, :254:37
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:18];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        replayReg =
          {_RANDOM[5'h0],
           _RANDOM[5'h1],
           _RANDOM[5'h2],
           _RANDOM[5'h3],
           _RANDOM[5'h4],
           _RANDOM[5'h5],
           _RANDOM[5'h6],
           _RANDOM[5'h7],
           _RANDOM[5'h8],
           _RANDOM[5'h9],
           _RANDOM[5'hA],
           _RANDOM[5'hB],
           _RANDOM[5'hC],
           _RANDOM[5'hD],
           _RANDOM[5'hE],
           _RANDOM[5'hF]};	// src/main/scala/gpcdcache/MSHR.scala:149:34
        state = _RANDOM[5'h10][2:0];	// src/main/scala/gpcdcache/MSHR.scala:152:104
        metaCounter = _RANDOM[5'h10][5:3];	// src/main/scala/gpcdcache/MSHR.scala:152:104, :154:28
        mshrEntryIdx = _RANDOM[5'h10][8:6];	// src/main/scala/gpcdcache/MSHR.scala:152:104, :157:31
        totalCounter = _RANDOM[5'h10][11:9];	// src/main/scala/gpcdcache/MSHR.scala:152:104, :162:33
        replayLineAddr = {_RANDOM[5'h10][31:12], _RANDOM[5'h11][12:0]};	// src/main/scala/gpcdcache/MSHR.scala:152:104, :163:33
        replayPerm = _RANDOM[5'h11][14:13];	// src/main/scala/gpcdcache/MSHR.scala:163:33, :164:33
        replayMeta_sourceId = _RANDOM[5'h11][16:15];	// src/main/scala/gpcdcache/MSHR.scala:163:33, :168:29
        replayMeta_regIdx = _RANDOM[5'h11][21:17];	// src/main/scala/gpcdcache/MSHR.scala:163:33, :168:29
        replayMeta_size = _RANDOM[5'h11][24:22];	// src/main/scala/gpcdcache/MSHR.scala:163:33, :168:29
        replayMeta_signed = _RANDOM[5'h11][25];	// src/main/scala/gpcdcache/MSHR.scala:163:33, :168:29
        replayMeta_offset = _RANDOM[5'h11][31:26];	// src/main/scala/gpcdcache/MSHR.scala:163:33, :168:29
        replayMeta_cmd = _RANDOM[5'h12][4:0];	// src/main/scala/gpcdcache/MSHR.scala:168:29
        writeRecord = _RANDOM[5'h12][5];	// src/main/scala/gpcdcache/MSHR.scala:168:29, :170:28
        io_toPipe_valid_REG = _RANDOM[5'h12][6];	// src/main/scala/gpcdcache/MSHR.scala:168:29, :254:37
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_toPipe_valid = io_toPipe_valid_REG;	// src/main/scala/gpcdcache/MSHR.scala:254:37
  assign io_toPipe_bits_sourceId = replayMeta_sourceId;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  assign io_toPipe_bits_regIdx = replayMeta_regIdx;	// src/main/scala/gpcdcache/MSHR.scala:168:29
  assign io_toPipe_bits_regData = loadgen;	// src/main/scala/gpcdcache/AMOALU.scala:65:16
  assign io_toPipe_bits_nextCycleWb = _io_toPipe_bits_nextCycleWb_output;	// src/main/scala/gpcdcache/MSHR.scala:252:6
  assign io_toReplace_valid = state == 3'h2;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :218:31, :235:31
  assign io_toReplace_bits_state = replayPerm == 2'h0 ? {1'h1, writeRecord} : 2'h1;	// src/main/scala/gpcdcache/MSHR.scala:164:33, :170:28, :237:72, :240:31, src/main/scala/gpcdcache/MemConstants.scala:45:{38,72}
  assign io_toReplace_bits_lineAddr = replayLineAddr;	// src/main/scala/gpcdcache/MSHR.scala:163:33
  assign io_toReplace_bits_data = replayReg;	// src/main/scala/gpcdcache/MSHR.scala:149:34
  assign io_innerIO_ready = ~(|state);	// src/main/scala/gpcdcache/MSHR.scala:152:104, :215:35, :230:29
  assign io_idxMeta = metaCounter;	// src/main/scala/gpcdcache/MSHR.scala:154:28
  assign io_replayIdx = (|state) ? mshrEntryIdx : io_innerIO_bits_entryIdx;	// src/main/scala/gpcdcache/MSHR.scala:152:104, :157:31, :215:35, :232:26
endmodule

