// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module TilePRCIDomain(
  input         auto_intsink_in_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_element_reset_domain_gpctile_hartid_in,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_int_in_clock_xing_in_2_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_int_in_clock_xing_in_1_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_int_in_clock_xing_in_0_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_int_in_clock_xing_in_0_sync_1,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_b_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_tl_master_clock_xing_out_b_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [31:0] auto_tl_master_clock_xing_out_b_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_tl_master_clock_xing_out_c_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [2:0]  auto_tl_master_clock_xing_out_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_tl_master_clock_xing_out_d_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [3:0]  auto_tl_master_clock_xing_out_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [5:0]  auto_tl_master_clock_xing_out_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_tl_master_clock_xing_out_d_bits_sink,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_tl_master_clock_xing_out_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [63:0] auto_tl_master_clock_xing_out_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_tl_master_clock_xing_out_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tap_clock_in_clock,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tap_clock_in_reset,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_intsink_out_2_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_intsink_out_1_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_intsink_out_0_0,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_tl_master_clock_xing_out_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [3:0]  auto_tl_master_clock_xing_out_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [5:0]  auto_tl_master_clock_xing_out_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [31:0] auto_tl_master_clock_xing_out_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [7:0]  auto_tl_master_clock_xing_out_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_tl_master_clock_xing_out_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_tl_master_clock_xing_out_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_b_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_c_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_tl_master_clock_xing_out_c_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_c_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [3:0]  auto_tl_master_clock_xing_out_c_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [5:0]  auto_tl_master_clock_xing_out_c_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [31:0] auto_tl_master_clock_xing_out_c_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_tl_master_clock_xing_out_c_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_tl_master_clock_xing_out_c_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_tl_master_clock_xing_out_e_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [1:0]  auto_tl_master_clock_xing_out_e_bits_sink	// src/main/scala/diplomacy/LazyModule.scala:367:18
);

  wire        _intsink_3_auto_out_0;	// src/main/scala/interrupts/Crossing.scala:101:29
  wire        _intsink_2_auto_out_0;	// src/main/scala/interrupts/Crossing.scala:101:29
  wire        _intsink_1_auto_out_0;	// src/main/scala/interrupts/Crossing.scala:101:29
  wire        _intsink_1_auto_out_1;	// src/main/scala/interrupts/Crossing.scala:101:29
  wire        _intsink_auto_out_0;	// src/main/scala/interrupts/Crossing.scala:80:29
  wire        _buffer_auto_in_a_ready;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_b_valid;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [2:0]  _buffer_auto_in_b_bits_opcode;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [1:0]  _buffer_auto_in_b_bits_param;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [3:0]  _buffer_auto_in_b_bits_size;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [5:0]  _buffer_auto_in_b_bits_source;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [31:0] _buffer_auto_in_b_bits_address;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [7:0]  _buffer_auto_in_b_bits_mask;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [63:0] _buffer_auto_in_b_bits_data;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_b_bits_corrupt;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_c_ready;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_d_valid;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [2:0]  _buffer_auto_in_d_bits_opcode;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [1:0]  _buffer_auto_in_d_bits_param;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [3:0]  _buffer_auto_in_d_bits_size;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [5:0]  _buffer_auto_in_d_bits_source;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [1:0]  _buffer_auto_in_d_bits_sink;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_d_bits_denied;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire [63:0] _buffer_auto_in_d_bits_data;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_d_bits_corrupt;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _buffer_auto_in_e_ready;	// src/main/scala/tilelink/Buffer.scala:69:28
  wire        _element_reset_domain_gpctile_auto_buffer_out_a_valid;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [2:0]  _element_reset_domain_gpctile_auto_buffer_out_a_bits_opcode;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [2:0]  _element_reset_domain_gpctile_auto_buffer_out_a_bits_param;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [3:0]  _element_reset_domain_gpctile_auto_buffer_out_a_bits_size;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [5:0]  _element_reset_domain_gpctile_auto_buffer_out_a_bits_source;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [31:0] _element_reset_domain_gpctile_auto_buffer_out_a_bits_address;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [7:0]  _element_reset_domain_gpctile_auto_buffer_out_a_bits_mask;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [63:0] _element_reset_domain_gpctile_auto_buffer_out_a_bits_data;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_buffer_out_a_bits_corrupt;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_buffer_out_b_ready;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_buffer_out_c_valid;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [2:0]  _element_reset_domain_gpctile_auto_buffer_out_c_bits_opcode;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [2:0]  _element_reset_domain_gpctile_auto_buffer_out_c_bits_param;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [3:0]  _element_reset_domain_gpctile_auto_buffer_out_c_bits_size;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [5:0]  _element_reset_domain_gpctile_auto_buffer_out_c_bits_source;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [31:0] _element_reset_domain_gpctile_auto_buffer_out_c_bits_address;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [63:0] _element_reset_domain_gpctile_auto_buffer_out_c_bits_data;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_buffer_out_c_bits_corrupt;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_buffer_out_d_ready;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_buffer_out_e_valid;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire [1:0]  _element_reset_domain_gpctile_auto_buffer_out_e_bits_sink;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        _element_reset_domain_gpctile_auto_wfi_out_0;	// src/main/scala/subsystem/HasTiles.scala:161:59
  wire        tapClockNodeIn_clock = auto_tap_clock_in_clock;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tapClockNodeIn_reset = auto_tap_clock_in_reset;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingOut_a_ready = auto_tl_master_clock_xing_out_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        tlMasterClockXingOut_b_valid = auto_tl_master_clock_xing_out_b_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [1:0]  tlMasterClockXingOut_b_bits_param =
    auto_tl_master_clock_xing_out_b_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [31:0] tlMasterClockXingOut_b_bits_address =
    auto_tl_master_clock_xing_out_b_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        tlMasterClockXingOut_c_ready = auto_tl_master_clock_xing_out_c_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        tlMasterClockXingOut_d_valid = auto_tl_master_clock_xing_out_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [2:0]  tlMasterClockXingOut_d_bits_opcode =
    auto_tl_master_clock_xing_out_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [1:0]  tlMasterClockXingOut_d_bits_param =
    auto_tl_master_clock_xing_out_d_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [3:0]  tlMasterClockXingOut_d_bits_size =
    auto_tl_master_clock_xing_out_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [5:0]  tlMasterClockXingOut_d_bits_source =
    auto_tl_master_clock_xing_out_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [1:0]  tlMasterClockXingOut_d_bits_sink =
    auto_tl_master_clock_xing_out_d_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        tlMasterClockXingOut_d_bits_denied =
    auto_tl_master_clock_xing_out_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [63:0] tlMasterClockXingOut_d_bits_data =
    auto_tl_master_clock_xing_out_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        tlMasterClockXingOut_d_bits_corrupt =
    auto_tl_master_clock_xing_out_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        intInClockXingIn_sync_0 = auto_int_in_clock_xing_in_0_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        intInClockXingIn_sync_1 = auto_int_in_clock_xing_in_0_sync_1;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        intInClockXingIn_1_sync_0 = auto_int_in_clock_xing_in_1_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        intInClockXingIn_2_sync_0 = auto_int_in_clock_xing_in_2_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        clockNode_childClock = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:412:31, :416:25
  wire        clockNode_childReset = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:414:31, :416:25
  wire        tlMasterClockXingOut_b_bits_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:416:25, src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        tlMasterClockXingIn_b_bits_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:416:25, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingOut_e_ready = 1'h1;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire        tlMasterClockXingIn_e_ready = 1'h1;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [7:0]  tlMasterClockXingOut_b_bits_mask = 8'hFF;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [7:0]  tlMasterClockXingIn_b_bits_mask = 8'hFF;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [5:0]  tlMasterClockXingOut_b_bits_source = 6'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [5:0]  tlMasterClockXingIn_b_bits_source = 6'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [3:0]  tlMasterClockXingOut_b_bits_size = 4'h6;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [3:0]  tlMasterClockXingIn_b_bits_size = 4'h6;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [2:0]  tlMasterClockXingOut_b_bits_opcode = 3'h6;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [2:0]  tlMasterClockXingIn_b_bits_opcode = 3'h6;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/Buffer.scala:69:28
  wire [63:0] tlMasterClockXingOut_b_bits_data = 64'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/subsystem/HasTiles.scala:161:59, src/main/scala/tilelink/Buffer.scala:69:28
  wire [63:0] tlMasterClockXingIn_b_bits_data = 64'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/subsystem/HasTiles.scala:161:59, src/main/scala/tilelink/Buffer.scala:69:28
  wire        element_reset_domain_clockNodeIn_clock;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        element_reset_domain_clockNodeIn_reset;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        clockNode_nodeOut_clock;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        element_reset_domain_childClock = element_reset_domain_clockNodeIn_clock;	// src/main/scala/diplomacy/LazyModule.scala:412:31, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        clockNode_nodeOut_reset;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        element_reset_domain_childReset = element_reset_domain_clockNodeIn_reset;	// src/main/scala/diplomacy/LazyModule.scala:414:31, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        clockNode_nodeIn_clock;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign element_reset_domain_clockNodeIn_clock = clockNode_nodeOut_clock;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        clockNode_nodeIn_reset;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign element_reset_domain_clockNodeIn_reset = clockNode_nodeOut_reset;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tapClockNodeOut_clock;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign clockNode_nodeOut_clock = clockNode_nodeIn_clock;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tapClockNodeOut_reset;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign clockNode_nodeOut_reset = clockNode_nodeIn_reset;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  assign clockNode_nodeIn_clock = tapClockNodeOut_clock;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  assign clockNode_nodeIn_reset = tapClockNodeOut_reset;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        childClock = tapClockNodeIn_clock;	// src/main/scala/diplomacy/LazyModule.scala:412:31, src/main/scala/diplomacy/Nodes.scala:1214:17
  assign tapClockNodeOut_clock = tapClockNodeIn_clock;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        childReset = tapClockNodeIn_reset;	// src/main/scala/diplomacy/LazyModule.scala:414:31, src/main/scala/diplomacy/Nodes.scala:1214:17
  assign tapClockNodeOut_reset = tapClockNodeIn_reset;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_a_ready = tlMasterClockXingOut_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]  tlMasterClockXingIn_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]  tlMasterClockXingIn_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [3:0]  tlMasterClockXingIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [5:0]  tlMasterClockXingIn_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [31:0] tlMasterClockXingIn_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [7:0]  tlMasterClockXingIn_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0] tlMasterClockXingIn_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingIn_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingIn_b_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingIn_b_valid = tlMasterClockXingOut_b_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [1:0]  tlMasterClockXingIn_b_bits_param = tlMasterClockXingOut_b_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [31:0] tlMasterClockXingIn_b_bits_address = tlMasterClockXingOut_b_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_c_ready = tlMasterClockXingOut_c_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_c_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]  tlMasterClockXingIn_c_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]  tlMasterClockXingIn_c_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [3:0]  tlMasterClockXingIn_c_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [5:0]  tlMasterClockXingIn_c_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [31:0] tlMasterClockXingIn_c_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0] tlMasterClockXingIn_c_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingIn_c_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingIn_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingIn_d_valid = tlMasterClockXingOut_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]  tlMasterClockXingIn_d_bits_opcode = tlMasterClockXingOut_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [1:0]  tlMasterClockXingIn_d_bits_param = tlMasterClockXingOut_d_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [3:0]  tlMasterClockXingIn_d_bits_size = tlMasterClockXingOut_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [5:0]  tlMasterClockXingIn_d_bits_source = tlMasterClockXingOut_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [1:0]  tlMasterClockXingIn_d_bits_sink = tlMasterClockXingOut_d_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_d_bits_denied = tlMasterClockXingOut_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [63:0] tlMasterClockXingIn_d_bits_data = tlMasterClockXingOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_d_bits_corrupt = tlMasterClockXingOut_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingIn_e_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]  tlMasterClockXingIn_e_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        tlMasterClockXingOut_a_valid = tlMasterClockXingIn_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]  tlMasterClockXingOut_a_bits_opcode = tlMasterClockXingIn_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]  tlMasterClockXingOut_a_bits_param = tlMasterClockXingIn_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [3:0]  tlMasterClockXingOut_a_bits_size = tlMasterClockXingIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [5:0]  tlMasterClockXingOut_a_bits_source = tlMasterClockXingIn_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [31:0] tlMasterClockXingOut_a_bits_address = tlMasterClockXingIn_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [7:0]  tlMasterClockXingOut_a_bits_mask = tlMasterClockXingIn_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [63:0] tlMasterClockXingOut_a_bits_data = tlMasterClockXingIn_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingOut_a_bits_corrupt = tlMasterClockXingIn_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingOut_b_ready = tlMasterClockXingIn_b_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingOut_c_valid = tlMasterClockXingIn_c_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]  tlMasterClockXingOut_c_bits_opcode = tlMasterClockXingIn_c_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]  tlMasterClockXingOut_c_bits_param = tlMasterClockXingIn_c_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [3:0]  tlMasterClockXingOut_c_bits_size = tlMasterClockXingIn_c_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [5:0]  tlMasterClockXingOut_c_bits_source = tlMasterClockXingIn_c_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [31:0] tlMasterClockXingOut_c_bits_address = tlMasterClockXingIn_c_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [63:0] tlMasterClockXingOut_c_bits_data = tlMasterClockXingIn_c_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingOut_c_bits_corrupt = tlMasterClockXingIn_c_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingOut_d_ready = tlMasterClockXingIn_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        tlMasterClockXingOut_e_valid = tlMasterClockXingIn_e_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [1:0]  tlMasterClockXingOut_e_bits_sink = tlMasterClockXingIn_e_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intInClockXingOut_sync_0 = intInClockXingIn_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intInClockXingOut_sync_1 = intInClockXingIn_sync_1;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intInClockXingOut_1_sync_0 = intInClockXingIn_1_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intInClockXingOut_2_sync_0 = intInClockXingIn_2_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intOutClockXingIn_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        intOutClockXingOut_1_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        intOutClockXingOut_sync_0 = intOutClockXingIn_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intOutClockXingIn_1_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign intOutClockXingIn_sync_0 = intOutClockXingOut_1_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  assign intOutClockXingOut_1_sync_0 = intOutClockXingIn_1_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intOutClockXingIn_2_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        intOutClockXingOut_3_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        intOutClockXingOut_2_sync_0 = intOutClockXingIn_2_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intOutClockXingIn_3_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign intOutClockXingIn_2_sync_0 = intOutClockXingOut_3_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  assign intOutClockXingOut_3_sync_0 = intOutClockXingIn_3_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intOutClockXingIn_4_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        intOutClockXingOut_5_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire        intOutClockXingOut_4_sync_0 = intOutClockXingIn_4_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire        intOutClockXingIn_5_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign intOutClockXingIn_4_sync_0 = intOutClockXingOut_5_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  assign intOutClockXingOut_5_sync_0 = intOutClockXingIn_5_sync_0;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  GpcTile element_reset_domain_gpctile (	// src/main/scala/subsystem/HasTiles.scala:161:59
    .clock                          (element_reset_domain_childClock),	// src/main/scala/diplomacy/LazyModule.scala:412:31
    .reset                          (element_reset_domain_childReset),	// src/main/scala/diplomacy/LazyModule.scala:414:31
    .auto_buffer_out_a_ready        (_buffer_auto_in_a_ready),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_valid        (_buffer_auto_in_b_valid),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_opcode  (_buffer_auto_in_b_bits_opcode),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_param   (_buffer_auto_in_b_bits_param),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_size    (_buffer_auto_in_b_bits_size),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_source  (_buffer_auto_in_b_bits_source),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_address (_buffer_auto_in_b_bits_address),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_mask    (_buffer_auto_in_b_bits_mask),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_data    (_buffer_auto_in_b_bits_data),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_b_bits_corrupt (_buffer_auto_in_b_bits_corrupt),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_c_ready        (_buffer_auto_in_c_ready),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_valid        (_buffer_auto_in_d_valid),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_opcode  (_buffer_auto_in_d_bits_opcode),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_param   (_buffer_auto_in_d_bits_param),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_size    (_buffer_auto_in_d_bits_size),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_source  (_buffer_auto_in_d_bits_source),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_sink    (_buffer_auto_in_d_bits_sink),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_denied  (_buffer_auto_in_d_bits_denied),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_data    (_buffer_auto_in_d_bits_data),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_d_bits_corrupt (_buffer_auto_in_d_bits_corrupt),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_buffer_out_e_ready        (_buffer_auto_in_e_ready),	// src/main/scala/tilelink/Buffer.scala:69:28
    .auto_int_local_in_3_0          (_intsink_3_auto_out_0),	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_int_local_in_2_0          (_intsink_2_auto_out_0),	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_int_local_in_1_0          (_intsink_1_auto_out_0),	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_int_local_in_1_1          (_intsink_1_auto_out_1),	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_int_local_in_0_0          (_intsink_auto_out_0),	// src/main/scala/interrupts/Crossing.scala:80:29
    .auto_hartid_in                 (auto_element_reset_domain_gpctile_hartid_in),
    .auto_buffer_out_a_valid
      (_element_reset_domain_gpctile_auto_buffer_out_a_valid),
    .auto_buffer_out_a_bits_opcode
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_opcode),
    .auto_buffer_out_a_bits_param
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_param),
    .auto_buffer_out_a_bits_size
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_size),
    .auto_buffer_out_a_bits_source
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_source),
    .auto_buffer_out_a_bits_address
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_address),
    .auto_buffer_out_a_bits_mask
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_mask),
    .auto_buffer_out_a_bits_data
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_data),
    .auto_buffer_out_a_bits_corrupt
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_corrupt),
    .auto_buffer_out_b_ready
      (_element_reset_domain_gpctile_auto_buffer_out_b_ready),
    .auto_buffer_out_c_valid
      (_element_reset_domain_gpctile_auto_buffer_out_c_valid),
    .auto_buffer_out_c_bits_opcode
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_opcode),
    .auto_buffer_out_c_bits_param
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_param),
    .auto_buffer_out_c_bits_size
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_size),
    .auto_buffer_out_c_bits_source
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_source),
    .auto_buffer_out_c_bits_address
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_address),
    .auto_buffer_out_c_bits_data
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_data),
    .auto_buffer_out_c_bits_corrupt
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_corrupt),
    .auto_buffer_out_d_ready
      (_element_reset_domain_gpctile_auto_buffer_out_d_ready),
    .auto_buffer_out_e_valid
      (_element_reset_domain_gpctile_auto_buffer_out_e_valid),
    .auto_buffer_out_e_bits_sink
      (_element_reset_domain_gpctile_auto_buffer_out_e_bits_sink),
    .auto_wfi_out_0                 (_element_reset_domain_gpctile_auto_wfi_out_0)
  );
  TLBuffer_10 buffer (	// src/main/scala/tilelink/Buffer.scala:69:28
    .clock                   (childClock),	// src/main/scala/diplomacy/LazyModule.scala:412:31
    .reset                   (childReset),	// src/main/scala/diplomacy/LazyModule.scala:414:31
    .auto_in_a_valid         (_element_reset_domain_gpctile_auto_buffer_out_a_valid),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_opcode
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_opcode),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_param    (_element_reset_domain_gpctile_auto_buffer_out_a_bits_param),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_size     (_element_reset_domain_gpctile_auto_buffer_out_a_bits_size),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_source
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_source),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_address
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_address),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_mask     (_element_reset_domain_gpctile_auto_buffer_out_a_bits_mask),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_data     (_element_reset_domain_gpctile_auto_buffer_out_a_bits_data),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_a_bits_corrupt
      (_element_reset_domain_gpctile_auto_buffer_out_a_bits_corrupt),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_b_ready         (_element_reset_domain_gpctile_auto_buffer_out_b_ready),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_valid         (_element_reset_domain_gpctile_auto_buffer_out_c_valid),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_opcode
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_opcode),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_param    (_element_reset_domain_gpctile_auto_buffer_out_c_bits_param),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_size     (_element_reset_domain_gpctile_auto_buffer_out_c_bits_size),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_source
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_source),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_address
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_address),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_data     (_element_reset_domain_gpctile_auto_buffer_out_c_bits_data),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_c_bits_corrupt
      (_element_reset_domain_gpctile_auto_buffer_out_c_bits_corrupt),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_d_ready         (_element_reset_domain_gpctile_auto_buffer_out_d_ready),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_e_valid         (_element_reset_domain_gpctile_auto_buffer_out_e_valid),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_in_e_bits_sink     (_element_reset_domain_gpctile_auto_buffer_out_e_bits_sink),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_out_a_ready        (tlMasterClockXingIn_a_ready),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_b_valid        (tlMasterClockXingIn_b_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_b_bits_param   (tlMasterClockXingIn_b_bits_param),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_b_bits_address (tlMasterClockXingIn_b_bits_address),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_c_ready        (tlMasterClockXingIn_c_ready),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_valid        (tlMasterClockXingIn_d_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_opcode  (tlMasterClockXingIn_d_bits_opcode),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_param   (tlMasterClockXingIn_d_bits_param),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_size    (tlMasterClockXingIn_d_bits_size),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_source  (tlMasterClockXingIn_d_bits_source),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_sink    (tlMasterClockXingIn_d_bits_sink),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_denied  (tlMasterClockXingIn_d_bits_denied),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_data    (tlMasterClockXingIn_d_bits_data),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_out_d_bits_corrupt (tlMasterClockXingIn_d_bits_corrupt),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_b_valid         (_buffer_auto_in_b_valid),
    .auto_in_b_bits_opcode   (_buffer_auto_in_b_bits_opcode),
    .auto_in_b_bits_param    (_buffer_auto_in_b_bits_param),
    .auto_in_b_bits_size     (_buffer_auto_in_b_bits_size),
    .auto_in_b_bits_source   (_buffer_auto_in_b_bits_source),
    .auto_in_b_bits_address  (_buffer_auto_in_b_bits_address),
    .auto_in_b_bits_mask     (_buffer_auto_in_b_bits_mask),
    .auto_in_b_bits_data     (_buffer_auto_in_b_bits_data),
    .auto_in_b_bits_corrupt  (_buffer_auto_in_b_bits_corrupt),
    .auto_in_c_ready         (_buffer_auto_in_c_ready),
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_in_e_ready         (_buffer_auto_in_e_ready),
    .auto_out_a_valid        (tlMasterClockXingIn_a_valid),
    .auto_out_a_bits_opcode  (tlMasterClockXingIn_a_bits_opcode),
    .auto_out_a_bits_param   (tlMasterClockXingIn_a_bits_param),
    .auto_out_a_bits_size    (tlMasterClockXingIn_a_bits_size),
    .auto_out_a_bits_source  (tlMasterClockXingIn_a_bits_source),
    .auto_out_a_bits_address (tlMasterClockXingIn_a_bits_address),
    .auto_out_a_bits_mask    (tlMasterClockXingIn_a_bits_mask),
    .auto_out_a_bits_data    (tlMasterClockXingIn_a_bits_data),
    .auto_out_a_bits_corrupt (tlMasterClockXingIn_a_bits_corrupt),
    .auto_out_b_ready        (tlMasterClockXingIn_b_ready),
    .auto_out_c_valid        (tlMasterClockXingIn_c_valid),
    .auto_out_c_bits_opcode  (tlMasterClockXingIn_c_bits_opcode),
    .auto_out_c_bits_param   (tlMasterClockXingIn_c_bits_param),
    .auto_out_c_bits_size    (tlMasterClockXingIn_c_bits_size),
    .auto_out_c_bits_source  (tlMasterClockXingIn_c_bits_source),
    .auto_out_c_bits_address (tlMasterClockXingIn_c_bits_address),
    .auto_out_c_bits_data    (tlMasterClockXingIn_c_bits_data),
    .auto_out_c_bits_corrupt (tlMasterClockXingIn_c_bits_corrupt),
    .auto_out_d_ready        (tlMasterClockXingIn_d_ready),
    .auto_out_e_valid        (tlMasterClockXingIn_e_valid),
    .auto_out_e_bits_sink    (tlMasterClockXingIn_e_bits_sink)
  );
  IntSyncAsyncCrossingSink_1 intsink (	// src/main/scala/interrupts/Crossing.scala:80:29
    .clock          (childClock),	// src/main/scala/diplomacy/LazyModule.scala:412:31
    .auto_in_sync_0 (auto_intsink_in_sync_0),
    .auto_out_0     (_intsink_auto_out_0)
  );
  IntSyncSyncCrossingSink intsink_1 (	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_in_sync_0 (intInClockXingOut_sync_0),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_in_sync_1 (intInClockXingOut_sync_1),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_out_0     (_intsink_1_auto_out_0),
    .auto_out_1     (_intsink_1_auto_out_1)
  );
  IntSyncSyncCrossingSink_1 intsink_2 (	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_in_sync_0 (intInClockXingOut_1_sync_0),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_out_0     (_intsink_2_auto_out_0)
  );
  IntSyncSyncCrossingSink_1 intsink_3 (	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_in_sync_0 (intInClockXingOut_2_sync_0),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_out_0     (_intsink_3_auto_out_0)
  );
  IntSyncSyncCrossingSink_1 intsink_4 (	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_in_sync_0 (intOutClockXingOut_sync_0),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_out_0     (auto_intsink_out_0_0)
  );
  IntSyncCrossingSource_1 intsource (	// src/main/scala/interrupts/Crossing.scala:28:31
    .clock           (childClock),	// src/main/scala/diplomacy/LazyModule.scala:412:31
    .reset           (childReset),	// src/main/scala/diplomacy/LazyModule.scala:414:31
    .auto_in_0       (1'h0),	// src/main/scala/diplomacy/LazyModule.scala:416:25
    .auto_out_sync_0 (intOutClockXingIn_1_sync_0)
  );
  IntSyncSyncCrossingSink_1 intsink_5 (	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_in_sync_0 (intOutClockXingOut_2_sync_0),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_out_0     (auto_intsink_out_1_0)
  );
  IntSyncCrossingSource_1 intsource_1 (	// src/main/scala/interrupts/Crossing.scala:28:31
    .clock           (childClock),	// src/main/scala/diplomacy/LazyModule.scala:412:31
    .reset           (childReset),	// src/main/scala/diplomacy/LazyModule.scala:414:31
    .auto_in_0       (_element_reset_domain_gpctile_auto_wfi_out_0),	// src/main/scala/subsystem/HasTiles.scala:161:59
    .auto_out_sync_0 (intOutClockXingIn_3_sync_0)
  );
  IntSyncSyncCrossingSink_1 intsink_6 (	// src/main/scala/interrupts/Crossing.scala:101:29
    .auto_in_sync_0 (intOutClockXingOut_4_sync_0),	// src/main/scala/diplomacy/Nodes.scala:1205:17
    .auto_out_0     (auto_intsink_out_2_0)
  );
  IntSyncCrossingSource_1 intsource_2 (	// src/main/scala/interrupts/Crossing.scala:28:31
    .clock           (childClock),	// src/main/scala/diplomacy/LazyModule.scala:412:31
    .reset           (childReset),	// src/main/scala/diplomacy/LazyModule.scala:414:31
    .auto_in_0       (1'h0),	// src/main/scala/diplomacy/LazyModule.scala:416:25
    .auto_out_sync_0 (intOutClockXingIn_5_sync_0)
  );
  assign auto_tl_master_clock_xing_out_a_valid = tlMasterClockXingOut_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_opcode = tlMasterClockXingOut_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_param = tlMasterClockXingOut_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_size = tlMasterClockXingOut_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_source = tlMasterClockXingOut_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_address =
    tlMasterClockXingOut_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_mask = tlMasterClockXingOut_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_data = tlMasterClockXingOut_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_a_bits_corrupt =
    tlMasterClockXingOut_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_b_ready = tlMasterClockXingOut_b_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_valid = tlMasterClockXingOut_c_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_opcode = tlMasterClockXingOut_c_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_param = tlMasterClockXingOut_c_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_size = tlMasterClockXingOut_c_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_source = tlMasterClockXingOut_c_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_address =
    tlMasterClockXingOut_c_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_data = tlMasterClockXingOut_c_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_c_bits_corrupt =
    tlMasterClockXingOut_c_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_d_ready = tlMasterClockXingOut_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_e_valid = tlMasterClockXingOut_e_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_tl_master_clock_xing_out_e_bits_sink = tlMasterClockXingOut_e_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1205:17
endmodule

