// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module TLFIFOFixer_3(
  input         clock,
                reset,
                auto_in_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [2:0]  auto_in_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_in_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [3:0]  auto_in_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [6:0]  auto_in_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [27:0] auto_in_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [7:0]  auto_in_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [63:0] auto_in_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_in_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_in_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_out_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_out_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [2:0]  auto_out_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_out_d_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [3:0]  auto_out_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [6:0]  auto_out_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_out_d_bits_sink,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_out_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [63:0] auto_out_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_out_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_in_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_in_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_in_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [1:0]  auto_in_d_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [3:0]  auto_in_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [6:0]  auto_in_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_in_d_bits_sink,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_in_d_bits_denied,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_in_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_in_d_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_out_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_out_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_out_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [3:0]  auto_out_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [6:0]  auto_out_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [27:0] auto_out_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [7:0]  auto_out_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_out_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_out_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_out_d_ready	// src/main/scala/diplomacy/LazyModule.scala:367:18
);

  wire         nodeIn_a_valid = auto_in_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]   nodeIn_a_bits_opcode = auto_in_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]   nodeIn_a_bits_param = auto_in_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [3:0]   nodeIn_a_bits_size = auto_in_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [6:0]   nodeIn_a_bits_source = auto_in_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [27:0]  nodeIn_a_bits_address = auto_in_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [7:0]   nodeIn_a_bits_mask = auto_in_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0]  nodeIn_a_bits_data = auto_in_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire         nodeIn_a_bits_corrupt = auto_in_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire         nodeIn_d_ready = auto_in_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire         nodeOut_a_ready = auto_out_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire         nodeOut_d_valid = auto_out_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [2:0]   nodeOut_d_bits_opcode = auto_out_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [1:0]   nodeOut_d_bits_param = auto_out_d_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [3:0]   nodeOut_d_bits_size = auto_out_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [6:0]   nodeOut_d_bits_source = auto_out_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire         nodeOut_d_bits_sink = auto_out_d_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire         nodeOut_d_bits_denied = auto_out_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [63:0]  nodeOut_d_bits_data = auto_out_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire         nodeOut_d_bits_corrupt = auto_out_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [2:0]   nodeOut_a_bits_opcode = nodeIn_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]   nodeOut_a_bits_param = nodeIn_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [3:0]   nodeOut_a_bits_size = nodeIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [6:0]   nodeOut_a_bits_source = nodeIn_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [27:0]  nodeOut_a_bits_address = nodeIn_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [7:0]   nodeOut_a_bits_mask = nodeIn_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [63:0]  nodeOut_a_bits_data = nodeIn_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire         nodeOut_a_bits_corrupt = nodeIn_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire         nodeOut_d_ready = nodeIn_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire         nodeIn_d_valid = nodeOut_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]   nodeIn_d_bits_opcode = nodeOut_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [1:0]   nodeIn_d_bits_param = nodeOut_d_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [3:0]   nodeIn_d_bits_size = nodeOut_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [6:0]   nodeIn_d_bits_source = nodeOut_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire         nodeIn_d_bits_sink = nodeOut_d_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire         nodeIn_d_bits_denied = nodeOut_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [63:0]  nodeIn_d_bits_data = nodeOut_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire         nodeIn_d_bits_corrupt = nodeOut_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17
  wire [2:0]   a_id =
    {{nodeIn_a_bits_address[27],
      nodeIn_a_bits_address[25],
      nodeIn_a_bits_address[16],
      nodeIn_a_bits_address[13]} == 4'h0,
     {{nodeIn_a_bits_address[27],
       ~(nodeIn_a_bits_address[25]),
       nodeIn_a_bits_address[16]} == 3'h0,
      {nodeIn_a_bits_address[27],
       nodeIn_a_bits_address[25],
       nodeIn_a_bits_address[16],
       ~(nodeIn_a_bits_address[13])} == 4'h0} | {2{nodeIn_a_bits_address[27]}}}
    | ({nodeIn_a_bits_address[27],
        nodeIn_a_bits_address[25],
        ~(nodeIn_a_bits_address[16])} == 3'h0
         ? 3'h5
         : 3'h0);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}
  wire         a_noDomain = a_id == 3'h0;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/tilelink/FIFOFixer.scala:57:29
  wire         nodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire         _stalls_id_T_8 = nodeIn_a_ready & nodeIn_a_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [26:0]  _a_first_beats1_decode_T_1 = 27'hFFF << nodeIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/util/package.scala:235:71
  wire [8:0]   a_first_beats1_decode = ~(_a_first_beats1_decode_T_1[11:3]);	// src/main/scala/tilelink/Edges.scala:221:59, src/main/scala/util/package.scala:235:{46,71,76}
  wire         a_first_beats1_opdata = ~(nodeIn_a_bits_opcode[2]);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:93:{28,37}
  wire [8:0]   a_first_beats1 = a_first_beats1_opdata ? a_first_beats1_decode : 9'h0;	// src/main/scala/tilelink/Edges.scala:93:28, :221:59, :222:14, :230:27
  reg  [8:0]   a_first_counter;	// src/main/scala/tilelink/Edges.scala:230:27
  wire [8:0]   a_first_counter1 = a_first_counter - 9'h1;	// src/main/scala/tilelink/Edges.scala:230:27, :231:28
  wire         a_first = a_first_counter == 9'h0;	// src/main/scala/tilelink/Edges.scala:230:27, :232:25
  wire         a_first_last = a_first_counter == 9'h1 | a_first_beats1 == 9'h0;	// src/main/scala/tilelink/Edges.scala:222:14, :230:27, :233:{25,33,43}
  wire         a_first_done = a_first_last & _stalls_id_T_8;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/tilelink/Edges.scala:233:33, :234:22
  wire [8:0]   a_first_count = a_first_beats1 & ~a_first_counter1;	// src/main/scala/tilelink/Edges.scala:222:14, :231:28, :235:{25,27}
  wire         _d_first_T = nodeOut_d_ready & nodeOut_d_valid;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Nodes.scala:1205:17
  wire [26:0]  _d_first_beats1_decode_T_1 = 27'hFFF << nodeOut_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/util/package.scala:235:71
  wire [8:0]   d_first_beats1_decode = ~(_d_first_beats1_decode_T_1[11:3]);	// src/main/scala/tilelink/Edges.scala:221:59, src/main/scala/util/package.scala:235:{46,71,76}
  wire         d_first_beats1_opdata = nodeOut_d_bits_opcode[0];	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/Edges.scala:107:36
  wire [8:0]   d_first_beats1 = d_first_beats1_opdata ? d_first_beats1_decode : 9'h0;	// src/main/scala/tilelink/Edges.scala:107:36, :221:59, :222:14, :230:27
  reg  [8:0]   d_first_counter;	// src/main/scala/tilelink/Edges.scala:230:27
  wire [8:0]   d_first_counter1 = d_first_counter - 9'h1;	// src/main/scala/tilelink/Edges.scala:230:27, :231:28
  wire         d_first_first = d_first_counter == 9'h0;	// src/main/scala/tilelink/Edges.scala:230:27, :232:25
  wire         d_first_last = d_first_counter == 9'h1 | d_first_beats1 == 9'h0;	// src/main/scala/tilelink/Edges.scala:222:14, :230:27, :233:{25,33,43}
  wire         d_first_done = d_first_last & _d_first_T;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/tilelink/Edges.scala:233:33, :234:22
  wire [8:0]   d_first_count = d_first_beats1 & ~d_first_counter1;	// src/main/scala/tilelink/Edges.scala:222:14, :231:28, :235:{25,27}
  wire         d_first = d_first_first & nodeOut_d_bits_opcode != 3'h6;	// src/main/scala/diplomacy/Nodes.scala:1205:17, src/main/scala/tilelink/Edges.scala:232:25, src/main/scala/tilelink/FIFOFixer.scala:69:{42,63}
  reg          flight_0;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_1;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_2;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_3;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_4;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_5;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_6;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_7;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_8;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_9;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_10;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_11;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_12;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_13;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_14;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_15;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_16;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_17;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_18;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_19;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_20;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_21;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_22;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_23;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_24;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_25;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_26;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_27;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_28;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_29;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_30;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_31;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_32;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_33;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_34;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_35;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_36;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_37;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_38;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_39;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_40;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_41;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_42;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_43;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_44;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_45;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_46;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_47;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_48;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_49;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_50;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_51;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_52;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_53;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_54;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_55;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_56;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_57;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_58;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_59;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_60;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_61;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_62;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_63;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_64;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_65;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_66;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_67;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_68;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_69;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_70;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_71;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_72;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_73;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_74;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_75;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_76;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_77;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_78;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  reg          flight_79;	// src/main/scala/tilelink/FIFOFixer.scala:73:27
  wire         _GEN = a_first & _stalls_id_T_8;	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/tilelink/Edges.scala:232:25, src/main/scala/tilelink/FIFOFixer.scala:74:21
  wire         _GEN_0 = d_first & nodeIn_d_ready & nodeIn_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:69:42, :75:21
  wire [2:0]   stalls_a_sel_uncommonBits = nodeIn_a_bits_source[2:0];	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:52:56
  wire [2:0]   stalls_a_sel_uncommonBits_1 = nodeIn_a_bits_source[2:0];	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:52:56
  wire [2:0]   stalls_a_sel_uncommonBits_2 = nodeIn_a_bits_source[2:0];	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:52:56
  wire         stalls_a_sel = nodeIn_a_bits_source[6:3] == 4'h8;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:54:{10,32}, :56:48
  reg  [2:0]   stalls_id;	// src/main/scala/tilelink/FIFOFixer.scala:79:30
  wire         stalls_0 =
    stalls_a_sel & a_first
    & (flight_64 | flight_65 | flight_66 | flight_67 | flight_68 | flight_69 | flight_70
       | flight_71) & (a_noDomain | stalls_id != a_id);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/diplomacy/Parameters.scala:56:48, src/main/scala/tilelink/Edges.scala:232:25, src/main/scala/tilelink/FIFOFixer.scala:57:29, :73:27, :79:30, :82:{44,50,65,71}
  wire         stalls_a_sel_1 = nodeIn_a_bits_source[6:3] == 4'h9;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:54:{10,32}, :56:48
  reg  [2:0]   stalls_id_1;	// src/main/scala/tilelink/FIFOFixer.scala:79:30
  wire         stalls_1 =
    stalls_a_sel_1 & a_first
    & (flight_72 | flight_73 | flight_74 | flight_75 | flight_76 | flight_77 | flight_78
       | flight_79) & (a_noDomain | stalls_id_1 != a_id);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/diplomacy/Parameters.scala:56:48, src/main/scala/tilelink/Edges.scala:232:25, src/main/scala/tilelink/FIFOFixer.scala:57:29, :73:27, :79:30, :82:{44,50,65,71}
  wire         stalls_a_sel_2 = nodeIn_a_bits_source[6:3] == 4'h2;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/diplomacy/Parameters.scala:54:{10,32}, :56:48
  reg  [2:0]   stalls_id_2;	// src/main/scala/tilelink/FIFOFixer.scala:79:30
  wire         stalls_2 =
    stalls_a_sel_2 & a_first
    & (flight_16 | flight_17 | flight_18 | flight_19 | flight_20 | flight_21 | flight_22
       | flight_23) & (a_noDomain | stalls_id_2 != a_id);	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/diplomacy/Parameters.scala:56:48, src/main/scala/tilelink/Edges.scala:232:25, src/main/scala/tilelink/FIFOFixer.scala:57:29, :73:27, :79:30, :82:{44,50,65,71}
  wire         stall = stalls_0 | stalls_1 | stalls_2;	// src/main/scala/tilelink/FIFOFixer.scala:82:50, :85:45
  wire         nodeOut_a_valid = nodeIn_a_valid & ~stall;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/FIFOFixer.scala:85:45, :89:{33,50}
  assign nodeIn_a_ready = nodeOut_a_ready & ~stall;	// src/main/scala/diplomacy/Nodes.scala:1205:17, :1214:17, src/main/scala/tilelink/FIFOFixer.scala:85:45, :89:50, :90:33
  reg  [79:0]  SourceIdFIFOed;	// src/main/scala/tilelink/FIFOFixer.scala:109:35
  wire [127:0] _SourceIdSet_T = 128'h1 << nodeIn_a_bits_source;	// src/main/scala/chisel3/util/OneHot.scala:58:35, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [79:0]  SourceIdSet = _GEN ? _SourceIdSet_T[79:0] : 80'h0;	// src/main/scala/chisel3/util/OneHot.scala:58:35, src/main/scala/tilelink/FIFOFixer.scala:74:21, :109:35, :110:36, :113:50, :114:21
  wire [127:0] _SourceIdClear_T = 128'h1 << nodeIn_d_bits_source;	// src/main/scala/chisel3/util/OneHot.scala:58:35, src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [79:0]  SourceIdClear = _GEN_0 ? _SourceIdClear_T[79:0] : 80'h0;	// src/main/scala/chisel3/util/OneHot.scala:58:35, src/main/scala/tilelink/FIFOFixer.scala:75:21, :109:35, :111:38, :116:36, :117:23
  wire         allIDs_FIFOed = &SourceIdFIFOed;	// src/main/scala/tilelink/FIFOFixer.scala:109:35, :121:41
  always @(posedge clock) begin
    if (reset) begin
      a_first_counter <= 9'h0;	// src/main/scala/tilelink/Edges.scala:230:27
      d_first_counter <= 9'h0;	// src/main/scala/tilelink/Edges.scala:230:27
      flight_0 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_1 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_2 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_3 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_4 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_5 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_6 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_7 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_8 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_9 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_10 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_11 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_12 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_13 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_14 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_15 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_16 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_17 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_18 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_19 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_20 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_21 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_22 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_23 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_24 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_25 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_26 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_27 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_28 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_29 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_30 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_31 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_32 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_33 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_34 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_35 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_36 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_37 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_38 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_39 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_40 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_41 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_42 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_43 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_44 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_45 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_46 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_47 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_48 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_49 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_50 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_51 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_52 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_53 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_54 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_55 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_56 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_57 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_58 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_59 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_60 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_61 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_62 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_63 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_64 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_65 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_66 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_67 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_68 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_69 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_70 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_71 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_72 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_73 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_74 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_75 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_76 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_77 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_78 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      flight_79 <= 1'h0;	// src/main/scala/diplomacy/Parameters.scala:137:31, src/main/scala/tilelink/FIFOFixer.scala:73:27
      SourceIdFIFOed <= 80'h0;	// src/main/scala/tilelink/FIFOFixer.scala:109:35
    end
    else begin
      if (_stalls_id_T_8) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35
        if (a_first)	// src/main/scala/tilelink/Edges.scala:232:25
          a_first_counter <= a_first_beats1;	// src/main/scala/tilelink/Edges.scala:222:14, :230:27
        else	// src/main/scala/tilelink/Edges.scala:232:25
          a_first_counter <= a_first_counter1;	// src/main/scala/tilelink/Edges.scala:230:27, :231:28
      end
      if (_d_first_T) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35
        if (d_first_first)	// src/main/scala/tilelink/Edges.scala:232:25
          d_first_counter <= d_first_beats1;	// src/main/scala/tilelink/Edges.scala:222:14, :230:27
        else	// src/main/scala/tilelink/Edges.scala:232:25
          d_first_counter <= d_first_counter1;	// src/main/scala/tilelink/Edges.scala:230:27, :231:28
      end
      flight_0 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h0)
        & (_GEN & nodeIn_a_bits_source == 7'h0 | flight_0);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_1 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1)
        & (_GEN & nodeIn_a_bits_source == 7'h1 | flight_1);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_2 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2)
        & (_GEN & nodeIn_a_bits_source == 7'h2 | flight_2);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_3 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3)
        & (_GEN & nodeIn_a_bits_source == 7'h3 | flight_3);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_4 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4)
        & (_GEN & nodeIn_a_bits_source == 7'h4 | flight_4);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_5 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h5)
        & (_GEN & nodeIn_a_bits_source == 7'h5 | flight_5);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_6 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h6)
        & (_GEN & nodeIn_a_bits_source == 7'h6 | flight_6);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_7 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h7)
        & (_GEN & nodeIn_a_bits_source == 7'h7 | flight_7);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_8 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h8)
        & (_GEN & nodeIn_a_bits_source == 7'h8 | flight_8);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_9 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h9)
        & (_GEN & nodeIn_a_bits_source == 7'h9 | flight_9);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_10 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'hA)
        & (_GEN & nodeIn_a_bits_source == 7'hA | flight_10);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_11 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'hB)
        & (_GEN & nodeIn_a_bits_source == 7'hB | flight_11);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_12 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'hC)
        & (_GEN & nodeIn_a_bits_source == 7'hC | flight_12);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_13 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'hD)
        & (_GEN & nodeIn_a_bits_source == 7'hD | flight_13);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_14 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'hE)
        & (_GEN & nodeIn_a_bits_source == 7'hE | flight_14);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_15 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'hF)
        & (_GEN & nodeIn_a_bits_source == 7'hF | flight_15);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_16 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h10)
        & (_GEN & nodeIn_a_bits_source == 7'h10 | flight_16);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_17 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h11)
        & (_GEN & nodeIn_a_bits_source == 7'h11 | flight_17);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_18 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h12)
        & (_GEN & nodeIn_a_bits_source == 7'h12 | flight_18);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_19 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h13)
        & (_GEN & nodeIn_a_bits_source == 7'h13 | flight_19);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_20 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h14)
        & (_GEN & nodeIn_a_bits_source == 7'h14 | flight_20);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_21 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h15)
        & (_GEN & nodeIn_a_bits_source == 7'h15 | flight_21);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_22 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h16)
        & (_GEN & nodeIn_a_bits_source == 7'h16 | flight_22);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_23 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h17)
        & (_GEN & nodeIn_a_bits_source == 7'h17 | flight_23);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_24 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h18)
        & (_GEN & nodeIn_a_bits_source == 7'h18 | flight_24);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_25 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h19)
        & (_GEN & nodeIn_a_bits_source == 7'h19 | flight_25);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_26 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1A)
        & (_GEN & nodeIn_a_bits_source == 7'h1A | flight_26);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_27 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1B)
        & (_GEN & nodeIn_a_bits_source == 7'h1B | flight_27);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_28 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1C)
        & (_GEN & nodeIn_a_bits_source == 7'h1C | flight_28);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_29 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1D)
        & (_GEN & nodeIn_a_bits_source == 7'h1D | flight_29);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_30 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1E)
        & (_GEN & nodeIn_a_bits_source == 7'h1E | flight_30);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_31 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h1F)
        & (_GEN & nodeIn_a_bits_source == 7'h1F | flight_31);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_32 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h20)
        & (_GEN & nodeIn_a_bits_source == 7'h20 | flight_32);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_33 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h21)
        & (_GEN & nodeIn_a_bits_source == 7'h21 | flight_33);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_34 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h22)
        & (_GEN & nodeIn_a_bits_source == 7'h22 | flight_34);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_35 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h23)
        & (_GEN & nodeIn_a_bits_source == 7'h23 | flight_35);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_36 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h24)
        & (_GEN & nodeIn_a_bits_source == 7'h24 | flight_36);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_37 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h25)
        & (_GEN & nodeIn_a_bits_source == 7'h25 | flight_37);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_38 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h26)
        & (_GEN & nodeIn_a_bits_source == 7'h26 | flight_38);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_39 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h27)
        & (_GEN & nodeIn_a_bits_source == 7'h27 | flight_39);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_40 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h28)
        & (_GEN & nodeIn_a_bits_source == 7'h28 | flight_40);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_41 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h29)
        & (_GEN & nodeIn_a_bits_source == 7'h29 | flight_41);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_42 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2A)
        & (_GEN & nodeIn_a_bits_source == 7'h2A | flight_42);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_43 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2B)
        & (_GEN & nodeIn_a_bits_source == 7'h2B | flight_43);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_44 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2C)
        & (_GEN & nodeIn_a_bits_source == 7'h2C | flight_44);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_45 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2D)
        & (_GEN & nodeIn_a_bits_source == 7'h2D | flight_45);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_46 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2E)
        & (_GEN & nodeIn_a_bits_source == 7'h2E | flight_46);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_47 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h2F)
        & (_GEN & nodeIn_a_bits_source == 7'h2F | flight_47);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_48 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h30)
        & (_GEN & nodeIn_a_bits_source == 7'h30 | flight_48);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_49 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h31)
        & (_GEN & nodeIn_a_bits_source == 7'h31 | flight_49);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_50 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h32)
        & (_GEN & nodeIn_a_bits_source == 7'h32 | flight_50);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_51 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h33)
        & (_GEN & nodeIn_a_bits_source == 7'h33 | flight_51);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_52 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h34)
        & (_GEN & nodeIn_a_bits_source == 7'h34 | flight_52);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_53 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h35)
        & (_GEN & nodeIn_a_bits_source == 7'h35 | flight_53);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_54 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h36)
        & (_GEN & nodeIn_a_bits_source == 7'h36 | flight_54);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_55 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h37)
        & (_GEN & nodeIn_a_bits_source == 7'h37 | flight_55);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_56 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h38)
        & (_GEN & nodeIn_a_bits_source == 7'h38 | flight_56);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_57 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h39)
        & (_GEN & nodeIn_a_bits_source == 7'h39 | flight_57);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_58 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3A)
        & (_GEN & nodeIn_a_bits_source == 7'h3A | flight_58);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_59 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3B)
        & (_GEN & nodeIn_a_bits_source == 7'h3B | flight_59);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_60 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3C)
        & (_GEN & nodeIn_a_bits_source == 7'h3C | flight_60);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_61 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3D)
        & (_GEN & nodeIn_a_bits_source == 7'h3D | flight_61);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_62 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3E)
        & (_GEN & nodeIn_a_bits_source == 7'h3E | flight_62);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_63 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h3F)
        & (_GEN & nodeIn_a_bits_source == 7'h3F | flight_63);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_64 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h40)
        & (_GEN & nodeIn_a_bits_source == 7'h40 | flight_64);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_65 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h41)
        & (_GEN & nodeIn_a_bits_source == 7'h41 | flight_65);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_66 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h42)
        & (_GEN & nodeIn_a_bits_source == 7'h42 | flight_66);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_67 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h43)
        & (_GEN & nodeIn_a_bits_source == 7'h43 | flight_67);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_68 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h44)
        & (_GEN & nodeIn_a_bits_source == 7'h44 | flight_68);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_69 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h45)
        & (_GEN & nodeIn_a_bits_source == 7'h45 | flight_69);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_70 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h46)
        & (_GEN & nodeIn_a_bits_source == 7'h46 | flight_70);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_71 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h47)
        & (_GEN & nodeIn_a_bits_source == 7'h47 | flight_71);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_72 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h48)
        & (_GEN & nodeIn_a_bits_source == 7'h48 | flight_72);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_73 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h49)
        & (_GEN & nodeIn_a_bits_source == 7'h49 | flight_73);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_74 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4A)
        & (_GEN & nodeIn_a_bits_source == 7'h4A | flight_74);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_75 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4B)
        & (_GEN & nodeIn_a_bits_source == 7'h4B | flight_75);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_76 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4C)
        & (_GEN & nodeIn_a_bits_source == 7'h4C | flight_76);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_77 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4D)
        & (_GEN & nodeIn_a_bits_source == 7'h4D | flight_77);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_78 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4E)
        & (_GEN & nodeIn_a_bits_source == 7'h4E | flight_78);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      flight_79 <=
        ~(_GEN_0 & nodeIn_d_bits_source == 7'h4F)
        & (_GEN & nodeIn_a_bits_source == 7'h4F | flight_79);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/FIFOFixer.scala:73:27, :74:{21,35,62}, :75:{21,35,62}
      SourceIdFIFOed <= SourceIdFIFOed | SourceIdSet;	// src/main/scala/tilelink/FIFOFixer.scala:109:35, :110:36, :120:40
    end
    if (_stalls_id_T_8 & stalls_a_sel)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Parameters.scala:56:48, src/main/scala/tilelink/FIFOFixer.scala:79:47
      stalls_id <= a_id;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/tilelink/FIFOFixer.scala:79:30
    if (_stalls_id_T_8 & stalls_a_sel_1)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Parameters.scala:56:48, src/main/scala/tilelink/FIFOFixer.scala:79:47
      stalls_id_1 <= a_id;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/tilelink/FIFOFixer.scala:79:30
    if (_stalls_id_T_8 & stalls_a_sel_2)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Parameters.scala:56:48, src/main/scala/tilelink/FIFOFixer.scala:79:47
      stalls_id_2 <= a_id;	// src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/tilelink/FIFOFixer.scala:79:30
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:5];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        a_first_counter = _RANDOM[3'h0][8:0];	// src/main/scala/tilelink/Edges.scala:230:27
        d_first_counter = _RANDOM[3'h0][17:9];	// src/main/scala/tilelink/Edges.scala:230:27
        flight_0 = _RANDOM[3'h0][18];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_1 = _RANDOM[3'h0][19];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_2 = _RANDOM[3'h0][20];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_3 = _RANDOM[3'h0][21];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_4 = _RANDOM[3'h0][22];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_5 = _RANDOM[3'h0][23];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_6 = _RANDOM[3'h0][24];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_7 = _RANDOM[3'h0][25];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_8 = _RANDOM[3'h0][26];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_9 = _RANDOM[3'h0][27];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_10 = _RANDOM[3'h0][28];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_11 = _RANDOM[3'h0][29];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_12 = _RANDOM[3'h0][30];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_13 = _RANDOM[3'h0][31];	// src/main/scala/tilelink/Edges.scala:230:27, src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_14 = _RANDOM[3'h1][0];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_15 = _RANDOM[3'h1][1];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_16 = _RANDOM[3'h1][2];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_17 = _RANDOM[3'h1][3];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_18 = _RANDOM[3'h1][4];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_19 = _RANDOM[3'h1][5];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_20 = _RANDOM[3'h1][6];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_21 = _RANDOM[3'h1][7];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_22 = _RANDOM[3'h1][8];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_23 = _RANDOM[3'h1][9];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_24 = _RANDOM[3'h1][10];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_25 = _RANDOM[3'h1][11];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_26 = _RANDOM[3'h1][12];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_27 = _RANDOM[3'h1][13];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_28 = _RANDOM[3'h1][14];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_29 = _RANDOM[3'h1][15];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_30 = _RANDOM[3'h1][16];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_31 = _RANDOM[3'h1][17];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_32 = _RANDOM[3'h1][18];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_33 = _RANDOM[3'h1][19];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_34 = _RANDOM[3'h1][20];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_35 = _RANDOM[3'h1][21];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_36 = _RANDOM[3'h1][22];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_37 = _RANDOM[3'h1][23];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_38 = _RANDOM[3'h1][24];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_39 = _RANDOM[3'h1][25];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_40 = _RANDOM[3'h1][26];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_41 = _RANDOM[3'h1][27];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_42 = _RANDOM[3'h1][28];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_43 = _RANDOM[3'h1][29];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_44 = _RANDOM[3'h1][30];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_45 = _RANDOM[3'h1][31];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_46 = _RANDOM[3'h2][0];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_47 = _RANDOM[3'h2][1];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_48 = _RANDOM[3'h2][2];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_49 = _RANDOM[3'h2][3];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_50 = _RANDOM[3'h2][4];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_51 = _RANDOM[3'h2][5];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_52 = _RANDOM[3'h2][6];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_53 = _RANDOM[3'h2][7];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_54 = _RANDOM[3'h2][8];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_55 = _RANDOM[3'h2][9];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_56 = _RANDOM[3'h2][10];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_57 = _RANDOM[3'h2][11];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_58 = _RANDOM[3'h2][12];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_59 = _RANDOM[3'h2][13];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_60 = _RANDOM[3'h2][14];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_61 = _RANDOM[3'h2][15];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_62 = _RANDOM[3'h2][16];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_63 = _RANDOM[3'h2][17];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_64 = _RANDOM[3'h2][18];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_65 = _RANDOM[3'h2][19];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_66 = _RANDOM[3'h2][20];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_67 = _RANDOM[3'h2][21];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_68 = _RANDOM[3'h2][22];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_69 = _RANDOM[3'h2][23];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_70 = _RANDOM[3'h2][24];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_71 = _RANDOM[3'h2][25];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_72 = _RANDOM[3'h2][26];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_73 = _RANDOM[3'h2][27];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_74 = _RANDOM[3'h2][28];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_75 = _RANDOM[3'h2][29];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_76 = _RANDOM[3'h2][30];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_77 = _RANDOM[3'h2][31];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_78 = _RANDOM[3'h3][0];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        flight_79 = _RANDOM[3'h3][1];	// src/main/scala/tilelink/FIFOFixer.scala:73:27
        stalls_id = _RANDOM[3'h3][4:2];	// src/main/scala/tilelink/FIFOFixer.scala:73:27, :79:30
        stalls_id_1 = _RANDOM[3'h3][7:5];	// src/main/scala/tilelink/FIFOFixer.scala:73:27, :79:30
        stalls_id_2 = _RANDOM[3'h3][10:8];	// src/main/scala/tilelink/FIFOFixer.scala:73:27, :79:30
        SourceIdFIFOed = {_RANDOM[3'h3][31:11], _RANDOM[3'h4], _RANDOM[3'h5][26:0]};	// src/main/scala/tilelink/FIFOFixer.scala:73:27, :109:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_8 monitor (	// src/main/scala/tilelink/Nodes.scala:24:25
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (nodeIn_a_ready),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_valid        (nodeIn_a_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_opcode  (nodeIn_a_bits_opcode),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_param   (nodeIn_a_bits_param),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_size    (nodeIn_a_bits_size),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_source  (nodeIn_a_bits_source),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_address (nodeIn_a_bits_address),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_mask    (nodeIn_a_bits_mask),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_corrupt (nodeIn_a_bits_corrupt),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_ready        (nodeIn_d_ready),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_valid        (nodeIn_d_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_param   (nodeIn_d_bits_param),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_size    (nodeIn_d_bits_size),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_source  (nodeIn_d_bits_source),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_sink    (nodeIn_d_bits_sink),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_denied  (nodeIn_d_bits_denied),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_corrupt (nodeIn_d_bits_corrupt)	// src/main/scala/diplomacy/Nodes.scala:1214:17
  );
  assign auto_in_a_ready = nodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_valid = nodeIn_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_param = nodeIn_d_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_size = nodeIn_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_source = nodeIn_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_sink = nodeIn_d_bits_sink;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_denied = nodeIn_d_bits_denied;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_data = nodeIn_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_corrupt = nodeIn_d_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_out_a_valid = nodeOut_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_opcode = nodeOut_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_param = nodeOut_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_size = nodeOut_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_source = nodeOut_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_address = nodeOut_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_mask = nodeOut_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_data = nodeOut_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_a_bits_corrupt = nodeOut_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1205:17
  assign auto_out_d_ready = nodeOut_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1205:17
endmodule

