// Generated by CIRCT firtool-1.56.1
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module WritebackQueue(
  input          clock,
                 reset,
                 io_req_valid,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
                 io_req_bits_voluntary,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input  [32:0]  io_req_bits_lineAddr,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input  [2:0]   io_req_bits_perm,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input          io_req_bits_hasData,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input  [511:0] io_req_bits_data,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input  [4:0]   io_req_bits_source,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input          io_missCheck_valid,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input  [32:0]  io_missCheck_lineAddr,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input          io_release_ready,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
                 io_grant_valid,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  input  [4:0]   io_grant_bits_source,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  output         io_req_ready,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
                 io_missCheck_blockMiss,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
                 io_release_valid,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  output [2:0]   io_release_bits_opcode,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
                 io_release_bits_param,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  output [4:0]   io_release_bits_source,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  output [31:0]  io_release_bits_address,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  output [63:0]  io_release_bits_data,	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
  output         io_grant_ready	// src/main/scala/gpcdcache/WritebackQueue.scala:161:14
);

  wire             releaseVec_0_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_1_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_2_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_3_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_4_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_5_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_6_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_7_bits_corrupt = 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [3:0]       releaseVec_0_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_1_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_2_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_3_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_4_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_5_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_6_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  wire [3:0]       releaseVec_7_bits_size = 4'h6;	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25, :196:27
  reg              enqPtr_flag;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23
  reg  [2:0]       enqPtr_value;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23
  reg              deqPtr_flag;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23
  reg  [2:0]       deqPtr_value;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23
  wire [3:0]       _enqPtr_new_ptr_WIRE_1 = {enqPtr_flag, enqPtr_value} + 4'h1;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, src/main/scala/utility/CircularQueuePtr.scala:39:46
  wire [2:0]       enqPtr_new_ptr_value = _enqPtr_new_ptr_WIRE_1[2:0];	// src/main/scala/utility/CircularQueuePtr.scala:37:23, :39:{46,59}
  wire             enqPtr_new_ptr_flag = _enqPtr_new_ptr_WIRE_1[3];	// src/main/scala/utility/CircularQueuePtr.scala:37:23, :39:{46,59}
  wire             releaseVec_0_ready = deqPtr_value == 3'h0 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:36, :169:23, :196:27, :198:{35,44}
  wire             releaseVec_1_ready = deqPtr_value == 3'h1 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :176:57, :196:27, :198:{35,44}
  wire             releaseVec_2_ready = deqPtr_value == 3'h2 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :176:57, :196:27, :198:{35,44}
  wire             releaseVec_3_ready = deqPtr_value == 3'h3 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :176:57, :196:27, :198:{35,44}
  wire             releaseVec_4_ready = deqPtr_value == 3'h4 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :176:57, :196:27, :198:{35,44}
  wire             releaseVec_5_ready = deqPtr_value == 3'h5 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :176:57, :196:27, :198:{35,44}
  wire             releaseVec_6_ready = deqPtr_value == 3'h6 & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :176:57, :196:27, :198:{35,44}
  wire             releaseVec_0_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_1_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_2_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_3_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_4_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_5_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_6_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire             releaseVec_7_ready = (&deqPtr_value) & io_release_ready;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :196:27, :198:{35,44}
  wire             releaseVec_7_valid;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [7:0]       _GEN =
    {{releaseVec_7_valid},
     {releaseVec_6_valid},
     {releaseVec_5_valid},
     {releaseVec_4_valid},
     {releaseVec_3_valid},
     {releaseVec_2_valid},
     {releaseVec_1_valid},
     {releaseVec_0_valid}};	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27, :201:20
  wire [2:0]       releaseVec_0_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_1_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_2_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_3_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_4_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_5_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_6_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_7_bits_opcode;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [7:0][2:0]  _GEN_0 =
    {{releaseVec_7_bits_opcode},
     {releaseVec_6_bits_opcode},
     {releaseVec_5_bits_opcode},
     {releaseVec_4_bits_opcode},
     {releaseVec_3_bits_opcode},
     {releaseVec_2_bits_opcode},
     {releaseVec_1_bits_opcode},
     {releaseVec_0_bits_opcode}};	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27, :201:20
  wire [2:0]       releaseVec_0_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_1_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_2_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_3_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_4_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_5_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_6_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [2:0]       releaseVec_7_bits_param;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [7:0][2:0]  _GEN_1 =
    {{releaseVec_7_bits_param},
     {releaseVec_6_bits_param},
     {releaseVec_5_bits_param},
     {releaseVec_4_bits_param},
     {releaseVec_3_bits_param},
     {releaseVec_2_bits_param},
     {releaseVec_1_bits_param},
     {releaseVec_0_bits_param}};	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27, :201:20
  wire [4:0]       releaseVec_0_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_1_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_2_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_3_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_4_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_5_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_6_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [4:0]       releaseVec_7_bits_source;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [7:0][4:0]  _GEN_2 =
    {{releaseVec_7_bits_source},
     {releaseVec_6_bits_source},
     {releaseVec_5_bits_source},
     {releaseVec_4_bits_source},
     {releaseVec_3_bits_source},
     {releaseVec_2_bits_source},
     {releaseVec_1_bits_source},
     {releaseVec_0_bits_source}};	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27, :201:20
  wire [31:0]      releaseVec_0_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_1_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_2_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_3_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_4_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_5_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_6_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [31:0]      releaseVec_7_bits_address;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [7:0][31:0] _GEN_3 =
    {{releaseVec_7_bits_address},
     {releaseVec_6_bits_address},
     {releaseVec_5_bits_address},
     {releaseVec_4_bits_address},
     {releaseVec_3_bits_address},
     {releaseVec_2_bits_address},
     {releaseVec_1_bits_address},
     {releaseVec_0_bits_address}};	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27, :201:20
  wire [63:0]      releaseVec_0_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_1_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_2_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_3_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_4_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_5_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_6_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [63:0]      releaseVec_7_bits_data;	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
  wire [7:0][63:0] _GEN_4 =
    {{releaseVec_7_bits_data},
     {releaseVec_6_bits_data},
     {releaseVec_5_bits_data},
     {releaseVec_4_bits_data},
     {releaseVec_3_bits_data},
     {releaseVec_2_bits_data},
     {releaseVec_1_bits_data},
     {releaseVec_0_bits_data}};	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27, :201:20
  wire             grantReadyVec_0;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_1;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_2;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_3;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_4;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_5;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_6;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire             grantReadyVec_7;	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30
  wire [7:0]       _GEN_5 =
    {{grantReadyVec_7},
     {grantReadyVec_6},
     {grantReadyVec_5},
     {grantReadyVec_4},
     {grantReadyVec_3},
     {grantReadyVec_2},
     {grantReadyVec_1},
     {grantReadyVec_0}};	// src/main/scala/gpcdcache/WritebackQueue.scala:205:30, :206:18
  wire [3:0]       _deqPtr_new_ptr_WIRE_1 = {deqPtr_flag, deqPtr_value} + 4'h1;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, src/main/scala/utility/CircularQueuePtr.scala:39:46
  wire [2:0]       deqPtr_new_ptr_value = _deqPtr_new_ptr_WIRE_1[2:0];	// src/main/scala/utility/CircularQueuePtr.scala:37:23, :39:{46,59}
  wire             deqPtr_new_ptr_flag = _deqPtr_new_ptr_WIRE_1[3];	// src/main/scala/utility/CircularQueuePtr.scala:37:23, :39:{46,59}
  wire             blockMissVec_0;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_1;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_2;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_3;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_4;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_5;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_6;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             blockMissVec_7;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29
  wire             _io_req_ready_T_2 =
    enqPtr_flag != deqPtr_flag & enqPtr_value == deqPtr_value;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :169:23, src/main/scala/utility/CircularQueuePtr.scala:99:{19,37,55}
  wire             wbFinishVec_0;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_1;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_2;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_3;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_4;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_5;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_6;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  wire             wbFinishVec_7;	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28
  always @(posedge clock) begin
    if (reset) begin
      enqPtr_flag <= 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23
      enqPtr_value <= 3'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:{23,36}
      deqPtr_flag <= 1'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23
      deqPtr_value <= 3'h0;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:36, :169:23
    end
    else begin
      automatic logic [7:0] _GEN_6 =
        {{wbFinishVec_7},
         {wbFinishVec_6},
         {wbFinishVec_5},
         {wbFinishVec_4},
         {wbFinishVec_3},
         {wbFinishVec_2},
         {wbFinishVec_1},
         {wbFinishVec_0}};	// src/main/scala/gpcdcache/WritebackQueue.scala:209:28, :211:35
      if (~_io_req_ready_T_2 & io_req_valid) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/gpcdcache/WritebackQueue.scala:219:19, src/main/scala/utility/CircularQueuePtr.scala:99:37
        enqPtr_flag <= enqPtr_new_ptr_flag;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, src/main/scala/utility/CircularQueuePtr.scala:37:23
        enqPtr_value <= enqPtr_new_ptr_value;	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, src/main/scala/utility/CircularQueuePtr.scala:37:23
      end
      if (_GEN_6[deqPtr_value]) begin	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :211:35
        deqPtr_flag <= deqPtr_new_ptr_flag;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, src/main/scala/utility/CircularQueuePtr.scala:37:23
        deqPtr_value <= deqPtr_new_ptr_value;	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, src/main/scala/utility/CircularQueuePtr.scala:37:23
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:0];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        enqPtr_flag = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23
        enqPtr_value = _RANDOM[/*Zero width*/ 1'b0][3:1];	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23
        deqPtr_flag = _RANDOM[/*Zero width*/ 1'b0][4];	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :169:23
        deqPtr_value = _RANDOM[/*Zero width*/ 1'b0][7:5];	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :169:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  WritebackEntry wbqEntries_0 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h0),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:{23,36}, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_0_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'h8),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_0),
    .io_release_valid        (releaseVec_0_valid),
    .io_release_bits_opcode  (releaseVec_0_bits_opcode),
    .io_release_bits_param   (releaseVec_0_bits_param),
    .io_release_bits_source  (releaseVec_0_bits_source),
    .io_release_bits_address (releaseVec_0_bits_address),
    .io_release_bits_data    (releaseVec_0_bits_data),
    .io_grant_ready          (grantReadyVec_0),
    .io_wbFinish             (wbFinishVec_0)
  );
  WritebackEntry_1 wbqEntries_1 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h1),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_1_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'h9),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_1),
    .io_release_valid        (releaseVec_1_valid),
    .io_release_bits_opcode  (releaseVec_1_bits_opcode),
    .io_release_bits_param   (releaseVec_1_bits_param),
    .io_release_bits_source  (releaseVec_1_bits_source),
    .io_release_bits_address (releaseVec_1_bits_address),
    .io_release_bits_data    (releaseVec_1_bits_data),
    .io_grant_ready          (grantReadyVec_1),
    .io_wbFinish             (wbFinishVec_1)
  );
  WritebackEntry_2 wbqEntries_2 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h2),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_2_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'hA),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_2),
    .io_release_valid        (releaseVec_2_valid),
    .io_release_bits_opcode  (releaseVec_2_bits_opcode),
    .io_release_bits_param   (releaseVec_2_bits_param),
    .io_release_bits_source  (releaseVec_2_bits_source),
    .io_release_bits_address (releaseVec_2_bits_address),
    .io_release_bits_data    (releaseVec_2_bits_data),
    .io_grant_ready          (grantReadyVec_2),
    .io_wbFinish             (wbFinishVec_2)
  );
  WritebackEntry_3 wbqEntries_3 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h3),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_3_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'hB),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_3),
    .io_release_valid        (releaseVec_3_valid),
    .io_release_bits_opcode  (releaseVec_3_bits_opcode),
    .io_release_bits_param   (releaseVec_3_bits_param),
    .io_release_bits_source  (releaseVec_3_bits_source),
    .io_release_bits_address (releaseVec_3_bits_address),
    .io_release_bits_data    (releaseVec_3_bits_data),
    .io_grant_ready          (grantReadyVec_3),
    .io_wbFinish             (wbFinishVec_3)
  );
  WritebackEntry_4 wbqEntries_4 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h4),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_4_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'hC),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_4),
    .io_release_valid        (releaseVec_4_valid),
    .io_release_bits_opcode  (releaseVec_4_bits_opcode),
    .io_release_bits_param   (releaseVec_4_bits_param),
    .io_release_bits_source  (releaseVec_4_bits_source),
    .io_release_bits_address (releaseVec_4_bits_address),
    .io_release_bits_data    (releaseVec_4_bits_data),
    .io_grant_ready          (grantReadyVec_4),
    .io_wbFinish             (wbFinishVec_4)
  );
  WritebackEntry_5 wbqEntries_5 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h5),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_5_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'hD),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_5),
    .io_release_valid        (releaseVec_5_valid),
    .io_release_bits_opcode  (releaseVec_5_bits_opcode),
    .io_release_bits_param   (releaseVec_5_bits_param),
    .io_release_bits_source  (releaseVec_5_bits_source),
    .io_release_bits_address (releaseVec_5_bits_address),
    .io_release_bits_data    (releaseVec_5_bits_data),
    .io_grant_ready          (grantReadyVec_5),
    .io_wbFinish             (wbFinishVec_5)
  );
  WritebackEntry_6 wbqEntries_6 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & enqPtr_value == 3'h6),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_6_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'hE),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_6),
    .io_release_valid        (releaseVec_6_valid),
    .io_release_bits_opcode  (releaseVec_6_bits_opcode),
    .io_release_bits_param   (releaseVec_6_bits_param),
    .io_release_bits_source  (releaseVec_6_bits_source),
    .io_release_bits_address (releaseVec_6_bits_address),
    .io_release_bits_data    (releaseVec_6_bits_data),
    .io_grant_ready          (grantReadyVec_6),
    .io_wbFinish             (wbFinishVec_6)
  );
  WritebackEntry_7 wbqEntries_7 (	// src/main/scala/gpcdcache/WritebackQueue.scala:173:25
    .clock                   (clock),
    .reset                   (reset),
    .io_req_valid            (io_req_valid & (&enqPtr_value)),	// src/main/scala/gpcdcache/WritebackQueue.scala:168:23, :176:{40,57}
    .io_req_bits_voluntary   (io_req_bits_voluntary),
    .io_req_bits_lineAddr    (io_req_bits_lineAddr),
    .io_req_bits_perm        (io_req_bits_perm),
    .io_req_bits_hasData     (io_req_bits_hasData),
    .io_req_bits_data        (io_req_bits_data),
    .io_req_bits_source      (io_req_bits_source),
    .io_missCheck_valid      (io_missCheck_valid),
    .io_missCheck_lineAddr   (io_missCheck_lineAddr),
    .io_release_ready        (releaseVec_7_ready),	// src/main/scala/gpcdcache/WritebackQueue.scala:196:27
    .io_grant_valid          (io_grant_valid & io_grant_bits_source == 5'hF),	// src/main/scala/gpcdcache/WritebackQueue.scala:184:{45,69}
    .io_missCheck_blockMiss  (blockMissVec_7),
    .io_release_valid        (releaseVec_7_valid),
    .io_release_bits_opcode  (releaseVec_7_bits_opcode),
    .io_release_bits_param   (releaseVec_7_bits_param),
    .io_release_bits_source  (releaseVec_7_bits_source),
    .io_release_bits_address (releaseVec_7_bits_address),
    .io_release_bits_data    (releaseVec_7_bits_data),
    .io_grant_ready          (grantReadyVec_7),
    .io_wbFinish             (wbFinishVec_7)
  );
  assign io_req_ready = ~_io_req_ready_T_2;	// src/main/scala/gpcdcache/WritebackQueue.scala:219:19, src/main/scala/utility/CircularQueuePtr.scala:99:37
  assign io_missCheck_blockMiss =
    blockMissVec_0 | blockMissVec_1 | blockMissVec_2 | blockMissVec_3 | blockMissVec_4
    | blockMissVec_5 | blockMissVec_6 | blockMissVec_7;	// src/main/scala/gpcdcache/WritebackQueue.scala:216:29, :217:51
  assign io_release_valid = _GEN[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :201:20
  assign io_release_bits_opcode = _GEN_0[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :201:20
  assign io_release_bits_param = _GEN_1[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :201:20
  assign io_release_bits_source = _GEN_2[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :201:20
  assign io_release_bits_address = _GEN_3[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :201:20
  assign io_release_bits_data = _GEN_4[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :201:20
  assign io_grant_ready = _GEN_5[deqPtr_value];	// src/main/scala/gpcdcache/WritebackQueue.scala:169:23, :206:18
endmodule

