#!/bin/bash

input_file="/datahdd/riscv/$USER/GPC_verif_env/vpu_grape_cove/sim_regress/regress.log"
output_file_pass="/datahdd/riscv/$USER/GPC_verif_env/vpu_grape_cove/common/tc_list_riscv-tests-passed"
output_file_fail="/datahdd/riscv/$USER/GPC_verif_env/vpu_grape_cove/common/tc_list_riscv-tests-fail"

> "$output_file_pass"
> "$output_file_fail"

while IFS= read -r line; do
  elf_name=$(echo "$line" | grep -o 'rv64[^ ]*\.elf')
  if echo "$line" | grep -q "PASS"; then
    echo "{mode=\"base_func\", tc=\"instr_test\" ,cfg=\"$elf_name\"   ,num=\"1\",fsdb=\"off\",cov=\"on\",cfg_dir=\"../tc/sequence/riscv-tests\"}" >> "$output_file_pass"
  elif echo "$line" | grep -q "FAIL"; then
    echo "{mode=\"base_func\", tc=\"instr_test\" ,cfg=\"$elf_name\"   ,num=\"1\",fsdb=\"off\",cov=\"on\",cfg_dir=\"../tc/sequence/riscv-tests\"}" >> "$output_file_fail"
  fi
done < "$input_file"
